template: native
provider: pocket-id
major-version: 0
providerDefaultBranch: main
publishRegistry: false
providerVersion: github.com/axnic/pulumi-pocket-id/provider.Version
parallel: 3
sdkModuleDir: sdk/go/pulumi-pocket-id
esc:
    enabled: true
    environment: imports/github-secrets
