# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

import types

__config__ = pulumi.Config('pocket-id')


class _ExportableConfig(types.ModuleType):
    @_builtins.property
    def api_key(self) -> Optional[str]:
        """
        A Pocket-ID API key sent with every request in the X-API-Key header. Falls back to the POCKET_ID_API_KEY environment variable if not set.
        """
        return __config__.get('apiKey')

    @_builtins.property
    def base_url(self) -> Optional[str]:
        """
        The base URL of the Pocket-ID server, e.g. "https://pocket-id.example.com". Falls back to the POCKET_ID_BASE_URL environment variable if not set.
        """
        return __config__.get('baseUrl')

