// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId.Inputs
{

    public sealed class ApiPermissionArgsArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// A description of the permission.
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// The stable identifier of the permission, e.g. "read:orders". Unique within the API.
        /// </summary>
        [Input("key", required: true)]
        public Input<string> Key { get; set; } = null!;

        /// <summary>
        /// The display name of the permission.
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        public ApiPermissionArgsArgs()
        {
        }
        public static new ApiPermissionArgsArgs Empty => new ApiPermissionArgsArgs();
    }
}
