// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId.Inputs
{

    public sealed class FederatedIdentityArgs : global::Pulumi.ResourceArgs
    {
        [Input("audience")]
        public Input<string>? Audience { get; set; }

        [Input("issuer", required: true)]
        public Input<string> Issuer { get; set; } = null!;

        [Input("jwks")]
        public Input<string>? Jwks { get; set; }

        [Input("replayProtection")]
        public Input<bool>? ReplayProtection { get; set; }

        [Input("subject")]
        public Input<string>? Subject { get; set; }

        public FederatedIdentityArgs()
        {
        }
        public static new FederatedIdentityArgs Empty => new FederatedIdentityArgs();
    }
}
