// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId.Inputs
{

    public sealed class OidcFederatedIdentityArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The expected audience of the federated identity.
        /// </summary>
        [Input("audience")]
        public Input<string>? Audience { get; set; }

        /// <summary>
        /// The issuer URL of the federated identity.
        /// </summary>
        [Input("issuer", required: true)]
        public Input<string> Issuer { get; set; } = null!;

        /// <summary>
        /// The URL or content of the JWKS used to verify the federated identity.
        /// </summary>
        [Input("jwks")]
        public Input<string>? Jwks { get; set; }

        /// <summary>
        /// Whether tokens issued by the federated identity can only be used once.
        /// </summary>
        [Input("replayProtection")]
        public Input<bool>? ReplayProtection { get; set; }

        /// <summary>
        /// The expected subject of the federated identity.
        /// </summary>
        [Input("subject")]
        public Input<string>? Subject { get; set; }

        public OidcFederatedIdentityArgs()
        {
        }
        public static new OidcFederatedIdentityArgs Empty => new OidcFederatedIdentityArgs();
    }
}
