// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/axnic/pulumi-pocket-id/sdk/go/pulumi-pocket-id/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

// A Pocket-ID API key sent with every request in the X-API-Key header. Falls back to the POCKET_ID_API_KEY environment variable if not set.
func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "pocket-id:apiKey")
}

// The base URL of the Pocket-ID server, e.g. "https://pocket-id.example.com". Falls back to the POCKET_ID_BASE_URL environment variable if not set.
func GetBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "pocket-id:baseUrl")
}
