// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package config

import (
	"github.com/axnic/pulumi-pocket-id/sdk/go/pulumi-pocket-id/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi/config"
)

var _ = internal.GetEnvOrDefault

func GetApiKey(ctx *pulumi.Context) string {
	return config.Get(ctx, "pocket-id:apiKey")
}
func GetBaseUrl(ctx *pulumi.Context) string {
	return config.Get(ctx, "pocket-id:baseUrl")
}
