// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumipocketid

import (
	"context"
	"reflect"

	"errors"
	"github.com/axnic/pulumi-pocket-id/sdk/go/pulumi-pocket-id/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// The access of an OIDC client on an API. Authoritative for the (API, client) pair; import with the ID "<apiId>/<clientId>".
type ApiClientGrant struct {
	pulumi.CustomResourceState

	// The ID of the API. Changing it replaces the grant.
	ApiId pulumi.StringOutput `pulumi:"apiId"`
	// Whether the client may access the API on its own behalf (client credentials flow).
	ClientAccess pulumi.BoolPtrOutput `pulumi:"clientAccess"`
	// The ID of the OIDC client. Changing it replaces the grant.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// The keys of the API permissions granted to the client on its own behalf.
	ClientPermissionKeys pulumi.StringArrayOutput `pulumi:"clientPermissionKeys"`
	// Whether the client may access the API on behalf of users.
	UserDelegatedAccess pulumi.BoolPtrOutput `pulumi:"userDelegatedAccess"`
	// The keys of the API permissions the client may use on behalf of users.
	UserDelegatedPermissionKeys pulumi.StringArrayOutput `pulumi:"userDelegatedPermissionKeys"`
}

// NewApiClientGrant registers a new resource with the given unique name, arguments, and options.
func NewApiClientGrant(ctx *pulumi.Context,
	name string, args *ApiClientGrantArgs, opts ...pulumi.ResourceOption) (*ApiClientGrant, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ApiId == nil {
		return nil, errors.New("invalid value for required argument 'ApiId'")
	}
	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"apiId",
		"clientId",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ApiClientGrant
	err := ctx.RegisterResource("pocket-id:index:ApiClientGrant", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetApiClientGrant gets an existing ApiClientGrant resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetApiClientGrant(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ApiClientGrantState, opts ...pulumi.ResourceOption) (*ApiClientGrant, error) {
	var resource ApiClientGrant
	err := ctx.ReadResource("pocket-id:index:ApiClientGrant", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ApiClientGrant resources.
type apiClientGrantState struct {
}

type ApiClientGrantState struct {
}

func (ApiClientGrantState) ElementType() reflect.Type {
	return reflect.TypeOf((*apiClientGrantState)(nil)).Elem()
}

type apiClientGrantArgs struct {
	// The ID of the API. Changing it replaces the grant.
	ApiId string `pulumi:"apiId"`
	// Whether the client may access the API on its own behalf (client credentials flow).
	ClientAccess *bool `pulumi:"clientAccess"`
	// The ID of the OIDC client. Changing it replaces the grant.
	ClientId string `pulumi:"clientId"`
	// The keys of the API permissions granted to the client on its own behalf.
	ClientPermissionKeys []string `pulumi:"clientPermissionKeys"`
	// Whether the client may access the API on behalf of users.
	UserDelegatedAccess *bool `pulumi:"userDelegatedAccess"`
	// The keys of the API permissions the client may use on behalf of users.
	UserDelegatedPermissionKeys []string `pulumi:"userDelegatedPermissionKeys"`
}

// The set of arguments for constructing a ApiClientGrant resource.
type ApiClientGrantArgs struct {
	// The ID of the API. Changing it replaces the grant.
	ApiId pulumi.StringInput
	// Whether the client may access the API on its own behalf (client credentials flow).
	ClientAccess pulumi.BoolPtrInput
	// The ID of the OIDC client. Changing it replaces the grant.
	ClientId pulumi.StringInput
	// The keys of the API permissions granted to the client on its own behalf.
	ClientPermissionKeys pulumi.StringArrayInput
	// Whether the client may access the API on behalf of users.
	UserDelegatedAccess pulumi.BoolPtrInput
	// The keys of the API permissions the client may use on behalf of users.
	UserDelegatedPermissionKeys pulumi.StringArrayInput
}

func (ApiClientGrantArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*apiClientGrantArgs)(nil)).Elem()
}

type ApiClientGrantInput interface {
	pulumi.Input

	ToApiClientGrantOutput() ApiClientGrantOutput
	ToApiClientGrantOutputWithContext(ctx context.Context) ApiClientGrantOutput
}

func (*ApiClientGrant) ElementType() reflect.Type {
	return reflect.TypeOf((**ApiClientGrant)(nil)).Elem()
}

func (i *ApiClientGrant) ToApiClientGrantOutput() ApiClientGrantOutput {
	return i.ToApiClientGrantOutputWithContext(context.Background())
}

func (i *ApiClientGrant) ToApiClientGrantOutputWithContext(ctx context.Context) ApiClientGrantOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApiClientGrantOutput)
}

// ApiClientGrantArrayInput is an input type that accepts ApiClientGrantArray and ApiClientGrantArrayOutput values.
// You can construct a concrete instance of `ApiClientGrantArrayInput` via:
//
//	ApiClientGrantArray{ ApiClientGrantArgs{...} }
type ApiClientGrantArrayInput interface {
	pulumi.Input

	ToApiClientGrantArrayOutput() ApiClientGrantArrayOutput
	ToApiClientGrantArrayOutputWithContext(context.Context) ApiClientGrantArrayOutput
}

type ApiClientGrantArray []ApiClientGrantInput

func (ApiClientGrantArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApiClientGrant)(nil)).Elem()
}

func (i ApiClientGrantArray) ToApiClientGrantArrayOutput() ApiClientGrantArrayOutput {
	return i.ToApiClientGrantArrayOutputWithContext(context.Background())
}

func (i ApiClientGrantArray) ToApiClientGrantArrayOutputWithContext(ctx context.Context) ApiClientGrantArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApiClientGrantArrayOutput)
}

// ApiClientGrantMapInput is an input type that accepts ApiClientGrantMap and ApiClientGrantMapOutput values.
// You can construct a concrete instance of `ApiClientGrantMapInput` via:
//
//	ApiClientGrantMap{ "key": ApiClientGrantArgs{...} }
type ApiClientGrantMapInput interface {
	pulumi.Input

	ToApiClientGrantMapOutput() ApiClientGrantMapOutput
	ToApiClientGrantMapOutputWithContext(context.Context) ApiClientGrantMapOutput
}

type ApiClientGrantMap map[string]ApiClientGrantInput

func (ApiClientGrantMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApiClientGrant)(nil)).Elem()
}

func (i ApiClientGrantMap) ToApiClientGrantMapOutput() ApiClientGrantMapOutput {
	return i.ToApiClientGrantMapOutputWithContext(context.Background())
}

func (i ApiClientGrantMap) ToApiClientGrantMapOutputWithContext(ctx context.Context) ApiClientGrantMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ApiClientGrantMapOutput)
}

type ApiClientGrantOutput struct{ *pulumi.OutputState }

func (ApiClientGrantOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ApiClientGrant)(nil)).Elem()
}

func (o ApiClientGrantOutput) ToApiClientGrantOutput() ApiClientGrantOutput {
	return o
}

func (o ApiClientGrantOutput) ToApiClientGrantOutputWithContext(ctx context.Context) ApiClientGrantOutput {
	return o
}

// The ID of the API. Changing it replaces the grant.
func (o ApiClientGrantOutput) ApiId() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiClientGrant) pulumi.StringOutput { return v.ApiId }).(pulumi.StringOutput)
}

// Whether the client may access the API on its own behalf (client credentials flow).
func (o ApiClientGrantOutput) ClientAccess() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ApiClientGrant) pulumi.BoolPtrOutput { return v.ClientAccess }).(pulumi.BoolPtrOutput)
}

// The ID of the OIDC client. Changing it replaces the grant.
func (o ApiClientGrantOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *ApiClientGrant) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// The keys of the API permissions granted to the client on its own behalf.
func (o ApiClientGrantOutput) ClientPermissionKeys() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ApiClientGrant) pulumi.StringArrayOutput { return v.ClientPermissionKeys }).(pulumi.StringArrayOutput)
}

// Whether the client may access the API on behalf of users.
func (o ApiClientGrantOutput) UserDelegatedAccess() pulumi.BoolPtrOutput {
	return o.ApplyT(func(v *ApiClientGrant) pulumi.BoolPtrOutput { return v.UserDelegatedAccess }).(pulumi.BoolPtrOutput)
}

// The keys of the API permissions the client may use on behalf of users.
func (o ApiClientGrantOutput) UserDelegatedPermissionKeys() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *ApiClientGrant) pulumi.StringArrayOutput { return v.UserDelegatedPermissionKeys }).(pulumi.StringArrayOutput)
}

type ApiClientGrantArrayOutput struct{ *pulumi.OutputState }

func (ApiClientGrantArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ApiClientGrant)(nil)).Elem()
}

func (o ApiClientGrantArrayOutput) ToApiClientGrantArrayOutput() ApiClientGrantArrayOutput {
	return o
}

func (o ApiClientGrantArrayOutput) ToApiClientGrantArrayOutputWithContext(ctx context.Context) ApiClientGrantArrayOutput {
	return o
}

func (o ApiClientGrantArrayOutput) Index(i pulumi.IntInput) ApiClientGrantOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ApiClientGrant {
		return vs[0].([]*ApiClientGrant)[vs[1].(int)]
	}).(ApiClientGrantOutput)
}

type ApiClientGrantMapOutput struct{ *pulumi.OutputState }

func (ApiClientGrantMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ApiClientGrant)(nil)).Elem()
}

func (o ApiClientGrantMapOutput) ToApiClientGrantMapOutput() ApiClientGrantMapOutput {
	return o
}

func (o ApiClientGrantMapOutput) ToApiClientGrantMapOutputWithContext(ctx context.Context) ApiClientGrantMapOutput {
	return o
}

func (o ApiClientGrantMapOutput) MapIndex(k pulumi.StringInput) ApiClientGrantOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ApiClientGrant {
		return vs[0].(map[string]*ApiClientGrant)[vs[1].(string)]
	}).(ApiClientGrantOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ApiClientGrantInput)(nil)).Elem(), &ApiClientGrant{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApiClientGrantArrayInput)(nil)).Elem(), ApiClientGrantArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ApiClientGrantMapInput)(nil)).Elem(), ApiClientGrantMap{})
	pulumi.RegisterOutputType(ApiClientGrantOutput{})
	pulumi.RegisterOutputType(ApiClientGrantArrayOutput{})
	pulumi.RegisterOutputType(ApiClientGrantMapOutput{})
}
