// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumipocketid

import (
	"context"
	"reflect"

	"github.com/axnic/pulumi-pocket-id/sdk/go/pulumi-pocket-id/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Reads the OpenID Connect discovery document of the Pocket-ID instance: issuer, endpoints, JWKS URI and supported capabilities. Use it to configure applications that consume the instance as an OIDC provider.
func GetOpenIdConfiguration(ctx *pulumi.Context, args *GetOpenIdConfigurationArgs, opts ...pulumi.InvokeOption) (*GetOpenIdConfigurationResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetOpenIdConfigurationResult
	err := ctx.Invoke("pocket-id:index:getOpenIdConfiguration", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type GetOpenIdConfigurationArgs struct {
}

type GetOpenIdConfigurationResult struct {
	// The OAuth 2.0 authorization endpoint.
	AuthorizationEndpoint string `pulumi:"authorizationEndpoint"`
	// The supported claims.
	ClaimsSupported []string `pulumi:"claimsSupported"`
	// The supported PKCE code challenge methods.
	CodeChallengeMethodsSupported []string `pulumi:"codeChallengeMethodsSupported"`
	// The device authorization endpoint, empty if the instance does not advertise one.
	DeviceAuthorizationEndpoint string `pulumi:"deviceAuthorizationEndpoint"`
	// The RP-initiated logout endpoint, empty if the instance does not advertise one.
	EndSessionEndpoint string `pulumi:"endSessionEndpoint"`
	// The supported OAuth 2.0 grant types.
	GrantTypesSupported []string `pulumi:"grantTypesSupported"`
	// The supported ID token signing algorithms.
	IdTokenSigningAlgValuesSupported []string `pulumi:"idTokenSigningAlgValuesSupported"`
	// The token introspection endpoint, empty if the instance does not advertise one.
	IntrospectionEndpoint string `pulumi:"introspectionEndpoint"`
	// The issuer URL, i.e. the base URL of the instance.
	Issuer string `pulumi:"issuer"`
	// The URL of the JSON Web Key Set used to verify issued tokens.
	JwksUri string `pulumi:"jwksUri"`
	// The supported response types.
	ResponseTypesSupported []string `pulumi:"responseTypesSupported"`
	// The supported scopes.
	ScopesSupported []string `pulumi:"scopesSupported"`
	// The supported subject identifier types.
	SubjectTypesSupported []string `pulumi:"subjectTypesSupported"`
	// The OAuth 2.0 token endpoint.
	TokenEndpoint string `pulumi:"tokenEndpoint"`
	// The supported client authentication methods at the token endpoint.
	TokenEndpointAuthMethodsSupported []string `pulumi:"tokenEndpointAuthMethodsSupported"`
	// The OIDC userinfo endpoint.
	UserinfoEndpoint string `pulumi:"userinfoEndpoint"`
}

func GetOpenIdConfigurationOutput(ctx *pulumi.Context, args GetOpenIdConfigurationOutputArgs, opts ...pulumi.InvokeOption) GetOpenIdConfigurationResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("pocket-id:index:getOpenIdConfiguration", args, GetOpenIdConfigurationResultOutput{}, options).(GetOpenIdConfigurationResultOutput)
}

type GetOpenIdConfigurationOutputArgs struct {
}

func (GetOpenIdConfigurationOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOpenIdConfigurationArgs)(nil)).Elem()
}

type GetOpenIdConfigurationResultOutput struct{ *pulumi.OutputState }

func (GetOpenIdConfigurationResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetOpenIdConfigurationResult)(nil)).Elem()
}

func (o GetOpenIdConfigurationResultOutput) ToGetOpenIdConfigurationResultOutput() GetOpenIdConfigurationResultOutput {
	return o
}

func (o GetOpenIdConfigurationResultOutput) ToGetOpenIdConfigurationResultOutputWithContext(ctx context.Context) GetOpenIdConfigurationResultOutput {
	return o
}

// The OAuth 2.0 authorization endpoint.
func (o GetOpenIdConfigurationResultOutput) AuthorizationEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) string { return v.AuthorizationEndpoint }).(pulumi.StringOutput)
}

// The supported claims.
func (o GetOpenIdConfigurationResultOutput) ClaimsSupported() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) []string { return v.ClaimsSupported }).(pulumi.StringArrayOutput)
}

// The supported PKCE code challenge methods.
func (o GetOpenIdConfigurationResultOutput) CodeChallengeMethodsSupported() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) []string { return v.CodeChallengeMethodsSupported }).(pulumi.StringArrayOutput)
}

// The device authorization endpoint, empty if the instance does not advertise one.
func (o GetOpenIdConfigurationResultOutput) DeviceAuthorizationEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) string { return v.DeviceAuthorizationEndpoint }).(pulumi.StringOutput)
}

// The RP-initiated logout endpoint, empty if the instance does not advertise one.
func (o GetOpenIdConfigurationResultOutput) EndSessionEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) string { return v.EndSessionEndpoint }).(pulumi.StringOutput)
}

// The supported OAuth 2.0 grant types.
func (o GetOpenIdConfigurationResultOutput) GrantTypesSupported() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) []string { return v.GrantTypesSupported }).(pulumi.StringArrayOutput)
}

// The supported ID token signing algorithms.
func (o GetOpenIdConfigurationResultOutput) IdTokenSigningAlgValuesSupported() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) []string { return v.IdTokenSigningAlgValuesSupported }).(pulumi.StringArrayOutput)
}

// The token introspection endpoint, empty if the instance does not advertise one.
func (o GetOpenIdConfigurationResultOutput) IntrospectionEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) string { return v.IntrospectionEndpoint }).(pulumi.StringOutput)
}

// The issuer URL, i.e. the base URL of the instance.
func (o GetOpenIdConfigurationResultOutput) Issuer() pulumi.StringOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) string { return v.Issuer }).(pulumi.StringOutput)
}

// The URL of the JSON Web Key Set used to verify issued tokens.
func (o GetOpenIdConfigurationResultOutput) JwksUri() pulumi.StringOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) string { return v.JwksUri }).(pulumi.StringOutput)
}

// The supported response types.
func (o GetOpenIdConfigurationResultOutput) ResponseTypesSupported() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) []string { return v.ResponseTypesSupported }).(pulumi.StringArrayOutput)
}

// The supported scopes.
func (o GetOpenIdConfigurationResultOutput) ScopesSupported() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) []string { return v.ScopesSupported }).(pulumi.StringArrayOutput)
}

// The supported subject identifier types.
func (o GetOpenIdConfigurationResultOutput) SubjectTypesSupported() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) []string { return v.SubjectTypesSupported }).(pulumi.StringArrayOutput)
}

// The OAuth 2.0 token endpoint.
func (o GetOpenIdConfigurationResultOutput) TokenEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) string { return v.TokenEndpoint }).(pulumi.StringOutput)
}

// The supported client authentication methods at the token endpoint.
func (o GetOpenIdConfigurationResultOutput) TokenEndpointAuthMethodsSupported() pulumi.StringArrayOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) []string { return v.TokenEndpointAuthMethodsSupported }).(pulumi.StringArrayOutput)
}

// The OIDC userinfo endpoint.
func (o GetOpenIdConfigurationResultOutput) UserinfoEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v GetOpenIdConfigurationResult) string { return v.UserinfoEndpoint }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetOpenIdConfigurationResultOutput{})
}
