// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumipocketid

import (
	"context"
	"reflect"

	"github.com/axnic/pulumi-pocket-id/sdk/go/pulumi-pocket-id/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Looks up a Pocket-ID user group by ID or by exact name.
func LookupUserGroup(ctx *pulumi.Context, args *LookupUserGroupArgs, opts ...pulumi.InvokeOption) (*LookupUserGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupUserGroupResult
	err := ctx.Invoke("pocket-id:index:getUserGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupUserGroupArgs struct {
	// The exact name of the group. Exactly one of userGroupId or name must be set.
	Name *string `pulumi:"name"`
	// The ID of the group. Exactly one of userGroupId or name must be set.
	UserGroupId *string `pulumi:"userGroupId"`
}

type LookupUserGroupResult struct {
	// The custom claims of the group.
	CustomClaims map[string]string `pulumi:"customClaims"`
	// The human-readable name of the group.
	FriendlyName string `pulumi:"friendlyName"`
	// The name of the group.
	Name string `pulumi:"name"`
	// The ID of the group.
	UserGroupId string `pulumi:"userGroupId"`
	// The IDs of the members of the group.
	UserIds []string `pulumi:"userIds"`
}

func LookupUserGroupOutput(ctx *pulumi.Context, args LookupUserGroupOutputArgs, opts ...pulumi.InvokeOption) LookupUserGroupResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("pocket-id:index:getUserGroup", args, LookupUserGroupResultOutput{}, options).(LookupUserGroupResultOutput)
}

type LookupUserGroupOutputArgs struct {
	// The exact name of the group. Exactly one of userGroupId or name must be set.
	Name pulumi.StringPtrInput `pulumi:"name"`
	// The ID of the group. Exactly one of userGroupId or name must be set.
	UserGroupId pulumi.StringPtrInput `pulumi:"userGroupId"`
}

func (LookupUserGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserGroupArgs)(nil)).Elem()
}

type LookupUserGroupResultOutput struct{ *pulumi.OutputState }

func (LookupUserGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserGroupResult)(nil)).Elem()
}

func (o LookupUserGroupResultOutput) ToLookupUserGroupResultOutput() LookupUserGroupResultOutput {
	return o
}

func (o LookupUserGroupResultOutput) ToLookupUserGroupResultOutputWithContext(ctx context.Context) LookupUserGroupResultOutput {
	return o
}

// The custom claims of the group.
func (o LookupUserGroupResultOutput) CustomClaims() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupUserGroupResult) map[string]string { return v.CustomClaims }).(pulumi.StringMapOutput)
}

// The human-readable name of the group.
func (o LookupUserGroupResultOutput) FriendlyName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserGroupResult) string { return v.FriendlyName }).(pulumi.StringOutput)
}

// The name of the group.
func (o LookupUserGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

// The ID of the group.
func (o LookupUserGroupResultOutput) UserGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserGroupResult) string { return v.UserGroupId }).(pulumi.StringOutput)
}

// The IDs of the members of the group.
func (o LookupUserGroupResultOutput) UserIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupUserGroupResult) []string { return v.UserIds }).(pulumi.StringArrayOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupUserGroupResultOutput{})
}
