// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumipocketid

import (
	"context"
	"reflect"

	"github.com/axnic/pulumi-pocket-id/sdk/go/pulumi-pocket-id/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Looks up a Pocket-ID user by ID or by exact username.
func LookupUser(ctx *pulumi.Context, args *LookupUserArgs, opts ...pulumi.InvokeOption) (*LookupUserResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupUserResult
	err := ctx.Invoke("pocket-id:index:getUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

type LookupUserArgs struct {
	// The ID of the user. Exactly one of userId or username must be set.
	UserId *string `pulumi:"userId"`
	// The exact username of the user. Exactly one of userId or username must be set.
	Username *string `pulumi:"username"`
}

type LookupUserResult struct {
	// The custom claims of the user.
	CustomClaims map[string]string `pulumi:"customClaims"`
	// Whether the user is disabled.
	Disabled bool `pulumi:"disabled"`
	// The display name of the user.
	DisplayName string `pulumi:"displayName"`
	// The email address of the user, empty if unset.
	Email string `pulumi:"email"`
	// Whether the email address is verified.
	EmailVerified bool `pulumi:"emailVerified"`
	// The first name of the user.
	FirstName string `pulumi:"firstName"`
	// Whether the user is an administrator.
	IsAdmin bool `pulumi:"isAdmin"`
	// The last name of the user, empty if unset.
	LastName string `pulumi:"lastName"`
	// The locale of the user, empty if unset.
	Locale string `pulumi:"locale"`
	// The IDs of the groups the user belongs to.
	UserGroupIds []string `pulumi:"userGroupIds"`
	// The ID of the user.
	UserId string `pulumi:"userId"`
	// The username of the user.
	Username string `pulumi:"username"`
}

func LookupUserOutput(ctx *pulumi.Context, args LookupUserOutputArgs, opts ...pulumi.InvokeOption) LookupUserResultOutput {
	options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
	return ctx.InvokeOutput("pocket-id:index:getUser", args, LookupUserResultOutput{}, options).(LookupUserResultOutput)
}

type LookupUserOutputArgs struct {
	// The ID of the user. Exactly one of userId or username must be set.
	UserId pulumi.StringPtrInput `pulumi:"userId"`
	// The exact username of the user. Exactly one of userId or username must be set.
	Username pulumi.StringPtrInput `pulumi:"username"`
}

func (LookupUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserArgs)(nil)).Elem()
}

type LookupUserResultOutput struct{ *pulumi.OutputState }

func (LookupUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupUserResult)(nil)).Elem()
}

func (o LookupUserResultOutput) ToLookupUserResultOutput() LookupUserResultOutput {
	return o
}

func (o LookupUserResultOutput) ToLookupUserResultOutputWithContext(ctx context.Context) LookupUserResultOutput {
	return o
}

// The custom claims of the user.
func (o LookupUserResultOutput) CustomClaims() pulumi.StringMapOutput {
	return o.ApplyT(func(v LookupUserResult) map[string]string { return v.CustomClaims }).(pulumi.StringMapOutput)
}

// Whether the user is disabled.
func (o LookupUserResultOutput) Disabled() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupUserResult) bool { return v.Disabled }).(pulumi.BoolOutput)
}

// The display name of the user.
func (o LookupUserResultOutput) DisplayName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.DisplayName }).(pulumi.StringOutput)
}

// The email address of the user, empty if unset.
func (o LookupUserResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Email }).(pulumi.StringOutput)
}

// Whether the email address is verified.
func (o LookupUserResultOutput) EmailVerified() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupUserResult) bool { return v.EmailVerified }).(pulumi.BoolOutput)
}

// The first name of the user.
func (o LookupUserResultOutput) FirstName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.FirstName }).(pulumi.StringOutput)
}

// Whether the user is an administrator.
func (o LookupUserResultOutput) IsAdmin() pulumi.BoolOutput {
	return o.ApplyT(func(v LookupUserResult) bool { return v.IsAdmin }).(pulumi.BoolOutput)
}

// The last name of the user, empty if unset.
func (o LookupUserResultOutput) LastName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.LastName }).(pulumi.StringOutput)
}

// The locale of the user, empty if unset.
func (o LookupUserResultOutput) Locale() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Locale }).(pulumi.StringOutput)
}

// The IDs of the groups the user belongs to.
func (o LookupUserResultOutput) UserGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupUserResult) []string { return v.UserGroupIds }).(pulumi.StringArrayOutput)
}

// The ID of the user.
func (o LookupUserResultOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.UserId }).(pulumi.StringOutput)
}

// The username of the user.
func (o LookupUserResultOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v LookupUserResult) string { return v.Username }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupUserResultOutput{})
}
