// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumipocketid

import (
	"context"
	"reflect"

	"errors"
	"github.com/axnic/pulumi-pocket-id/sdk/go/pulumi-pocket-id/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A client secret of an OIDC client. Several secrets can coexist, which allows rotating a secret without downtime: create the new one, then remove the old one. Every property is immutable: changing one replaces the secret.
type OidcClientSecret struct {
	pulumi.CustomResourceState

	// The ID of the OIDC client the secret belongs to. Changing it replaces the secret.
	ClientId pulumi.StringOutput `pulumi:"clientId"`
	// The creation date of the secret.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The expiration date of the secret (RFC 3339). Never expires when unset. Changing it replaces the secret.
	ExpiresAt pulumi.StringPtrOutput `pulumi:"expiresAt"`
	// The first characters of the secret, as reported by Pocket-ID.
	Prefix pulumi.StringOutput `pulumi:"prefix"`
	// The plain-text secret. Only returned by Pocket-ID at creation, so it is kept from the state and is empty after an import.
	Secret pulumi.StringOutput `pulumi:"secret"`
	// The ID of the secret.
	SecretId pulumi.StringOutput `pulumi:"secretId"`
}

// NewOidcClientSecret registers a new resource with the given unique name, arguments, and options.
func NewOidcClientSecret(ctx *pulumi.Context,
	name string, args *OidcClientSecretArgs, opts ...pulumi.ResourceOption) (*OidcClientSecret, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClientId == nil {
		return nil, errors.New("invalid value for required argument 'ClientId'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"secret",
	})
	opts = append(opts, secrets)
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"clientId",
		"expiresAt",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource OidcClientSecret
	err := ctx.RegisterResource("pocket-id:index:OidcClientSecret", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOidcClientSecret gets an existing OidcClientSecret resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOidcClientSecret(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OidcClientSecretState, opts ...pulumi.ResourceOption) (*OidcClientSecret, error) {
	var resource OidcClientSecret
	err := ctx.ReadResource("pocket-id:index:OidcClientSecret", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OidcClientSecret resources.
type oidcClientSecretState struct {
}

type OidcClientSecretState struct {
}

func (OidcClientSecretState) ElementType() reflect.Type {
	return reflect.TypeOf((*oidcClientSecretState)(nil)).Elem()
}

type oidcClientSecretArgs struct {
	// The ID of the OIDC client the secret belongs to. Changing it replaces the secret.
	ClientId string `pulumi:"clientId"`
	// The expiration date of the secret (RFC 3339). Never expires when unset. Changing it replaces the secret.
	ExpiresAt *string `pulumi:"expiresAt"`
}

// The set of arguments for constructing a OidcClientSecret resource.
type OidcClientSecretArgs struct {
	// The ID of the OIDC client the secret belongs to. Changing it replaces the secret.
	ClientId pulumi.StringInput
	// The expiration date of the secret (RFC 3339). Never expires when unset. Changing it replaces the secret.
	ExpiresAt pulumi.StringPtrInput
}

func (OidcClientSecretArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*oidcClientSecretArgs)(nil)).Elem()
}

type OidcClientSecretInput interface {
	pulumi.Input

	ToOidcClientSecretOutput() OidcClientSecretOutput
	ToOidcClientSecretOutputWithContext(ctx context.Context) OidcClientSecretOutput
}

func (*OidcClientSecret) ElementType() reflect.Type {
	return reflect.TypeOf((**OidcClientSecret)(nil)).Elem()
}

func (i *OidcClientSecret) ToOidcClientSecretOutput() OidcClientSecretOutput {
	return i.ToOidcClientSecretOutputWithContext(context.Background())
}

func (i *OidcClientSecret) ToOidcClientSecretOutputWithContext(ctx context.Context) OidcClientSecretOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OidcClientSecretOutput)
}

// OidcClientSecretArrayInput is an input type that accepts OidcClientSecretArray and OidcClientSecretArrayOutput values.
// You can construct a concrete instance of `OidcClientSecretArrayInput` via:
//
//	OidcClientSecretArray{ OidcClientSecretArgs{...} }
type OidcClientSecretArrayInput interface {
	pulumi.Input

	ToOidcClientSecretArrayOutput() OidcClientSecretArrayOutput
	ToOidcClientSecretArrayOutputWithContext(context.Context) OidcClientSecretArrayOutput
}

type OidcClientSecretArray []OidcClientSecretInput

func (OidcClientSecretArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OidcClientSecret)(nil)).Elem()
}

func (i OidcClientSecretArray) ToOidcClientSecretArrayOutput() OidcClientSecretArrayOutput {
	return i.ToOidcClientSecretArrayOutputWithContext(context.Background())
}

func (i OidcClientSecretArray) ToOidcClientSecretArrayOutputWithContext(ctx context.Context) OidcClientSecretArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OidcClientSecretArrayOutput)
}

// OidcClientSecretMapInput is an input type that accepts OidcClientSecretMap and OidcClientSecretMapOutput values.
// You can construct a concrete instance of `OidcClientSecretMapInput` via:
//
//	OidcClientSecretMap{ "key": OidcClientSecretArgs{...} }
type OidcClientSecretMapInput interface {
	pulumi.Input

	ToOidcClientSecretMapOutput() OidcClientSecretMapOutput
	ToOidcClientSecretMapOutputWithContext(context.Context) OidcClientSecretMapOutput
}

type OidcClientSecretMap map[string]OidcClientSecretInput

func (OidcClientSecretMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OidcClientSecret)(nil)).Elem()
}

func (i OidcClientSecretMap) ToOidcClientSecretMapOutput() OidcClientSecretMapOutput {
	return i.ToOidcClientSecretMapOutputWithContext(context.Background())
}

func (i OidcClientSecretMap) ToOidcClientSecretMapOutputWithContext(ctx context.Context) OidcClientSecretMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OidcClientSecretMapOutput)
}

type OidcClientSecretOutput struct{ *pulumi.OutputState }

func (OidcClientSecretOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OidcClientSecret)(nil)).Elem()
}

func (o OidcClientSecretOutput) ToOidcClientSecretOutput() OidcClientSecretOutput {
	return o
}

func (o OidcClientSecretOutput) ToOidcClientSecretOutputWithContext(ctx context.Context) OidcClientSecretOutput {
	return o
}

// The ID of the OIDC client the secret belongs to. Changing it replaces the secret.
func (o OidcClientSecretOutput) ClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcClientSecret) pulumi.StringOutput { return v.ClientId }).(pulumi.StringOutput)
}

// The creation date of the secret.
func (o OidcClientSecretOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcClientSecret) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The expiration date of the secret (RFC 3339). Never expires when unset. Changing it replaces the secret.
func (o OidcClientSecretOutput) ExpiresAt() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *OidcClientSecret) pulumi.StringPtrOutput { return v.ExpiresAt }).(pulumi.StringPtrOutput)
}

// The first characters of the secret, as reported by Pocket-ID.
func (o OidcClientSecretOutput) Prefix() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcClientSecret) pulumi.StringOutput { return v.Prefix }).(pulumi.StringOutput)
}

// The plain-text secret. Only returned by Pocket-ID at creation, so it is kept from the state and is empty after an import.
func (o OidcClientSecretOutput) Secret() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcClientSecret) pulumi.StringOutput { return v.Secret }).(pulumi.StringOutput)
}

// The ID of the secret.
func (o OidcClientSecretOutput) SecretId() pulumi.StringOutput {
	return o.ApplyT(func(v *OidcClientSecret) pulumi.StringOutput { return v.SecretId }).(pulumi.StringOutput)
}

type OidcClientSecretArrayOutput struct{ *pulumi.OutputState }

func (OidcClientSecretArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OidcClientSecret)(nil)).Elem()
}

func (o OidcClientSecretArrayOutput) ToOidcClientSecretArrayOutput() OidcClientSecretArrayOutput {
	return o
}

func (o OidcClientSecretArrayOutput) ToOidcClientSecretArrayOutputWithContext(ctx context.Context) OidcClientSecretArrayOutput {
	return o
}

func (o OidcClientSecretArrayOutput) Index(i pulumi.IntInput) OidcClientSecretOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *OidcClientSecret {
		return vs[0].([]*OidcClientSecret)[vs[1].(int)]
	}).(OidcClientSecretOutput)
}

type OidcClientSecretMapOutput struct{ *pulumi.OutputState }

func (OidcClientSecretMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OidcClientSecret)(nil)).Elem()
}

func (o OidcClientSecretMapOutput) ToOidcClientSecretMapOutput() OidcClientSecretMapOutput {
	return o
}

func (o OidcClientSecretMapOutput) ToOidcClientSecretMapOutputWithContext(ctx context.Context) OidcClientSecretMapOutput {
	return o
}

func (o OidcClientSecretMapOutput) MapIndex(k pulumi.StringInput) OidcClientSecretOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *OidcClientSecret {
		return vs[0].(map[string]*OidcClientSecret)[vs[1].(string)]
	}).(OidcClientSecretOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OidcClientSecretInput)(nil)).Elem(), &OidcClientSecret{})
	pulumi.RegisterInputType(reflect.TypeOf((*OidcClientSecretArrayInput)(nil)).Elem(), OidcClientSecretArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*OidcClientSecretMapInput)(nil)).Elem(), OidcClientSecretMap{})
	pulumi.RegisterOutputType(OidcClientSecretOutput{})
	pulumi.RegisterOutputType(OidcClientSecretArrayOutput{})
	pulumi.RegisterOutputType(OidcClientSecretMapOutput{})
}
