// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumipocketid

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

type ApplicationImageType string

const (
	// The light mode application logo.
	ApplicationImageTypeLogo = ApplicationImageType("logo")
	// The dark mode application logo.
	ApplicationImageTypeDarkLogo = ApplicationImageType("darkLogo")
	// The favicon. It cannot be deleted.
	ApplicationImageTypeFavicon = ApplicationImageType("favicon")
	// The login page background.
	ApplicationImageTypeBackground = ApplicationImageType("background")
	// The image used in e-mails. It cannot be deleted.
	ApplicationImageTypeEmail = ApplicationImageType("email")
	// The default profile picture of users.
	ApplicationImageTypeDefaultProfilePicture = ApplicationImageType("defaultProfilePicture")
)

func (ApplicationImageType) ElementType() reflect.Type {
	return reflect.TypeOf((*ApplicationImageType)(nil)).Elem()
}

func (e ApplicationImageType) ToApplicationImageTypeOutput() ApplicationImageTypeOutput {
	return pulumi.ToOutput(e).(ApplicationImageTypeOutput)
}

func (e ApplicationImageType) ToApplicationImageTypeOutputWithContext(ctx context.Context) ApplicationImageTypeOutput {
	return pulumi.ToOutputWithContext(ctx, e).(ApplicationImageTypeOutput)
}

func (e ApplicationImageType) ToApplicationImageTypePtrOutput() ApplicationImageTypePtrOutput {
	return e.ToApplicationImageTypePtrOutputWithContext(context.Background())
}

func (e ApplicationImageType) ToApplicationImageTypePtrOutputWithContext(ctx context.Context) ApplicationImageTypePtrOutput {
	return ApplicationImageType(e).ToApplicationImageTypeOutputWithContext(ctx).ToApplicationImageTypePtrOutputWithContext(ctx)
}

func (e ApplicationImageType) ToStringOutput() pulumi.StringOutput {
	return pulumi.ToOutput(pulumi.String(e)).(pulumi.StringOutput)
}

func (e ApplicationImageType) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return pulumi.ToOutputWithContext(ctx, pulumi.String(e)).(pulumi.StringOutput)
}

func (e ApplicationImageType) ToStringPtrOutput() pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringPtrOutputWithContext(context.Background())
}

func (e ApplicationImageType) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return pulumi.String(e).ToStringOutputWithContext(ctx).ToStringPtrOutputWithContext(ctx)
}

type ApplicationImageTypeOutput struct{ *pulumi.OutputState }

func (ApplicationImageTypeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*ApplicationImageType)(nil)).Elem()
}

func (o ApplicationImageTypeOutput) ToApplicationImageTypeOutput() ApplicationImageTypeOutput {
	return o
}

func (o ApplicationImageTypeOutput) ToApplicationImageTypeOutputWithContext(ctx context.Context) ApplicationImageTypeOutput {
	return o
}

func (o ApplicationImageTypeOutput) ToApplicationImageTypePtrOutput() ApplicationImageTypePtrOutput {
	return o.ToApplicationImageTypePtrOutputWithContext(context.Background())
}

func (o ApplicationImageTypeOutput) ToApplicationImageTypePtrOutputWithContext(ctx context.Context) ApplicationImageTypePtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, v ApplicationImageType) *ApplicationImageType {
		return &v
	}).(ApplicationImageTypePtrOutput)
}

func (o ApplicationImageTypeOutput) ToStringOutput() pulumi.StringOutput {
	return o.ToStringOutputWithContext(context.Background())
}

func (o ApplicationImageTypeOutput) ToStringOutputWithContext(ctx context.Context) pulumi.StringOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ApplicationImageType) string {
		return string(e)
	}).(pulumi.StringOutput)
}

func (o ApplicationImageTypeOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ApplicationImageTypeOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e ApplicationImageType) *string {
		v := string(e)
		return &v
	}).(pulumi.StringPtrOutput)
}

type ApplicationImageTypePtrOutput struct{ *pulumi.OutputState }

func (ApplicationImageTypePtrOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ApplicationImageType)(nil)).Elem()
}

func (o ApplicationImageTypePtrOutput) ToApplicationImageTypePtrOutput() ApplicationImageTypePtrOutput {
	return o
}

func (o ApplicationImageTypePtrOutput) ToApplicationImageTypePtrOutputWithContext(ctx context.Context) ApplicationImageTypePtrOutput {
	return o
}

func (o ApplicationImageTypePtrOutput) Elem() ApplicationImageTypeOutput {
	return o.ApplyT(func(v *ApplicationImageType) ApplicationImageType {
		if v != nil {
			return *v
		}
		var ret ApplicationImageType
		return ret
	}).(ApplicationImageTypeOutput)
}

func (o ApplicationImageTypePtrOutput) ToStringPtrOutput() pulumi.StringPtrOutput {
	return o.ToStringPtrOutputWithContext(context.Background())
}

func (o ApplicationImageTypePtrOutput) ToStringPtrOutputWithContext(ctx context.Context) pulumi.StringPtrOutput {
	return o.ApplyTWithContext(ctx, func(_ context.Context, e *ApplicationImageType) *string {
		if e == nil {
			return nil
		}
		v := string(*e)
		return &v
	}).(pulumi.StringPtrOutput)
}

// ApplicationImageTypeInput is an input type that accepts values of the ApplicationImageType enum
// A concrete instance of `ApplicationImageTypeInput` can be one of the following:
//
//	ApplicationImageTypeLogo
//	ApplicationImageTypeDarkLogo
//	ApplicationImageTypeFavicon
//	ApplicationImageTypeBackground
//	ApplicationImageTypeEmail
//	ApplicationImageTypeDefaultProfilePicture
type ApplicationImageTypeInput interface {
	pulumi.Input

	ToApplicationImageTypeOutput() ApplicationImageTypeOutput
	ToApplicationImageTypeOutputWithContext(context.Context) ApplicationImageTypeOutput
}

var applicationImageTypePtrType = reflect.TypeOf((**ApplicationImageType)(nil)).Elem()

type ApplicationImageTypePtrInput interface {
	pulumi.Input

	ToApplicationImageTypePtrOutput() ApplicationImageTypePtrOutput
	ToApplicationImageTypePtrOutputWithContext(context.Context) ApplicationImageTypePtrOutput
}

type applicationImageTypePtr string

func ApplicationImageTypePtr(v string) ApplicationImageTypePtrInput {
	return (*applicationImageTypePtr)(&v)
}

func (*applicationImageTypePtr) ElementType() reflect.Type {
	return applicationImageTypePtrType
}

func (in *applicationImageTypePtr) ToApplicationImageTypePtrOutput() ApplicationImageTypePtrOutput {
	return pulumi.ToOutput(in).(ApplicationImageTypePtrOutput)
}

func (in *applicationImageTypePtr) ToApplicationImageTypePtrOutputWithContext(ctx context.Context) ApplicationImageTypePtrOutput {
	return pulumi.ToOutputWithContext(ctx, in).(ApplicationImageTypePtrOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationImageTypeInput)(nil)).Elem(), ApplicationImageType("logo"))
	pulumi.RegisterInputType(reflect.TypeOf((*ApplicationImageTypePtrInput)(nil)).Elem(), ApplicationImageType("logo"))
	pulumi.RegisterOutputType(ApplicationImageTypeOutput{})
	pulumi.RegisterOutputType(ApplicationImageTypePtrOutput{})
}
