// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumipocketid

import (
	"context"
	"reflect"

	"errors"
	"github.com/axnic/pulumi-pocket-id/sdk/go/pulumi-pocket-id/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A SCIM service provider attached to an OIDC client. To import it, use the ID <oidcClientId>/<serviceProviderId>.
type ScimServiceProvider struct {
	pulumi.CustomResourceState

	// The creation date of the service provider.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The base URL of the SCIM endpoint.
	Endpoint pulumi.StringOutput `pulumi:"endpoint"`
	// The date of the last synchronization, empty if it never ran.
	LastSyncedAt pulumi.StringOutput `pulumi:"lastSyncedAt"`
	// The ID of the OIDC client the service provider belongs to. Changing it replaces the resource.
	OidcClientId pulumi.StringOutput `pulumi:"oidcClientId"`
	// The bearer token used to authenticate against the SCIM endpoint. Never read back from the API: it is kept from the state and unset after an import.
	Token pulumi.StringPtrOutput `pulumi:"token"`
}

// NewScimServiceProvider registers a new resource with the given unique name, arguments, and options.
func NewScimServiceProvider(ctx *pulumi.Context,
	name string, args *ScimServiceProviderArgs, opts ...pulumi.ResourceOption) (*ScimServiceProvider, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Endpoint == nil {
		return nil, errors.New("invalid value for required argument 'Endpoint'")
	}
	if args.OidcClientId == nil {
		return nil, errors.New("invalid value for required argument 'OidcClientId'")
	}
	if args.Token != nil {
		args.Token = pulumi.ToSecret(args.Token).(pulumi.StringPtrInput)
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
	})
	opts = append(opts, secrets)
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"oidcClientId",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ScimServiceProvider
	err := ctx.RegisterResource("pocket-id:index:ScimServiceProvider", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetScimServiceProvider gets an existing ScimServiceProvider resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetScimServiceProvider(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ScimServiceProviderState, opts ...pulumi.ResourceOption) (*ScimServiceProvider, error) {
	var resource ScimServiceProvider
	err := ctx.ReadResource("pocket-id:index:ScimServiceProvider", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ScimServiceProvider resources.
type scimServiceProviderState struct {
}

type ScimServiceProviderState struct {
}

func (ScimServiceProviderState) ElementType() reflect.Type {
	return reflect.TypeOf((*scimServiceProviderState)(nil)).Elem()
}

type scimServiceProviderArgs struct {
	// The base URL of the SCIM endpoint.
	Endpoint string `pulumi:"endpoint"`
	// The ID of the OIDC client the service provider belongs to. Changing it replaces the resource.
	OidcClientId string `pulumi:"oidcClientId"`
	// The bearer token used to authenticate against the SCIM endpoint. Never read back from the API: it is kept from the state and unset after an import.
	Token *string `pulumi:"token"`
}

// The set of arguments for constructing a ScimServiceProvider resource.
type ScimServiceProviderArgs struct {
	// The base URL of the SCIM endpoint.
	Endpoint pulumi.StringInput
	// The ID of the OIDC client the service provider belongs to. Changing it replaces the resource.
	OidcClientId pulumi.StringInput
	// The bearer token used to authenticate against the SCIM endpoint. Never read back from the API: it is kept from the state and unset after an import.
	Token pulumi.StringPtrInput
}

func (ScimServiceProviderArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*scimServiceProviderArgs)(nil)).Elem()
}

type ScimServiceProviderInput interface {
	pulumi.Input

	ToScimServiceProviderOutput() ScimServiceProviderOutput
	ToScimServiceProviderOutputWithContext(ctx context.Context) ScimServiceProviderOutput
}

func (*ScimServiceProvider) ElementType() reflect.Type {
	return reflect.TypeOf((**ScimServiceProvider)(nil)).Elem()
}

func (i *ScimServiceProvider) ToScimServiceProviderOutput() ScimServiceProviderOutput {
	return i.ToScimServiceProviderOutputWithContext(context.Background())
}

func (i *ScimServiceProvider) ToScimServiceProviderOutputWithContext(ctx context.Context) ScimServiceProviderOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScimServiceProviderOutput)
}

// ScimServiceProviderArrayInput is an input type that accepts ScimServiceProviderArray and ScimServiceProviderArrayOutput values.
// You can construct a concrete instance of `ScimServiceProviderArrayInput` via:
//
//	ScimServiceProviderArray{ ScimServiceProviderArgs{...} }
type ScimServiceProviderArrayInput interface {
	pulumi.Input

	ToScimServiceProviderArrayOutput() ScimServiceProviderArrayOutput
	ToScimServiceProviderArrayOutputWithContext(context.Context) ScimServiceProviderArrayOutput
}

type ScimServiceProviderArray []ScimServiceProviderInput

func (ScimServiceProviderArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ScimServiceProvider)(nil)).Elem()
}

func (i ScimServiceProviderArray) ToScimServiceProviderArrayOutput() ScimServiceProviderArrayOutput {
	return i.ToScimServiceProviderArrayOutputWithContext(context.Background())
}

func (i ScimServiceProviderArray) ToScimServiceProviderArrayOutputWithContext(ctx context.Context) ScimServiceProviderArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScimServiceProviderArrayOutput)
}

// ScimServiceProviderMapInput is an input type that accepts ScimServiceProviderMap and ScimServiceProviderMapOutput values.
// You can construct a concrete instance of `ScimServiceProviderMapInput` via:
//
//	ScimServiceProviderMap{ "key": ScimServiceProviderArgs{...} }
type ScimServiceProviderMapInput interface {
	pulumi.Input

	ToScimServiceProviderMapOutput() ScimServiceProviderMapOutput
	ToScimServiceProviderMapOutputWithContext(context.Context) ScimServiceProviderMapOutput
}

type ScimServiceProviderMap map[string]ScimServiceProviderInput

func (ScimServiceProviderMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ScimServiceProvider)(nil)).Elem()
}

func (i ScimServiceProviderMap) ToScimServiceProviderMapOutput() ScimServiceProviderMapOutput {
	return i.ToScimServiceProviderMapOutputWithContext(context.Background())
}

func (i ScimServiceProviderMap) ToScimServiceProviderMapOutputWithContext(ctx context.Context) ScimServiceProviderMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ScimServiceProviderMapOutput)
}

type ScimServiceProviderOutput struct{ *pulumi.OutputState }

func (ScimServiceProviderOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ScimServiceProvider)(nil)).Elem()
}

func (o ScimServiceProviderOutput) ToScimServiceProviderOutput() ScimServiceProviderOutput {
	return o
}

func (o ScimServiceProviderOutput) ToScimServiceProviderOutputWithContext(ctx context.Context) ScimServiceProviderOutput {
	return o
}

// The creation date of the service provider.
func (o ScimServiceProviderOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ScimServiceProvider) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The base URL of the SCIM endpoint.
func (o ScimServiceProviderOutput) Endpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *ScimServiceProvider) pulumi.StringOutput { return v.Endpoint }).(pulumi.StringOutput)
}

// The date of the last synchronization, empty if it never ran.
func (o ScimServiceProviderOutput) LastSyncedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ScimServiceProvider) pulumi.StringOutput { return v.LastSyncedAt }).(pulumi.StringOutput)
}

// The ID of the OIDC client the service provider belongs to. Changing it replaces the resource.
func (o ScimServiceProviderOutput) OidcClientId() pulumi.StringOutput {
	return o.ApplyT(func(v *ScimServiceProvider) pulumi.StringOutput { return v.OidcClientId }).(pulumi.StringOutput)
}

// The bearer token used to authenticate against the SCIM endpoint. Never read back from the API: it is kept from the state and unset after an import.
func (o ScimServiceProviderOutput) Token() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *ScimServiceProvider) pulumi.StringPtrOutput { return v.Token }).(pulumi.StringPtrOutput)
}

type ScimServiceProviderArrayOutput struct{ *pulumi.OutputState }

func (ScimServiceProviderArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ScimServiceProvider)(nil)).Elem()
}

func (o ScimServiceProviderArrayOutput) ToScimServiceProviderArrayOutput() ScimServiceProviderArrayOutput {
	return o
}

func (o ScimServiceProviderArrayOutput) ToScimServiceProviderArrayOutputWithContext(ctx context.Context) ScimServiceProviderArrayOutput {
	return o
}

func (o ScimServiceProviderArrayOutput) Index(i pulumi.IntInput) ScimServiceProviderOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ScimServiceProvider {
		return vs[0].([]*ScimServiceProvider)[vs[1].(int)]
	}).(ScimServiceProviderOutput)
}

type ScimServiceProviderMapOutput struct{ *pulumi.OutputState }

func (ScimServiceProviderMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ScimServiceProvider)(nil)).Elem()
}

func (o ScimServiceProviderMapOutput) ToScimServiceProviderMapOutput() ScimServiceProviderMapOutput {
	return o
}

func (o ScimServiceProviderMapOutput) ToScimServiceProviderMapOutputWithContext(ctx context.Context) ScimServiceProviderMapOutput {
	return o
}

func (o ScimServiceProviderMapOutput) MapIndex(k pulumi.StringInput) ScimServiceProviderOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ScimServiceProvider {
		return vs[0].(map[string]*ScimServiceProvider)[vs[1].(string)]
	}).(ScimServiceProviderOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ScimServiceProviderInput)(nil)).Elem(), &ScimServiceProvider{})
	pulumi.RegisterInputType(reflect.TypeOf((*ScimServiceProviderArrayInput)(nil)).Elem(), ScimServiceProviderArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ScimServiceProviderMapInput)(nil)).Elem(), ScimServiceProviderMap{})
	pulumi.RegisterOutputType(ScimServiceProviderOutput{})
	pulumi.RegisterOutputType(ScimServiceProviderArrayOutput{})
	pulumi.RegisterOutputType(ScimServiceProviderMapOutput{})
}
