// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package pulumipocketid

import (
	"context"
	"reflect"

	"errors"
	"github.com/axnic/pulumi-pocket-id/sdk/go/pulumi-pocket-id/internal"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// A Pocket-ID signup token that lets new users create their own account.
type SignupToken struct {
	pulumi.CustomResourceState

	// The RFC 3339 timestamp at which the token was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The RFC 3339 timestamp at which the token expires.
	ExpiresAt pulumi.StringOutput `pulumi:"expiresAt"`
	// The secret signup token. It is captured at creation and carried in state; it is not read back from the API, so it is empty after an import.
	Token pulumi.StringOutput `pulumi:"token"`
	// The lifetime of the token in seconds. Changing it replaces the resource.
	Ttl pulumi.IntOutput `pulumi:"ttl"`
	// How many times the token can be used to sign up. Changing it replaces the resource.
	UsageLimit pulumi.IntOutput `pulumi:"usageLimit"`
	// The IDs of the groups users signing up with this token join. Changing them replaces the resource.
	UserGroupIds pulumi.StringArrayOutput `pulumi:"userGroupIds"`
}

// NewSignupToken registers a new resource with the given unique name, arguments, and options.
func NewSignupToken(ctx *pulumi.Context,
	name string, args *SignupTokenArgs, opts ...pulumi.ResourceOption) (*SignupToken, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Ttl == nil {
		return nil, errors.New("invalid value for required argument 'Ttl'")
	}
	if args.UsageLimit == nil {
		return nil, errors.New("invalid value for required argument 'UsageLimit'")
	}
	secrets := pulumi.AdditionalSecretOutputs([]string{
		"token",
	})
	opts = append(opts, secrets)
	replaceOnChanges := pulumi.ReplaceOnChanges([]string{
		"ttl",
		"usageLimit",
		"userGroupIds[*]",
	})
	opts = append(opts, replaceOnChanges)
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SignupToken
	err := ctx.RegisterResource("pocket-id:index:SignupToken", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSignupToken gets an existing SignupToken resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSignupToken(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SignupTokenState, opts ...pulumi.ResourceOption) (*SignupToken, error) {
	var resource SignupToken
	err := ctx.ReadResource("pocket-id:index:SignupToken", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SignupToken resources.
type signupTokenState struct {
}

type SignupTokenState struct {
}

func (SignupTokenState) ElementType() reflect.Type {
	return reflect.TypeOf((*signupTokenState)(nil)).Elem()
}

type signupTokenArgs struct {
	// The lifetime of the token in seconds. Changing it replaces the resource.
	Ttl int `pulumi:"ttl"`
	// How many times the token can be used to sign up. Changing it replaces the resource.
	UsageLimit int `pulumi:"usageLimit"`
	// The IDs of the groups users signing up with this token join. Changing them replaces the resource.
	UserGroupIds []string `pulumi:"userGroupIds"`
}

// The set of arguments for constructing a SignupToken resource.
type SignupTokenArgs struct {
	// The lifetime of the token in seconds. Changing it replaces the resource.
	Ttl pulumi.IntInput
	// How many times the token can be used to sign up. Changing it replaces the resource.
	UsageLimit pulumi.IntInput
	// The IDs of the groups users signing up with this token join. Changing them replaces the resource.
	UserGroupIds pulumi.StringArrayInput
}

func (SignupTokenArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*signupTokenArgs)(nil)).Elem()
}

type SignupTokenInput interface {
	pulumi.Input

	ToSignupTokenOutput() SignupTokenOutput
	ToSignupTokenOutputWithContext(ctx context.Context) SignupTokenOutput
}

func (*SignupToken) ElementType() reflect.Type {
	return reflect.TypeOf((**SignupToken)(nil)).Elem()
}

func (i *SignupToken) ToSignupTokenOutput() SignupTokenOutput {
	return i.ToSignupTokenOutputWithContext(context.Background())
}

func (i *SignupToken) ToSignupTokenOutputWithContext(ctx context.Context) SignupTokenOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SignupTokenOutput)
}

// SignupTokenArrayInput is an input type that accepts SignupTokenArray and SignupTokenArrayOutput values.
// You can construct a concrete instance of `SignupTokenArrayInput` via:
//
//	SignupTokenArray{ SignupTokenArgs{...} }
type SignupTokenArrayInput interface {
	pulumi.Input

	ToSignupTokenArrayOutput() SignupTokenArrayOutput
	ToSignupTokenArrayOutputWithContext(context.Context) SignupTokenArrayOutput
}

type SignupTokenArray []SignupTokenInput

func (SignupTokenArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SignupToken)(nil)).Elem()
}

func (i SignupTokenArray) ToSignupTokenArrayOutput() SignupTokenArrayOutput {
	return i.ToSignupTokenArrayOutputWithContext(context.Background())
}

func (i SignupTokenArray) ToSignupTokenArrayOutputWithContext(ctx context.Context) SignupTokenArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SignupTokenArrayOutput)
}

// SignupTokenMapInput is an input type that accepts SignupTokenMap and SignupTokenMapOutput values.
// You can construct a concrete instance of `SignupTokenMapInput` via:
//
//	SignupTokenMap{ "key": SignupTokenArgs{...} }
type SignupTokenMapInput interface {
	pulumi.Input

	ToSignupTokenMapOutput() SignupTokenMapOutput
	ToSignupTokenMapOutputWithContext(context.Context) SignupTokenMapOutput
}

type SignupTokenMap map[string]SignupTokenInput

func (SignupTokenMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SignupToken)(nil)).Elem()
}

func (i SignupTokenMap) ToSignupTokenMapOutput() SignupTokenMapOutput {
	return i.ToSignupTokenMapOutputWithContext(context.Background())
}

func (i SignupTokenMap) ToSignupTokenMapOutputWithContext(ctx context.Context) SignupTokenMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SignupTokenMapOutput)
}

type SignupTokenOutput struct{ *pulumi.OutputState }

func (SignupTokenOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SignupToken)(nil)).Elem()
}

func (o SignupTokenOutput) ToSignupTokenOutput() SignupTokenOutput {
	return o
}

func (o SignupTokenOutput) ToSignupTokenOutputWithContext(ctx context.Context) SignupTokenOutput {
	return o
}

// The RFC 3339 timestamp at which the token was created.
func (o SignupTokenOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *SignupToken) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The RFC 3339 timestamp at which the token expires.
func (o SignupTokenOutput) ExpiresAt() pulumi.StringOutput {
	return o.ApplyT(func(v *SignupToken) pulumi.StringOutput { return v.ExpiresAt }).(pulumi.StringOutput)
}

// The secret signup token. It is captured at creation and carried in state; it is not read back from the API, so it is empty after an import.
func (o SignupTokenOutput) Token() pulumi.StringOutput {
	return o.ApplyT(func(v *SignupToken) pulumi.StringOutput { return v.Token }).(pulumi.StringOutput)
}

// The lifetime of the token in seconds. Changing it replaces the resource.
func (o SignupTokenOutput) Ttl() pulumi.IntOutput {
	return o.ApplyT(func(v *SignupToken) pulumi.IntOutput { return v.Ttl }).(pulumi.IntOutput)
}

// How many times the token can be used to sign up. Changing it replaces the resource.
func (o SignupTokenOutput) UsageLimit() pulumi.IntOutput {
	return o.ApplyT(func(v *SignupToken) pulumi.IntOutput { return v.UsageLimit }).(pulumi.IntOutput)
}

// The IDs of the groups users signing up with this token join. Changing them replaces the resource.
func (o SignupTokenOutput) UserGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *SignupToken) pulumi.StringArrayOutput { return v.UserGroupIds }).(pulumi.StringArrayOutput)
}

type SignupTokenArrayOutput struct{ *pulumi.OutputState }

func (SignupTokenArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SignupToken)(nil)).Elem()
}

func (o SignupTokenArrayOutput) ToSignupTokenArrayOutput() SignupTokenArrayOutput {
	return o
}

func (o SignupTokenArrayOutput) ToSignupTokenArrayOutputWithContext(ctx context.Context) SignupTokenArrayOutput {
	return o
}

func (o SignupTokenArrayOutput) Index(i pulumi.IntInput) SignupTokenOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SignupToken {
		return vs[0].([]*SignupToken)[vs[1].(int)]
	}).(SignupTokenOutput)
}

type SignupTokenMapOutput struct{ *pulumi.OutputState }

func (SignupTokenMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SignupToken)(nil)).Elem()
}

func (o SignupTokenMapOutput) ToSignupTokenMapOutput() SignupTokenMapOutput {
	return o
}

func (o SignupTokenMapOutput) ToSignupTokenMapOutputWithContext(ctx context.Context) SignupTokenMapOutput {
	return o
}

func (o SignupTokenMapOutput) MapIndex(k pulumi.StringInput) SignupTokenOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SignupToken {
		return vs[0].(map[string]*SignupToken)[vs[1].(string)]
	}).(SignupTokenOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SignupTokenInput)(nil)).Elem(), &SignupToken{})
	pulumi.RegisterInputType(reflect.TypeOf((*SignupTokenArrayInput)(nil)).Elem(), SignupTokenArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SignupTokenMapInput)(nil)).Elem(), SignupTokenMap{})
	pulumi.RegisterOutputType(SignupTokenOutput{})
	pulumi.RegisterOutputType(SignupTokenArrayOutput{})
	pulumi.RegisterOutputType(SignupTokenMapOutput{})
}
