// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId
{
    /// <summary>
    /// The instance-wide configuration of Pocket-ID. It is a singleton with the fixed ID "app-config": only the fields that are set are managed, the others keep their current value on the server, and destroying the resource leaves the configuration untouched. Use at most one per instance.
    /// </summary>
    [PocketIdResourceType("pocket-id:index:ApplicationConfiguration")]
    public partial class ApplicationConfiguration : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The UI accent color, as "default" or a CSS color value.
        /// </summary>
        [Output("accentColor")]
        public Output<string?> AccentColor { get; private set; } = null!;

        /// <summary>
        /// Whether users may edit their own account details.
        /// </summary>
        [Output("allowOwnAccountEdit")]
        public Output<bool?> AllowOwnAccountEdit { get; private set; } = null!;

        /// <summary>
        /// Who may sign up by themselves: "disabled", "withToken" or "open".
        /// </summary>
        [Output("allowUserSignups")]
        public Output<string?> AllowUserSignups { get; private set; } = null!;

        /// <summary>
        /// The application name shown in the UI and in emails (1 to 30 characters).
        /// </summary>
        [Output("appName")]
        public Output<string?> AppName { get; private set; } = null!;

        /// <summary>
        /// Whether a secret is generated automatically when an OIDC client is created.
        /// </summary>
        [Output("autoCreateOidcClientSecret")]
        public Output<bool?> AutoCreateOidcClientSecret { get; private set; } = null!;

        /// <summary>
        /// The allowlist of URLs accepted as OIDC client metadata documents (CIMD), in the format Pocket-ID expects.
        /// </summary>
        [Output("cimdUrlAllowlist")]
        public Output<string?> CimdUrlAllowlist { get; private set; } = null!;

        /// <summary>
        /// Whether to disable the UI animations.
        /// </summary>
        [Output("disableAnimations")]
        public Output<bool?> DisableAnimations { get; private set; } = null!;

        /// <summary>
        /// Whether an email is sent when an API key is about to expire.
        /// </summary>
        [Output("emailApiKeyExpirationEnabled")]
        public Output<bool?> EmailApiKeyExpirationEnabled { get; private set; } = null!;

        /// <summary>
        /// Whether an email is sent when a user signs in from a new device.
        /// </summary>
        [Output("emailLoginNotificationEnabled")]
        public Output<bool?> EmailLoginNotificationEnabled { get; private set; } = null!;

        /// <summary>
        /// Whether administrators may send one-time access links by email.
        /// </summary>
        [Output("emailOneTimeAccessAsAdminEnabled")]
        public Output<bool?> EmailOneTimeAccessAsAdminEnabled { get; private set; } = null!;

        /// <summary>
        /// Whether unauthenticated users may request a one-time access link by email.
        /// </summary>
        [Output("emailOneTimeAccessAsUnauthenticatedEnabled")]
        public Output<bool?> EmailOneTimeAccessAsUnauthenticatedEnabled { get; private set; } = null!;

        /// <summary>
        /// Whether users must verify their email address.
        /// </summary>
        [Output("emailVerificationEnabled")]
        public Output<bool?> EmailVerificationEnabled { get; private set; } = null!;

        /// <summary>
        /// Whether emails are considered verified by default.
        /// </summary>
        [Output("emailsVerified")]
        public Output<bool?> EmailsVerified { get; private set; } = null!;

        /// <summary>
        /// The path of the page users land on after signing in, e.g. "/settings/account".
        /// </summary>
        [Output("homePageUrl")]
        public Output<string?> HomePageUrl { get; private set; } = null!;

        /// <summary>
        /// The name of the LDAP group whose members become Pocket-ID administrators.
        /// </summary>
        [Output("ldapAdminGroupName")]
        public Output<string?> LdapAdminGroupName { get; private set; } = null!;

        /// <summary>
        /// The LDAP attribute listing the members of a group.
        /// </summary>
        [Output("ldapAttributeGroupMember")]
        public Output<string?> LdapAttributeGroupMember { get; private set; } = null!;

        /// <summary>
        /// The LDAP attribute mapped to the group name.
        /// </summary>
        [Output("ldapAttributeGroupName")]
        public Output<string?> LdapAttributeGroupName { get; private set; } = null!;

        /// <summary>
        /// The LDAP attribute holding the unique identifier of a group.
        /// </summary>
        [Output("ldapAttributeGroupUniqueIdentifier")]
        public Output<string?> LdapAttributeGroupUniqueIdentifier { get; private set; } = null!;

        /// <summary>
        /// The LDAP attribute mapped to the display name.
        /// </summary>
        [Output("ldapAttributeUserDisplayName")]
        public Output<string?> LdapAttributeUserDisplayName { get; private set; } = null!;

        /// <summary>
        /// The LDAP attribute mapped to the email address.
        /// </summary>
        [Output("ldapAttributeUserEmail")]
        public Output<string?> LdapAttributeUserEmail { get; private set; } = null!;

        /// <summary>
        /// The LDAP attribute mapped to the first name.
        /// </summary>
        [Output("ldapAttributeUserFirstName")]
        public Output<string?> LdapAttributeUserFirstName { get; private set; } = null!;

        /// <summary>
        /// The LDAP attribute mapped to the last name.
        /// </summary>
        [Output("ldapAttributeUserLastName")]
        public Output<string?> LdapAttributeUserLastName { get; private set; } = null!;

        /// <summary>
        /// The LDAP attribute mapped to the profile picture.
        /// </summary>
        [Output("ldapAttributeUserProfilePicture")]
        public Output<string?> LdapAttributeUserProfilePicture { get; private set; } = null!;

        /// <summary>
        /// The LDAP attribute holding the unique identifier of a user.
        /// </summary>
        [Output("ldapAttributeUserUniqueIdentifier")]
        public Output<string?> LdapAttributeUserUniqueIdentifier { get; private set; } = null!;

        /// <summary>
        /// The LDAP attribute mapped to the user name.
        /// </summary>
        [Output("ldapAttributeUserUsername")]
        public Output<string?> LdapAttributeUserUsername { get; private set; } = null!;

        /// <summary>
        /// The LDAP base DN under which users and groups are searched.
        /// </summary>
        [Output("ldapBase")]
        public Output<string?> LdapBase { get; private set; } = null!;

        /// <summary>
        /// The distinguished name used to bind to the LDAP server.
        /// </summary>
        [Output("ldapBindDn")]
        public Output<string?> LdapBindDn { get; private set; } = null!;

        /// <summary>
        /// The LDAP bind password. It is a secret and is never read back from Pocket-ID: the value in state is the one from the program, and it is empty after an import.
        /// </summary>
        [Output("ldapBindPassword")]
        public Output<string?> LdapBindPassword { get; private set; } = null!;

        /// <summary>
        /// Whether LDAP synchronization is enabled.
        /// </summary>
        [Output("ldapEnabled")]
        public Output<bool?> LdapEnabled { get; private set; } = null!;

        /// <summary>
        /// Whether to skip the verification of the LDAP server certificate.
        /// </summary>
        [Output("ldapSkipCertVerify")]
        public Output<bool?> LdapSkipCertVerify { get; private set; } = null!;

        /// <summary>
        /// Whether users removed from LDAP are disabled instead of deleted.
        /// </summary>
        [Output("ldapSoftDeleteUsers")]
        public Output<bool?> LdapSoftDeleteUsers { get; private set; } = null!;

        /// <summary>
        /// The LDAP server URL, e.g. "ldaps://ldap.example.com:636".
        /// </summary>
        [Output("ldapUrl")]
        public Output<string?> LdapUrl { get; private set; } = null!;

        /// <summary>
        /// The LDAP filter selecting groups, e.g. "(objectClass=groupOfNames)".
        /// </summary>
        [Output("ldapUserGroupSearchFilter")]
        public Output<string?> LdapUserGroupSearchFilter { get; private set; } = null!;

        /// <summary>
        /// The LDAP filter selecting users, e.g. "(objectClass=person)".
        /// </summary>
        [Output("ldapUserSearchFilter")]
        public Output<string?> LdapUserSearchFilter { get; private set; } = null!;

        /// <summary>
        /// Whether an email address is required for every user.
        /// </summary>
        [Output("requireUserEmail")]
        public Output<bool?> RequireUserEmail { get; private set; } = null!;

        /// <summary>
        /// The session lifetime, in minutes.
        /// </summary>
        [Output("sessionDuration")]
        public Output<int?> SessionDuration { get; private set; } = null!;

        /// <summary>
        /// The custom claims given to new users, as the JSON array string Pocket-ID expects.
        /// </summary>
        [Output("signupDefaultCustomClaims")]
        public Output<string?> SignupDefaultCustomClaims { get; private set; } = null!;

        /// <summary>
        /// The IDs of the user groups new users join, as the JSON array string Pocket-ID expects.
        /// </summary>
        [Output("signupDefaultUserGroupIDs")]
        public Output<string?> SignupDefaultUserGroupIDs { get; private set; } = null!;

        /// <summary>
        /// The sender address of outgoing emails.
        /// </summary>
        [Output("smtpFrom")]
        public Output<string?> SmtpFrom { get; private set; } = null!;

        /// <summary>
        /// The SMTP server host name.
        /// </summary>
        [Output("smtpHost")]
        public Output<string?> SmtpHost { get; private set; } = null!;

        /// <summary>
        /// The SMTP password. It is a secret and is never read back from Pocket-ID: the value in state is the one from the program, and it is empty after an import.
        /// </summary>
        [Output("smtpPassword")]
        public Output<string?> SmtpPassword { get; private set; } = null!;

        /// <summary>
        /// The SMTP server port.
        /// </summary>
        [Output("smtpPort")]
        public Output<int?> SmtpPort { get; private set; } = null!;

        /// <summary>
        /// Whether to skip the verification of the SMTP server certificate.
        /// </summary>
        [Output("smtpSkipCertVerify")]
        public Output<bool?> SmtpSkipCertVerify { get; private set; } = null!;

        /// <summary>
        /// The SMTP transport security: "none", "starttls" or "tls".
        /// </summary>
        [Output("smtpTls")]
        public Output<string?> SmtpTls { get; private set; } = null!;

        /// <summary>
        /// The SMTP user name.
        /// </summary>
        [Output("smtpUser")]
        public Output<string?> SmtpUser { get; private set; } = null!;

        /// <summary>
        /// Whether passkeys synced between devices are accepted.
        /// </summary>
        [Output("webauthnAllowSyncedPasskeys")]
        public Output<bool?> WebauthnAllowSyncedPasskeys { get; private set; } = null!;

        /// <summary>
        /// The accepted authenticator attachment: "any", "platform" or "cross-platform".
        /// </summary>
        [Output("webauthnAuthenticatorAttachment")]
        public Output<string?> WebauthnAuthenticatorAttachment { get; private set; } = null!;

        /// <summary>
        /// The user verification requirement: "required" or "preferred".
        /// </summary>
        [Output("webauthnUserVerification")]
        public Output<string?> WebauthnUserVerification { get; private set; } = null!;


        /// <summary>
        /// Create a ApplicationConfiguration resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ApplicationConfiguration(string name, ApplicationConfigurationArgs? args = null, CustomResourceOptions? options = null)
            : base("pocket-id:index:ApplicationConfiguration", name, args ?? new ApplicationConfigurationArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ApplicationConfiguration(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pocket-id:index:ApplicationConfiguration", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/axnic/pulumi-pocket-id",
                AdditionalSecretOutputs =
                {
                    "ldapBindPassword",
                    "smtpPassword",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ApplicationConfiguration resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ApplicationConfiguration Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ApplicationConfiguration(name, id, options);
        }
    }

    public sealed class ApplicationConfigurationArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The UI accent color, as "default" or a CSS color value.
        /// </summary>
        [Input("accentColor")]
        public Input<string>? AccentColor { get; set; }

        /// <summary>
        /// Whether users may edit their own account details.
        /// </summary>
        [Input("allowOwnAccountEdit")]
        public Input<bool>? AllowOwnAccountEdit { get; set; }

        /// <summary>
        /// Who may sign up by themselves: "disabled", "withToken" or "open".
        /// </summary>
        [Input("allowUserSignups")]
        public Input<string>? AllowUserSignups { get; set; }

        /// <summary>
        /// The application name shown in the UI and in emails (1 to 30 characters).
        /// </summary>
        [Input("appName")]
        public Input<string>? AppName { get; set; }

        /// <summary>
        /// Whether a secret is generated automatically when an OIDC client is created.
        /// </summary>
        [Input("autoCreateOidcClientSecret")]
        public Input<bool>? AutoCreateOidcClientSecret { get; set; }

        /// <summary>
        /// The allowlist of URLs accepted as OIDC client metadata documents (CIMD), in the format Pocket-ID expects.
        /// </summary>
        [Input("cimdUrlAllowlist")]
        public Input<string>? CimdUrlAllowlist { get; set; }

        /// <summary>
        /// Whether to disable the UI animations.
        /// </summary>
        [Input("disableAnimations")]
        public Input<bool>? DisableAnimations { get; set; }

        /// <summary>
        /// Whether an email is sent when an API key is about to expire.
        /// </summary>
        [Input("emailApiKeyExpirationEnabled")]
        public Input<bool>? EmailApiKeyExpirationEnabled { get; set; }

        /// <summary>
        /// Whether an email is sent when a user signs in from a new device.
        /// </summary>
        [Input("emailLoginNotificationEnabled")]
        public Input<bool>? EmailLoginNotificationEnabled { get; set; }

        /// <summary>
        /// Whether administrators may send one-time access links by email.
        /// </summary>
        [Input("emailOneTimeAccessAsAdminEnabled")]
        public Input<bool>? EmailOneTimeAccessAsAdminEnabled { get; set; }

        /// <summary>
        /// Whether unauthenticated users may request a one-time access link by email.
        /// </summary>
        [Input("emailOneTimeAccessAsUnauthenticatedEnabled")]
        public Input<bool>? EmailOneTimeAccessAsUnauthenticatedEnabled { get; set; }

        /// <summary>
        /// Whether users must verify their email address.
        /// </summary>
        [Input("emailVerificationEnabled")]
        public Input<bool>? EmailVerificationEnabled { get; set; }

        /// <summary>
        /// Whether emails are considered verified by default.
        /// </summary>
        [Input("emailsVerified")]
        public Input<bool>? EmailsVerified { get; set; }

        /// <summary>
        /// The path of the page users land on after signing in, e.g. "/settings/account".
        /// </summary>
        [Input("homePageUrl")]
        public Input<string>? HomePageUrl { get; set; }

        /// <summary>
        /// The name of the LDAP group whose members become Pocket-ID administrators.
        /// </summary>
        [Input("ldapAdminGroupName")]
        public Input<string>? LdapAdminGroupName { get; set; }

        /// <summary>
        /// The LDAP attribute listing the members of a group.
        /// </summary>
        [Input("ldapAttributeGroupMember")]
        public Input<string>? LdapAttributeGroupMember { get; set; }

        /// <summary>
        /// The LDAP attribute mapped to the group name.
        /// </summary>
        [Input("ldapAttributeGroupName")]
        public Input<string>? LdapAttributeGroupName { get; set; }

        /// <summary>
        /// The LDAP attribute holding the unique identifier of a group.
        /// </summary>
        [Input("ldapAttributeGroupUniqueIdentifier")]
        public Input<string>? LdapAttributeGroupUniqueIdentifier { get; set; }

        /// <summary>
        /// The LDAP attribute mapped to the display name.
        /// </summary>
        [Input("ldapAttributeUserDisplayName")]
        public Input<string>? LdapAttributeUserDisplayName { get; set; }

        /// <summary>
        /// The LDAP attribute mapped to the email address.
        /// </summary>
        [Input("ldapAttributeUserEmail")]
        public Input<string>? LdapAttributeUserEmail { get; set; }

        /// <summary>
        /// The LDAP attribute mapped to the first name.
        /// </summary>
        [Input("ldapAttributeUserFirstName")]
        public Input<string>? LdapAttributeUserFirstName { get; set; }

        /// <summary>
        /// The LDAP attribute mapped to the last name.
        /// </summary>
        [Input("ldapAttributeUserLastName")]
        public Input<string>? LdapAttributeUserLastName { get; set; }

        /// <summary>
        /// The LDAP attribute mapped to the profile picture.
        /// </summary>
        [Input("ldapAttributeUserProfilePicture")]
        public Input<string>? LdapAttributeUserProfilePicture { get; set; }

        /// <summary>
        /// The LDAP attribute holding the unique identifier of a user.
        /// </summary>
        [Input("ldapAttributeUserUniqueIdentifier")]
        public Input<string>? LdapAttributeUserUniqueIdentifier { get; set; }

        /// <summary>
        /// The LDAP attribute mapped to the user name.
        /// </summary>
        [Input("ldapAttributeUserUsername")]
        public Input<string>? LdapAttributeUserUsername { get; set; }

        /// <summary>
        /// The LDAP base DN under which users and groups are searched.
        /// </summary>
        [Input("ldapBase")]
        public Input<string>? LdapBase { get; set; }

        /// <summary>
        /// The distinguished name used to bind to the LDAP server.
        /// </summary>
        [Input("ldapBindDn")]
        public Input<string>? LdapBindDn { get; set; }

        [Input("ldapBindPassword")]
        private Input<string>? _ldapBindPassword;

        /// <summary>
        /// The LDAP bind password. It is a secret and is never read back from Pocket-ID: the value in state is the one from the program, and it is empty after an import.
        /// </summary>
        public Input<string>? LdapBindPassword
        {
            get => _ldapBindPassword;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _ldapBindPassword = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// Whether LDAP synchronization is enabled.
        /// </summary>
        [Input("ldapEnabled")]
        public Input<bool>? LdapEnabled { get; set; }

        /// <summary>
        /// Whether to skip the verification of the LDAP server certificate.
        /// </summary>
        [Input("ldapSkipCertVerify")]
        public Input<bool>? LdapSkipCertVerify { get; set; }

        /// <summary>
        /// Whether users removed from LDAP are disabled instead of deleted.
        /// </summary>
        [Input("ldapSoftDeleteUsers")]
        public Input<bool>? LdapSoftDeleteUsers { get; set; }

        /// <summary>
        /// The LDAP server URL, e.g. "ldaps://ldap.example.com:636".
        /// </summary>
        [Input("ldapUrl")]
        public Input<string>? LdapUrl { get; set; }

        /// <summary>
        /// The LDAP filter selecting groups, e.g. "(objectClass=groupOfNames)".
        /// </summary>
        [Input("ldapUserGroupSearchFilter")]
        public Input<string>? LdapUserGroupSearchFilter { get; set; }

        /// <summary>
        /// The LDAP filter selecting users, e.g. "(objectClass=person)".
        /// </summary>
        [Input("ldapUserSearchFilter")]
        public Input<string>? LdapUserSearchFilter { get; set; }

        /// <summary>
        /// Whether an email address is required for every user.
        /// </summary>
        [Input("requireUserEmail")]
        public Input<bool>? RequireUserEmail { get; set; }

        /// <summary>
        /// The session lifetime, in minutes.
        /// </summary>
        [Input("sessionDuration")]
        public Input<int>? SessionDuration { get; set; }

        /// <summary>
        /// The custom claims given to new users, as the JSON array string Pocket-ID expects.
        /// </summary>
        [Input("signupDefaultCustomClaims")]
        public Input<string>? SignupDefaultCustomClaims { get; set; }

        /// <summary>
        /// The IDs of the user groups new users join, as the JSON array string Pocket-ID expects.
        /// </summary>
        [Input("signupDefaultUserGroupIDs")]
        public Input<string>? SignupDefaultUserGroupIDs { get; set; }

        /// <summary>
        /// The sender address of outgoing emails.
        /// </summary>
        [Input("smtpFrom")]
        public Input<string>? SmtpFrom { get; set; }

        /// <summary>
        /// The SMTP server host name.
        /// </summary>
        [Input("smtpHost")]
        public Input<string>? SmtpHost { get; set; }

        [Input("smtpPassword")]
        private Input<string>? _smtpPassword;

        /// <summary>
        /// The SMTP password. It is a secret and is never read back from Pocket-ID: the value in state is the one from the program, and it is empty after an import.
        /// </summary>
        public Input<string>? SmtpPassword
        {
            get => _smtpPassword;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _smtpPassword = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        /// <summary>
        /// The SMTP server port.
        /// </summary>
        [Input("smtpPort")]
        public Input<int>? SmtpPort { get; set; }

        /// <summary>
        /// Whether to skip the verification of the SMTP server certificate.
        /// </summary>
        [Input("smtpSkipCertVerify")]
        public Input<bool>? SmtpSkipCertVerify { get; set; }

        /// <summary>
        /// The SMTP transport security: "none", "starttls" or "tls".
        /// </summary>
        [Input("smtpTls")]
        public Input<string>? SmtpTls { get; set; }

        /// <summary>
        /// The SMTP user name.
        /// </summary>
        [Input("smtpUser")]
        public Input<string>? SmtpUser { get; set; }

        /// <summary>
        /// Whether passkeys synced between devices are accepted.
        /// </summary>
        [Input("webauthnAllowSyncedPasskeys")]
        public Input<bool>? WebauthnAllowSyncedPasskeys { get; set; }

        /// <summary>
        /// The accepted authenticator attachment: "any", "platform" or "cross-platform".
        /// </summary>
        [Input("webauthnAuthenticatorAttachment")]
        public Input<string>? WebauthnAuthenticatorAttachment { get; set; }

        /// <summary>
        /// The user verification requirement: "required" or "preferred".
        /// </summary>
        [Input("webauthnUserVerification")]
        public Input<string>? WebauthnUserVerification { get; set; }

        public ApplicationConfigurationArgs()
        {
        }
        public static new ApplicationConfigurationArgs Empty => new ApplicationConfigurationArgs();
    }
}
