// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId
{
    [PocketIdResourceType("pocket-id:index:CustomClaims")]
    public partial class CustomClaims : global::Pulumi.CustomResource
    {
        [Output("claims")]
        public Output<ImmutableArray<Outputs.CustomClaim>> Claims { get; private set; } = null!;

        [Output("ownerId")]
        public Output<string> OwnerId { get; private set; } = null!;

        [Output("ownerType")]
        public Output<string> OwnerType { get; private set; } = null!;


        /// <summary>
        /// Create a CustomClaims resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public CustomClaims(string name, CustomClaimsArgs args, CustomResourceOptions? options = null)
            : base("pocket-id:index:CustomClaims", name, args ?? new CustomClaimsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private CustomClaims(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pocket-id:index:CustomClaims", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/axnic/pulumi-pocket-id",
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing CustomClaims resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static CustomClaims Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new CustomClaims(name, id, options);
        }
    }

    public sealed class CustomClaimsArgs : global::Pulumi.ResourceArgs
    {
        [Input("claims")]
        private InputList<Inputs.CustomClaimArgs>? _claims;
        public InputList<Inputs.CustomClaimArgs> Claims
        {
            get => _claims ?? (_claims = new InputList<Inputs.CustomClaimArgs>());
            set => _claims = value;
        }

        [Input("ownerId", required: true)]
        public Input<string> OwnerId { get; set; } = null!;

        [Input("ownerType", required: true)]
        public Input<string> OwnerType { get; set; } = null!;

        public CustomClaimsArgs()
        {
        }
        public static new CustomClaimsArgs Empty => new CustomClaimsArgs();
    }
}
