// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.ComponentModel;
using Pulumi;

namespace Axnic.Pulumi.PocketId
{
    [EnumType]
    public readonly struct ApplicationImageType : IEquatable<ApplicationImageType>
    {
        private readonly string _value;

        private ApplicationImageType(string value)
        {
            _value = value ?? throw new ArgumentNullException(nameof(value));
        }

        /// <summary>
        /// The light mode application logo.
        /// </summary>
        public static ApplicationImageType Logo { get; } = new ApplicationImageType("logo");
        /// <summary>
        /// The dark mode application logo.
        /// </summary>
        public static ApplicationImageType DarkLogo { get; } = new ApplicationImageType("darkLogo");
        /// <summary>
        /// The favicon. It cannot be deleted.
        /// </summary>
        public static ApplicationImageType Favicon { get; } = new ApplicationImageType("favicon");
        /// <summary>
        /// The login page background.
        /// </summary>
        public static ApplicationImageType Background { get; } = new ApplicationImageType("background");
        /// <summary>
        /// The image used in e-mails. It cannot be deleted.
        /// </summary>
        public static ApplicationImageType Email { get; } = new ApplicationImageType("email");
        /// <summary>
        /// The default profile picture of users.
        /// </summary>
        public static ApplicationImageType DefaultProfilePicture { get; } = new ApplicationImageType("defaultProfilePicture");

        public static bool operator ==(ApplicationImageType left, ApplicationImageType right) => left.Equals(right);
        public static bool operator !=(ApplicationImageType left, ApplicationImageType right) => !left.Equals(right);

        public static explicit operator string(ApplicationImageType value) => value._value;

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override bool Equals(object? obj) => obj is ApplicationImageType other && Equals(other);
        public bool Equals(ApplicationImageType other) => string.Equals(_value, other._value, StringComparison.Ordinal);

        [EditorBrowsable(EditorBrowsableState.Never)]
        public override int GetHashCode() => _value?.GetHashCode() ?? 0;

        public override string ToString() => _value;
    }
}
