// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId
{
    public static class GetUserGroup
    {
        /// <summary>
        /// Looks up a Pocket-ID user group by ID or by exact name.
        /// </summary>
        public static Task<GetUserGroupResult> InvokeAsync(GetUserGroupArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetUserGroupResult>("pocket-id:index:getUserGroup", args ?? new GetUserGroupArgs(), options.WithDefaults());

        /// <summary>
        /// Looks up a Pocket-ID user group by ID or by exact name.
        /// </summary>
        public static Output<GetUserGroupResult> Invoke(GetUserGroupInvokeArgs? args = null, InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetUserGroupResult>("pocket-id:index:getUserGroup", args ?? new GetUserGroupInvokeArgs(), options.WithDefaults());

        /// <summary>
        /// Looks up a Pocket-ID user group by ID or by exact name.
        /// </summary>
        public static Output<GetUserGroupResult> Invoke(GetUserGroupInvokeArgs args, InvokeOutputOptions options)
            => global::Pulumi.Deployment.Instance.Invoke<GetUserGroupResult>("pocket-id:index:getUserGroup", args ?? new GetUserGroupInvokeArgs(), options.WithDefaults());
    }


    public sealed class GetUserGroupArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The exact name of the group. Exactly one of userGroupId or name must be set.
        /// </summary>
        [Input("name")]
        public string? Name { get; set; }

        /// <summary>
        /// The ID of the group. Exactly one of userGroupId or name must be set.
        /// </summary>
        [Input("userGroupId")]
        public string? UserGroupId { get; set; }

        public GetUserGroupArgs()
        {
        }
        public static new GetUserGroupArgs Empty => new GetUserGroupArgs();
    }

    public sealed class GetUserGroupInvokeArgs : global::Pulumi.InvokeArgs
    {
        /// <summary>
        /// The exact name of the group. Exactly one of userGroupId or name must be set.
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// The ID of the group. Exactly one of userGroupId or name must be set.
        /// </summary>
        [Input("userGroupId")]
        public Input<string>? UserGroupId { get; set; }

        public GetUserGroupInvokeArgs()
        {
        }
        public static new GetUserGroupInvokeArgs Empty => new GetUserGroupInvokeArgs();
    }


    [OutputType]
    public sealed class GetUserGroupResult
    {
        /// <summary>
        /// The custom claims of the group.
        /// </summary>
        public readonly ImmutableDictionary<string, string> CustomClaims;
        /// <summary>
        /// The human-readable name of the group.
        /// </summary>
        public readonly string FriendlyName;
        /// <summary>
        /// The name of the group.
        /// </summary>
        public readonly string Name;
        /// <summary>
        /// The ID of the group.
        /// </summary>
        public readonly string UserGroupId;
        /// <summary>
        /// The IDs of the members of the group.
        /// </summary>
        public readonly ImmutableArray<string> UserIds;

        [OutputConstructor]
        private GetUserGroupResult(
            ImmutableDictionary<string, string> customClaims,

            string friendlyName,

            string name,

            string userGroupId,

            ImmutableArray<string> userIds)
        {
            CustomClaims = customClaims;
            FriendlyName = friendlyName;
            Name = name;
            UserGroupId = userGroupId;
            UserIds = userIds;
        }
    }
}
