// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId
{
    /// <summary>
    /// A client secret of an OIDC client. Several secrets can coexist, which allows rotating a secret without downtime: create the new one, then remove the old one. Every property is immutable: changing one replaces the secret.
    /// </summary>
    [PocketIdResourceType("pocket-id:index:OidcClientSecret")]
    public partial class OidcClientSecret : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The ID of the OIDC client the secret belongs to. Changing it replaces the secret.
        /// </summary>
        [Output("clientId")]
        public Output<string> ClientId { get; private set; } = null!;

        /// <summary>
        /// The creation date of the secret.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The expiration date of the secret (RFC 3339). Never expires when unset. Changing it replaces the secret.
        /// </summary>
        [Output("expiresAt")]
        public Output<string?> ExpiresAt { get; private set; } = null!;

        /// <summary>
        /// The first characters of the secret, as reported by Pocket-ID.
        /// </summary>
        [Output("prefix")]
        public Output<string> Prefix { get; private set; } = null!;

        /// <summary>
        /// The plain-text secret. Only returned by Pocket-ID at creation, so it is kept from the state and is empty after an import.
        /// </summary>
        [Output("secret")]
        public Output<string> Secret { get; private set; } = null!;

        /// <summary>
        /// The ID of the secret.
        /// </summary>
        [Output("secretId")]
        public Output<string> SecretId { get; private set; } = null!;


        /// <summary>
        /// Create a OidcClientSecret resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OidcClientSecret(string name, OidcClientSecretArgs args, CustomResourceOptions? options = null)
            : base("pocket-id:index:OidcClientSecret", name, args ?? new OidcClientSecretArgs(), MakeResourceOptions(options, ""))
        {
        }

        private OidcClientSecret(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pocket-id:index:OidcClientSecret", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/axnic/pulumi-pocket-id",
                AdditionalSecretOutputs =
                {
                    "secret",
                },
                ReplaceOnChanges =
                {
                    "clientId",
                    "expiresAt",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing OidcClientSecret resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static OidcClientSecret Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new OidcClientSecret(name, id, options);
        }
    }

    public sealed class OidcClientSecretArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The ID of the OIDC client the secret belongs to. Changing it replaces the secret.
        /// </summary>
        [Input("clientId", required: true)]
        public Input<string> ClientId { get; set; } = null!;

        /// <summary>
        /// The expiration date of the secret (RFC 3339). Never expires when unset. Changing it replaces the secret.
        /// </summary>
        [Input("expiresAt")]
        public Input<string>? ExpiresAt { get; set; }

        public OidcClientSecretArgs()
        {
        }
        public static new OidcClientSecretArgs Empty => new OidcClientSecretArgs();
    }
}
