// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId
{
    /// <summary>
    /// An OIDC client of Pocket-ID. The client never creates a secret by itself; use OidcClientSecret to generate one. The allowed user groups are owned by this resource. The logos are set either from a URL (logoUrl, darkLogoUrl) or from an uploaded file (logo, darkLogo), never both for the same variant.
    /// </summary>
    [PocketIdResourceType("pocket-id:index:OidcClient")]
    public partial class OidcClient : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The access token lifetime in minutes. Pocket-ID's default applies when unset.
        /// </summary>
        [Output("accessTokenDurationMinutes")]
        public Output<int?> AccessTokenDurationMinutes { get; private set; } = null!;

        /// <summary>
        /// The IDs of the user groups allowed to use the client. Authoritative: the set is replaced on every update, and the client is restricted to these groups when the list is non-empty (unrestricted when empty).
        /// </summary>
        [Output("allowedUserGroupIds")]
        public Output<ImmutableArray<string>> AllowedUserGroupIds { get; private set; } = null!;

        /// <summary>
        /// The URL called for OIDC back-channel logout. Requires Pocket-ID v2.17.0 or later: older versions ignore the field, so the provider fails instead of silently dropping it.
        /// </summary>
        [Output("backchannelLogoutUrl")]
        public Output<string?> BackchannelLogoutUrl { get; private set; } = null!;

        /// <summary>
        /// The allowed redirect URLs.
        /// </summary>
        [Output("callbackUrls")]
        public Output<ImmutableArray<string>> CallbackUrls { get; private set; } = null!;

        /// <summary>
        /// The ID of the client. Generated by Pocket-ID when unset. Changing it replaces the client.
        /// </summary>
        [Output("clientId")]
        public Output<string?> ClientId { get; private set; } = null!;

        /// <summary>
        /// The client type reported by Pocket-ID (confidential or public).
        /// </summary>
        [Output("clientType")]
        public Output<string> ClientType { get; private set; } = null!;

        /// <summary>
        /// The credentials of the client managed here (federated identities).
        /// </summary>
        [Output("credentials")]
        public Output<Outputs.OidcClientCredentials?> Credentials { get; private set; } = null!;

        /// <summary>
        /// The dark mode client logo (PNG, JPG or SVG) uploaded from a file, as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file and removing it deletes the logo. Mutually exclusive with darkLogoUrl. An asset cannot be read back: after an import it is empty and must be set in the program, which uploads the logo again if it differs from the served one.
        /// </summary>
        [Output("darkLogo")]
        public Output<AssetOrArchive?> DarkLogo { get; private set; } = null!;

        /// <summary>
        /// The hex SHA-256 digest of the uploaded dark mode logo (see darkLogo). At refresh it is the digest of the bytes currently served by Pocket-ID, so out-of-band changes show up as a diff.
        /// </summary>
        [Output("darkLogoSha256")]
        public Output<string?> DarkLogoSha256 { get; private set; } = null!;

        /// <summary>
        /// A URL from which Pocket-ID fetches the dark mode logo. When unset, the dark logo is removed. It is not read back from the API. Mutually exclusive with darkLogo (uploaded file).
        /// </summary>
        [Output("darkLogoUrl")]
        public Output<string?> DarkLogoUrl { get; private set; } = null!;

        /// <summary>
        /// A description of the client (150 characters max).
        /// </summary>
        [Output("description")]
        public Output<string?> Description { get; private set; } = null!;

        /// <summary>
        /// Whether the client has a dark mode logo.
        /// </summary>
        [Output("hasDarkLogo")]
        public Output<bool> HasDarkLogo { get; private set; } = null!;

        /// <summary>
        /// Whether the client has a logo.
        /// </summary>
        [Output("hasLogo")]
        public Output<bool> HasLogo { get; private set; } = null!;

        /// <summary>
        /// Whether access is restricted to the allowed user groups.
        /// </summary>
        [Output("isGroupRestricted")]
        public Output<bool> IsGroupRestricted { get; private set; } = null!;

        /// <summary>
        /// Whether the client is public (no client secret, PKCE recommended).
        /// </summary>
        [Output("isPublic")]
        public Output<bool?> IsPublic { get; private set; } = null!;

        /// <summary>
        /// The URL used to launch the application from the Pocket-ID dashboard.
        /// </summary>
        [Output("launchUrl")]
        public Output<string?> LaunchUrl { get; private set; } = null!;

        /// <summary>
        /// The client logo (PNG, JPG or SVG) uploaded from a file, as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file and removing it deletes the logo. Mutually exclusive with logoUrl. An asset cannot be read back: after an import it is empty and must be set in the program, which uploads the logo again if it differs from the served one.
        /// </summary>
        [Output("logo")]
        public Output<AssetOrArchive?> Logo { get; private set; } = null!;

        /// <summary>
        /// The hex SHA-256 digest of the uploaded logo (see logo). At refresh it is the digest of the bytes currently served by Pocket-ID, so out-of-band changes show up as a diff.
        /// </summary>
        [Output("logoSha256")]
        public Output<string?> LogoSha256 { get; private set; } = null!;

        /// <summary>
        /// A URL from which Pocket-ID fetches the client logo. When unset, the logo is removed. It is not read back from the API. Mutually exclusive with logo (uploaded file).
        /// </summary>
        [Output("logoUrl")]
        public Output<string?> LogoUrl { get; private set; } = null!;

        /// <summary>
        /// The allowed post-logout redirect URLs.
        /// </summary>
        [Output("logoutCallbackUrls")]
        public Output<ImmutableArray<string>> LogoutCallbackUrls { get; private set; } = null!;

        /// <summary>
        /// The display name of the client (50 characters max).
        /// </summary>
        [Output("name")]
        public Output<string> Name { get; private set; } = null!;

        /// <summary>
        /// Whether PKCE is required for the client.
        /// </summary>
        [Output("pkceEnabled")]
        public Output<bool?> PkceEnabled { get; private set; } = null!;

        /// <summary>
        /// Whether PKCE is supported for this client.
        /// </summary>
        [Output("pkceSupported")]
        public Output<bool> PkceSupported { get; private set; } = null!;

        /// <summary>
        /// The refresh token lifetime in minutes. Pocket-ID's default applies when unset.
        /// </summary>
        [Output("refreshTokenDurationMinutes")]
        public Output<int?> RefreshTokenDurationMinutes { get; private set; } = null!;

        /// <summary>
        /// Whether the client must use pushed authorization requests (PAR).
        /// </summary>
        [Output("requiresPushedAuthorizationRequests")]
        public Output<bool?> RequiresPushedAuthorizationRequests { get; private set; } = null!;

        /// <summary>
        /// Whether users must re-authenticate on every authorization.
        /// </summary>
        [Output("requiresReauthentication")]
        public Output<bool?> RequiresReauthentication { get; private set; } = null!;

        /// <summary>
        /// Whether the consent screen is skipped for this client.
        /// </summary>
        [Output("skipConsent")]
        public Output<bool?> SkipConsent { get; private set; } = null!;


        /// <summary>
        /// Create a OidcClient resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public OidcClient(string name, OidcClientArgs args, CustomResourceOptions? options = null)
            : base("pocket-id:index:OidcClient", name, args ?? new OidcClientArgs(), MakeResourceOptions(options, ""))
        {
        }

        private OidcClient(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pocket-id:index:OidcClient", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/axnic/pulumi-pocket-id",
                ReplaceOnChanges =
                {
                    "clientId",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing OidcClient resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static OidcClient Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new OidcClient(name, id, options);
        }
    }

    public sealed class OidcClientArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The access token lifetime in minutes. Pocket-ID's default applies when unset.
        /// </summary>
        [Input("accessTokenDurationMinutes")]
        public Input<int>? AccessTokenDurationMinutes { get; set; }

        [Input("allowedUserGroupIds")]
        private InputList<string>? _allowedUserGroupIds;

        /// <summary>
        /// The IDs of the user groups allowed to use the client. Authoritative: the set is replaced on every update, and the client is restricted to these groups when the list is non-empty (unrestricted when empty).
        /// </summary>
        public InputList<string> AllowedUserGroupIds
        {
            get => _allowedUserGroupIds ?? (_allowedUserGroupIds = new InputList<string>());
            set => _allowedUserGroupIds = value;
        }

        /// <summary>
        /// The URL called for OIDC back-channel logout. Requires Pocket-ID v2.17.0 or later: older versions ignore the field, so the provider fails instead of silently dropping it.
        /// </summary>
        [Input("backchannelLogoutUrl")]
        public Input<string>? BackchannelLogoutUrl { get; set; }

        [Input("callbackUrls")]
        private InputList<string>? _callbackUrls;

        /// <summary>
        /// The allowed redirect URLs.
        /// </summary>
        public InputList<string> CallbackUrls
        {
            get => _callbackUrls ?? (_callbackUrls = new InputList<string>());
            set => _callbackUrls = value;
        }

        /// <summary>
        /// The ID of the client. Generated by Pocket-ID when unset. Changing it replaces the client.
        /// </summary>
        [Input("clientId")]
        public Input<string>? ClientId { get; set; }

        /// <summary>
        /// The credentials of the client managed here (federated identities).
        /// </summary>
        [Input("credentials")]
        public Input<Inputs.OidcClientCredentialsArgs>? Credentials { get; set; }

        /// <summary>
        /// The dark mode client logo (PNG, JPG or SVG) uploaded from a file, as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file and removing it deletes the logo. Mutually exclusive with darkLogoUrl. An asset cannot be read back: after an import it is empty and must be set in the program, which uploads the logo again if it differs from the served one.
        /// </summary>
        [Input("darkLogo")]
        public Input<AssetOrArchive>? DarkLogo { get; set; }

        /// <summary>
        /// A URL from which Pocket-ID fetches the dark mode logo. When unset, the dark logo is removed. It is not read back from the API. Mutually exclusive with darkLogo (uploaded file).
        /// </summary>
        [Input("darkLogoUrl")]
        public Input<string>? DarkLogoUrl { get; set; }

        /// <summary>
        /// A description of the client (150 characters max).
        /// </summary>
        [Input("description")]
        public Input<string>? Description { get; set; }

        /// <summary>
        /// Whether the client is public (no client secret, PKCE recommended).
        /// </summary>
        [Input("isPublic")]
        public Input<bool>? IsPublic { get; set; }

        /// <summary>
        /// The URL used to launch the application from the Pocket-ID dashboard.
        /// </summary>
        [Input("launchUrl")]
        public Input<string>? LaunchUrl { get; set; }

        /// <summary>
        /// The client logo (PNG, JPG or SVG) uploaded from a file, as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file and removing it deletes the logo. Mutually exclusive with logoUrl. An asset cannot be read back: after an import it is empty and must be set in the program, which uploads the logo again if it differs from the served one.
        /// </summary>
        [Input("logo")]
        public Input<AssetOrArchive>? Logo { get; set; }

        /// <summary>
        /// A URL from which Pocket-ID fetches the client logo. When unset, the logo is removed. It is not read back from the API. Mutually exclusive with logo (uploaded file).
        /// </summary>
        [Input("logoUrl")]
        public Input<string>? LogoUrl { get; set; }

        [Input("logoutCallbackUrls")]
        private InputList<string>? _logoutCallbackUrls;

        /// <summary>
        /// The allowed post-logout redirect URLs.
        /// </summary>
        public InputList<string> LogoutCallbackUrls
        {
            get => _logoutCallbackUrls ?? (_logoutCallbackUrls = new InputList<string>());
            set => _logoutCallbackUrls = value;
        }

        /// <summary>
        /// The display name of the client (50 characters max).
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Whether PKCE is required for the client.
        /// </summary>
        [Input("pkceEnabled")]
        public Input<bool>? PkceEnabled { get; set; }

        /// <summary>
        /// The refresh token lifetime in minutes. Pocket-ID's default applies when unset.
        /// </summary>
        [Input("refreshTokenDurationMinutes")]
        public Input<int>? RefreshTokenDurationMinutes { get; set; }

        /// <summary>
        /// Whether the client must use pushed authorization requests (PAR).
        /// </summary>
        [Input("requiresPushedAuthorizationRequests")]
        public Input<bool>? RequiresPushedAuthorizationRequests { get; set; }

        /// <summary>
        /// Whether users must re-authenticate on every authorization.
        /// </summary>
        [Input("requiresReauthentication")]
        public Input<bool>? RequiresReauthentication { get; set; }

        /// <summary>
        /// Whether the consent screen is skipped for this client.
        /// </summary>
        [Input("skipConsent")]
        public Input<bool>? SkipConsent { get; set; }

        public OidcClientArgs()
        {
        }
        public static new OidcClientArgs Empty => new OidcClientArgs();
    }
}
