// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId
{
    /// <summary>
    /// A SCIM service provider attached to an OIDC client. To import it, use the ID &lt;oidcClientId&gt;/&lt;serviceProviderId&gt;.
    /// </summary>
    [PocketIdResourceType("pocket-id:index:ScimServiceProvider")]
    public partial class ScimServiceProvider : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The creation date of the service provider.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The base URL of the SCIM endpoint.
        /// </summary>
        [Output("endpoint")]
        public Output<string> Endpoint { get; private set; } = null!;

        /// <summary>
        /// The date of the last synchronization, empty if it never ran.
        /// </summary>
        [Output("lastSyncedAt")]
        public Output<string> LastSyncedAt { get; private set; } = null!;

        /// <summary>
        /// The ID of the OIDC client the service provider belongs to. Changing it replaces the resource.
        /// </summary>
        [Output("oidcClientId")]
        public Output<string> OidcClientId { get; private set; } = null!;

        /// <summary>
        /// The bearer token used to authenticate against the SCIM endpoint. Never read back from the API: it is kept from the state and unset after an import.
        /// </summary>
        [Output("token")]
        public Output<string?> Token { get; private set; } = null!;


        /// <summary>
        /// Create a ScimServiceProvider resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public ScimServiceProvider(string name, ScimServiceProviderArgs args, CustomResourceOptions? options = null)
            : base("pocket-id:index:ScimServiceProvider", name, args ?? new ScimServiceProviderArgs(), MakeResourceOptions(options, ""))
        {
        }

        private ScimServiceProvider(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pocket-id:index:ScimServiceProvider", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/axnic/pulumi-pocket-id",
                AdditionalSecretOutputs =
                {
                    "token",
                },
                ReplaceOnChanges =
                {
                    "oidcClientId",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing ScimServiceProvider resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static ScimServiceProvider Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new ScimServiceProvider(name, id, options);
        }
    }

    public sealed class ScimServiceProviderArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The base URL of the SCIM endpoint.
        /// </summary>
        [Input("endpoint", required: true)]
        public Input<string> Endpoint { get; set; } = null!;

        /// <summary>
        /// The ID of the OIDC client the service provider belongs to. Changing it replaces the resource.
        /// </summary>
        [Input("oidcClientId", required: true)]
        public Input<string> OidcClientId { get; set; } = null!;

        [Input("token")]
        private Input<string>? _token;

        /// <summary>
        /// The bearer token used to authenticate against the SCIM endpoint. Never read back from the API: it is kept from the state and unset after an import.
        /// </summary>
        public Input<string>? Token
        {
            get => _token;
            set
            {
                var emptySecret = Output.CreateSecret(0);
                _token = Output.Tuple<Input<string>?, int>(value, emptySecret).Apply(t => t.Item1);
            }
        }

        public ScimServiceProviderArgs()
        {
        }
        public static new ScimServiceProviderArgs Empty => new ScimServiceProviderArgs();
    }
}
