// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId
{
    /// <summary>
    /// A Pocket-ID signup token that lets new users create their own account.
    /// </summary>
    [PocketIdResourceType("pocket-id:index:SignupToken")]
    public partial class SignupToken : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The RFC 3339 timestamp at which the token was created.
        /// </summary>
        [Output("createdAt")]
        public Output<string> CreatedAt { get; private set; } = null!;

        /// <summary>
        /// The RFC 3339 timestamp at which the token expires.
        /// </summary>
        [Output("expiresAt")]
        public Output<string> ExpiresAt { get; private set; } = null!;

        /// <summary>
        /// The secret signup token. It is captured at creation and carried in state; it is not read back from the API, so it is empty after an import.
        /// </summary>
        [Output("token")]
        public Output<string> Token { get; private set; } = null!;

        /// <summary>
        /// The lifetime of the token in seconds. Changing it replaces the resource.
        /// </summary>
        [Output("ttl")]
        public Output<int> Ttl { get; private set; } = null!;

        /// <summary>
        /// How many times the token can be used to sign up. Changing it replaces the resource.
        /// </summary>
        [Output("usageLimit")]
        public Output<int> UsageLimit { get; private set; } = null!;

        /// <summary>
        /// The IDs of the groups users signing up with this token join. Changing them replaces the resource.
        /// </summary>
        [Output("userGroupIds")]
        public Output<ImmutableArray<string>> UserGroupIds { get; private set; } = null!;


        /// <summary>
        /// Create a SignupToken resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public SignupToken(string name, SignupTokenArgs args, CustomResourceOptions? options = null)
            : base("pocket-id:index:SignupToken", name, args ?? new SignupTokenArgs(), MakeResourceOptions(options, ""))
        {
        }

        private SignupToken(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pocket-id:index:SignupToken", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/axnic/pulumi-pocket-id",
                AdditionalSecretOutputs =
                {
                    "token",
                },
                ReplaceOnChanges =
                {
                    "ttl",
                    "usageLimit",
                    "userGroupIds[*]",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing SignupToken resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static SignupToken Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new SignupToken(name, id, options);
        }
    }

    public sealed class SignupTokenArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// The lifetime of the token in seconds. Changing it replaces the resource.
        /// </summary>
        [Input("ttl", required: true)]
        public Input<int> Ttl { get; set; } = null!;

        /// <summary>
        /// How many times the token can be used to sign up. Changing it replaces the resource.
        /// </summary>
        [Input("usageLimit", required: true)]
        public Input<int> UsageLimit { get; set; } = null!;

        [Input("userGroupIds")]
        private InputList<string>? _userGroupIds;

        /// <summary>
        /// The IDs of the groups users signing up with this token join. Changing them replaces the resource.
        /// </summary>
        public InputList<string> UserGroupIds
        {
            get => _userGroupIds ?? (_userGroupIds = new InputList<string>());
            set => _userGroupIds = value;
        }

        public SignupTokenArgs()
        {
        }
        public static new SignupTokenArgs Empty => new SignupTokenArgs();
    }
}
