// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId
{
    /// <summary>
    /// The authoritative set of custom claims of a user group. Destroying the resource removes every custom claim from the group.
    /// </summary>
    [PocketIdResourceType("pocket-id:index:UserGroupCustomClaims")]
    public partial class UserGroupCustomClaims : global::Pulumi.CustomResource
    {
        /// <summary>
        /// The custom claims of the group, as key/value pairs. The set is authoritative: claims not listed are removed from the group.
        /// </summary>
        [Output("claims")]
        public Output<ImmutableDictionary<string, string>> Claims { get; private set; } = null!;

        /// <summary>
        /// The ID of the user group. Changing it replaces the resource.
        /// </summary>
        [Output("userGroupId")]
        public Output<string> UserGroupId { get; private set; } = null!;


        /// <summary>
        /// Create a UserGroupCustomClaims resource with the given unique name, arguments, and options.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resource</param>
        /// <param name="args">The arguments used to populate this resource's properties</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public UserGroupCustomClaims(string name, UserGroupCustomClaimsArgs args, CustomResourceOptions? options = null)
            : base("pocket-id:index:UserGroupCustomClaims", name, args ?? new UserGroupCustomClaimsArgs(), MakeResourceOptions(options, ""))
        {
        }

        private UserGroupCustomClaims(string name, Input<string> id, CustomResourceOptions? options = null)
            : base("pocket-id:index:UserGroupCustomClaims", name, null, MakeResourceOptions(options, id))
        {
        }

        private static CustomResourceOptions MakeResourceOptions(CustomResourceOptions? options, Input<string>? id)
        {
            var defaultOptions = new CustomResourceOptions
            {
                Version = Utilities.Version,
                PluginDownloadURL = "github://api.github.com/axnic/pulumi-pocket-id",
                ReplaceOnChanges =
                {
                    "userGroupId",
                },
            };
            var merged = CustomResourceOptions.Merge(defaultOptions, options);
            // Override the ID if one was specified for consistency with other language SDKs.
            merged.Id = id ?? merged.Id;
            return merged;
        }
        /// <summary>
        /// Get an existing UserGroupCustomClaims resource's state with the given name, ID, and optional extra
        /// properties used to qualify the lookup.
        /// </summary>
        ///
        /// <param name="name">The unique name of the resulting resource.</param>
        /// <param name="id">The unique provider ID of the resource to lookup.</param>
        /// <param name="options">A bag of options that control this resource's behavior</param>
        public static UserGroupCustomClaims Get(string name, Input<string> id, CustomResourceOptions? options = null)
        {
            return new UserGroupCustomClaims(name, id, options);
        }
    }

    public sealed class UserGroupCustomClaimsArgs : global::Pulumi.ResourceArgs
    {
        [Input("claims", required: true)]
        private InputMap<string>? _claims;

        /// <summary>
        /// The custom claims of the group, as key/value pairs. The set is authoritative: claims not listed are removed from the group.
        /// </summary>
        public InputMap<string> Claims
        {
            get => _claims ?? (_claims = new InputMap<string>());
            set => _claims = value;
        }

        /// <summary>
        /// The ID of the user group. Changing it replaces the resource.
        /// </summary>
        [Input("userGroupId", required: true)]
        public Input<string> UserGroupId { get; set; } = null!;

        public UserGroupCustomClaimsArgs()
        {
        }
        public static new UserGroupCustomClaimsArgs Empty => new UserGroupCustomClaimsArgs();
    }
}
