# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from .custom_claims import *
from .oidc_client import *
from .provider import *
from .user import *
from .user_group import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_pocket_id.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_pocket_id.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "pocket-id",
  "mod": "index",
  "fqn": "pulumi_pocket_id",
  "classes": {
   "pocket-id:index:CustomClaims": "CustomClaims",
   "pocket-id:index:OidcClient": "OidcClient",
   "pocket-id:index:User": "User",
   "pocket-id:index:UserGroup": "UserGroup"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "pocket-id",
  "token": "pulumi:providers:pocket-id",
  "fqn": "pulumi_pocket_id",
  "class": "Provider"
 }
]
"""
)
