# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
from . import _utilities
import typing
# Export this package's modules as members:
from ._enums import *
from .api import *
from .api_client_grant import *
from .application_configuration import *
from .application_image import *
from .get_oidc_client import *
from .get_open_id_configuration import *
from .get_user import *
from .get_user_group import *
from .oidc_client import *
from .oidc_client_secret import *
from .provider import *
from .scim_service_provider import *
from .signup_token import *
from .user import *
from .user_custom_claims import *
from .user_group import *
from .user_group_custom_claims import *
from .user_group_members import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_pocket_id.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_pocket_id.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "pocket-id",
  "mod": "index",
  "fqn": "pulumi_pocket_id",
  "classes": {
   "pocket-id:index:Api": "Api",
   "pocket-id:index:ApiClientGrant": "ApiClientGrant",
   "pocket-id:index:ApplicationConfiguration": "ApplicationConfiguration",
   "pocket-id:index:ApplicationImage": "ApplicationImage",
   "pocket-id:index:OidcClient": "OidcClient",
   "pocket-id:index:OidcClientSecret": "OidcClientSecret",
   "pocket-id:index:ScimServiceProvider": "ScimServiceProvider",
   "pocket-id:index:SignupToken": "SignupToken",
   "pocket-id:index:User": "User",
   "pocket-id:index:UserCustomClaims": "UserCustomClaims",
   "pocket-id:index:UserGroup": "UserGroup",
   "pocket-id:index:UserGroupCustomClaims": "UserGroupCustomClaims",
   "pocket-id:index:UserGroupMembers": "UserGroupMembers"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "pocket-id",
  "token": "pulumi:providers:pocket-id",
  "fqn": "pulumi_pocket_id",
  "class": "Provider"
 }
]
"""
)
