# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import pulumi
from enum import Enum

__all__ = [
    'ApplicationImageType',
]


@pulumi.type_token("pocket-id:index:ApplicationImageType")
class ApplicationImageType(_builtins.str, Enum):
    LOGO = "logo"
    """
    The light mode application logo.
    """
    DARK_LOGO = "darkLogo"
    """
    The dark mode application logo.
    """
    FAVICON = "favicon"
    """
    The favicon. It cannot be deleted.
    """
    BACKGROUND = "background"
    """
    The login page background.
    """
    EMAIL = "email"
    """
    The image used in e-mails. It cannot be deleted.
    """
    DEFAULT_PROFILE_PICTURE = "defaultProfilePicture"
    """
    The default profile picture of users.
    """
