# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['ApiArgs', 'Api']

@pulumi.input_type
class ApiArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 resource: pulumi.Input[_builtins.str],
                 cimd_access: pulumi.Input[Optional['ApiCimdAccessArgs']] = None,
                 permissions: pulumi.Input[Optional[Sequence[pulumi.Input['ApiPermissionArgsArgs']]]] = None):
        """
        The set of arguments for constructing a Api resource.

        :param pulumi.Input[_builtins.str] name: The display name of the API.
        :param pulumi.Input[_builtins.str] resource: The resource identifier (audience) of the API, usually a URL. Changing it replaces the API.
        :param pulumi.Input['ApiCimdAccessArgs'] cimd_access: The access granted to clients registered through a Client ID Metadata Document. When set it is authoritative; when omitted the server value is left untouched.
        :param pulumi.Input[Sequence[pulumi.Input['ApiPermissionArgsArgs']]] permissions: The permissions of the API. The list is authoritative: permissions not listed here are removed.
        """
        pulumi.set(__self__, "name", name)
        pulumi.set(__self__, "resource", resource)
        if cimd_access is not None:
            pulumi.set(__self__, "cimd_access", cimd_access)
        if permissions is not None:
            pulumi.set(__self__, "permissions", permissions)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The display name of the API.
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter
    def resource(self) -> pulumi.Input[_builtins.str]:
        """
        The resource identifier (audience) of the API, usually a URL. Changing it replaces the API.
        """
        return pulumi.get(self, "resource")

    @resource.setter
    def resource(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "resource", value)

    @_builtins.property
    @pulumi.getter(name="cimdAccess")
    def cimd_access(self) -> pulumi.Input[Optional['ApiCimdAccessArgs']]:
        """
        The access granted to clients registered through a Client ID Metadata Document. When set it is authoritative; when omitted the server value is left untouched.
        """
        return pulumi.get(self, "cimd_access")

    @cimd_access.setter
    def cimd_access(self, value: pulumi.Input[Optional['ApiCimdAccessArgs']]):
        pulumi.set(self, "cimd_access", value)

    @_builtins.property
    @pulumi.getter
    def permissions(self) -> pulumi.Input[Optional[Sequence[pulumi.Input['ApiPermissionArgsArgs']]]]:
        """
        The permissions of the API. The list is authoritative: permissions not listed here are removed.
        """
        return pulumi.get(self, "permissions")

    @permissions.setter
    def permissions(self, value: pulumi.Input[Optional[Sequence[pulumi.Input['ApiPermissionArgsArgs']]]]):
        pulumi.set(self, "permissions", value)


@pulumi.type_token("pocket-id:index:Api")
class Api(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cimd_access: pulumi.Input[Optional[Union['ApiCimdAccessArgs', 'ApiCimdAccessArgsDict', 'outputs.ApiCimdAccess']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 permissions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['ApiPermissionArgsArgs', 'ApiPermissionArgsArgsDict']]]]] = None,
                 resource: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A Pocket-ID API (OAuth resource server) and its permissions.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union['ApiCimdAccessArgs', 'ApiCimdAccessArgsDict', 'outputs.ApiCimdAccess']] cimd_access: The access granted to clients registered through a Client ID Metadata Document. When set it is authoritative; when omitted the server value is left untouched.
        :param pulumi.Input[_builtins.str] name: The display name of the API.
        :param pulumi.Input[Sequence[pulumi.Input[Union['ApiPermissionArgsArgs', 'ApiPermissionArgsArgsDict']]]] permissions: The permissions of the API. The list is authoritative: permissions not listed here are removed.
        :param pulumi.Input[_builtins.str] resource: The resource identifier (audience) of the API, usually a URL. Changing it replaces the API.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ApiArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A Pocket-ID API (OAuth resource server) and its permissions.

        :param str resource_name: The name of the resource.
        :param ApiArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ApiArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 cimd_access: pulumi.Input[Optional[Union['ApiCimdAccessArgs', 'ApiCimdAccessArgsDict', 'outputs.ApiCimdAccess']]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 permissions: pulumi.Input[Optional[Sequence[pulumi.Input[Union['ApiPermissionArgsArgs', 'ApiPermissionArgsArgsDict']]]]] = None,
                 resource: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ApiArgs.__new__(ApiArgs)

            __props__.__dict__["cimd_access"] = cimd_access
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["permissions"] = permissions
            if resource is None and not opts.urn:
                raise TypeError("Missing required property 'resource'")
            __props__.__dict__["resource"] = resource
            __props__.__dict__["created_at"] = None
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["resource"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(Api, __self__).__init__(
            'pocket-id:index:Api',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'Api':
        """
        Get an existing Api resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ApiArgs.__new__(ApiArgs)

        __props__.__dict__["cimd_access"] = None
        __props__.__dict__["created_at"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["permissions"] = None
        __props__.__dict__["resource"] = None
        return Api(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="cimdAccess")
    def cimd_access(self) -> pulumi.Output[Optional['outputs.ApiCimdAccess']]:
        """
        The access granted to clients registered through a Client ID Metadata Document, if managed.
        """
        return pulumi.get(self, "cimd_access")

    @_builtins.property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> pulumi.Output[_builtins.str]:
        """
        The RFC 3339 timestamp at which the API was created.
        """
        return pulumi.get(self, "created_at")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The display name of the API.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def permissions(self) -> pulumi.Output[Sequence['outputs.ApiPermissionState']]:
        """
        The permissions of the API, including their Pocket-ID identifiers.
        """
        return pulumi.get(self, "permissions")

    @_builtins.property
    @pulumi.getter
    def resource(self) -> pulumi.Output[_builtins.str]:
        """
        The resource identifier (audience) of the API.
        """
        return pulumi.get(self, "resource")

