# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['ApplicationConfigurationArgs', 'ApplicationConfiguration']

@pulumi.input_type
class ApplicationConfigurationArgs:
    def __init__(__self__, *,
                 accent_color: pulumi.Input[Optional[_builtins.str]] = None,
                 allow_own_account_edit: pulumi.Input[Optional[_builtins.bool]] = None,
                 allow_user_signups: pulumi.Input[Optional[_builtins.str]] = None,
                 app_name: pulumi.Input[Optional[_builtins.str]] = None,
                 auto_create_oidc_client_secret: pulumi.Input[Optional[_builtins.bool]] = None,
                 cimd_url_allowlist: pulumi.Input[Optional[_builtins.str]] = None,
                 disable_animations: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_api_key_expiration_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_login_notification_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_one_time_access_as_admin_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_one_time_access_as_unauthenticated_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_verification_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 emails_verified: pulumi.Input[Optional[_builtins.bool]] = None,
                 home_page_url: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_admin_group_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_group_member: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_group_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_group_unique_identifier: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_email: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_first_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_last_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_profile_picture: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_unique_identifier: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_username: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_base: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_bind_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_bind_password: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 ldap_skip_cert_verify: pulumi.Input[Optional[_builtins.bool]] = None,
                 ldap_soft_delete_users: pulumi.Input[Optional[_builtins.bool]] = None,
                 ldap_url: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_user_group_search_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_user_search_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 require_user_email: pulumi.Input[Optional[_builtins.bool]] = None,
                 session_duration: pulumi.Input[Optional[_builtins.int]] = None,
                 signup_default_custom_claims: pulumi.Input[Optional[_builtins.str]] = None,
                 signup_default_user_group_ids: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_from: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_host: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_password: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_port: pulumi.Input[Optional[_builtins.int]] = None,
                 smtp_skip_cert_verify: pulumi.Input[Optional[_builtins.bool]] = None,
                 smtp_tls: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_user: pulumi.Input[Optional[_builtins.str]] = None,
                 webauthn_allow_synced_passkeys: pulumi.Input[Optional[_builtins.bool]] = None,
                 webauthn_authenticator_attachment: pulumi.Input[Optional[_builtins.str]] = None,
                 webauthn_user_verification: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a ApplicationConfiguration resource.

        :param pulumi.Input[_builtins.str] accent_color: The UI accent color, as "default" or a CSS color value.
        :param pulumi.Input[_builtins.bool] allow_own_account_edit: Whether users may edit their own account details.
        :param pulumi.Input[_builtins.str] allow_user_signups: Who may sign up by themselves: "disabled", "withToken" or "open".
        :param pulumi.Input[_builtins.str] app_name: The application name shown in the UI and in emails (1 to 30 characters).
        :param pulumi.Input[_builtins.bool] auto_create_oidc_client_secret: Whether a secret is generated automatically when an OIDC client is created.
        :param pulumi.Input[_builtins.str] cimd_url_allowlist: The allowlist of URLs accepted as OIDC client metadata documents (CIMD), in the format Pocket-ID expects.
        :param pulumi.Input[_builtins.bool] disable_animations: Whether to disable the UI animations.
        :param pulumi.Input[_builtins.bool] email_api_key_expiration_enabled: Whether an email is sent when an API key is about to expire.
        :param pulumi.Input[_builtins.bool] email_login_notification_enabled: Whether an email is sent when a user signs in from a new device.
        :param pulumi.Input[_builtins.bool] email_one_time_access_as_admin_enabled: Whether administrators may send one-time access links by email.
        :param pulumi.Input[_builtins.bool] email_one_time_access_as_unauthenticated_enabled: Whether unauthenticated users may request a one-time access link by email.
        :param pulumi.Input[_builtins.bool] email_verification_enabled: Whether users must verify their email address.
        :param pulumi.Input[_builtins.bool] emails_verified: Whether emails are considered verified by default.
        :param pulumi.Input[_builtins.str] home_page_url: The path of the page users land on after signing in, e.g. "/settings/account".
        :param pulumi.Input[_builtins.str] ldap_admin_group_name: The name of the LDAP group whose members become Pocket-ID administrators.
        :param pulumi.Input[_builtins.str] ldap_attribute_group_member: The LDAP attribute listing the members of a group.
        :param pulumi.Input[_builtins.str] ldap_attribute_group_name: The LDAP attribute mapped to the group name.
        :param pulumi.Input[_builtins.str] ldap_attribute_group_unique_identifier: The LDAP attribute holding the unique identifier of a group.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_display_name: The LDAP attribute mapped to the display name.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_email: The LDAP attribute mapped to the email address.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_first_name: The LDAP attribute mapped to the first name.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_last_name: The LDAP attribute mapped to the last name.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_profile_picture: The LDAP attribute mapped to the profile picture.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_unique_identifier: The LDAP attribute holding the unique identifier of a user.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_username: The LDAP attribute mapped to the user name.
        :param pulumi.Input[_builtins.str] ldap_base: The LDAP base DN under which users and groups are searched.
        :param pulumi.Input[_builtins.str] ldap_bind_dn: The distinguished name used to bind to the LDAP server.
        :param pulumi.Input[_builtins.str] ldap_bind_password: The LDAP bind password. It is a secret and is never read back from Pocket-ID: the value in state is the one from the program, and it is empty after an import.
        :param pulumi.Input[_builtins.bool] ldap_enabled: Whether LDAP synchronization is enabled.
        :param pulumi.Input[_builtins.bool] ldap_skip_cert_verify: Whether to skip the verification of the LDAP server certificate.
        :param pulumi.Input[_builtins.bool] ldap_soft_delete_users: Whether users removed from LDAP are disabled instead of deleted.
        :param pulumi.Input[_builtins.str] ldap_url: The LDAP server URL, e.g. "ldaps://ldap.example.com:636".
        :param pulumi.Input[_builtins.str] ldap_user_group_search_filter: The LDAP filter selecting groups, e.g. "(objectClass=groupOfNames)".
        :param pulumi.Input[_builtins.str] ldap_user_search_filter: The LDAP filter selecting users, e.g. "(objectClass=person)".
        :param pulumi.Input[_builtins.bool] require_user_email: Whether an email address is required for every user.
        :param pulumi.Input[_builtins.int] session_duration: The session lifetime, in minutes.
        :param pulumi.Input[_builtins.str] signup_default_custom_claims: The custom claims given to new users, as the JSON array string Pocket-ID expects.
        :param pulumi.Input[_builtins.str] signup_default_user_group_ids: The IDs of the user groups new users join, as the JSON array string Pocket-ID expects.
        :param pulumi.Input[_builtins.str] smtp_from: The sender address of outgoing emails.
        :param pulumi.Input[_builtins.str] smtp_host: The SMTP server host name.
        :param pulumi.Input[_builtins.str] smtp_password: The SMTP password. It is a secret and is never read back from Pocket-ID: the value in state is the one from the program, and it is empty after an import.
        :param pulumi.Input[_builtins.int] smtp_port: The SMTP server port.
        :param pulumi.Input[_builtins.bool] smtp_skip_cert_verify: Whether to skip the verification of the SMTP server certificate.
        :param pulumi.Input[_builtins.str] smtp_tls: The SMTP transport security: "none", "starttls" or "tls".
        :param pulumi.Input[_builtins.str] smtp_user: The SMTP user name.
        :param pulumi.Input[_builtins.bool] webauthn_allow_synced_passkeys: Whether passkeys synced between devices are accepted.
        :param pulumi.Input[_builtins.str] webauthn_authenticator_attachment: The accepted authenticator attachment: "any", "platform" or "cross-platform".
        :param pulumi.Input[_builtins.str] webauthn_user_verification: The user verification requirement: "required" or "preferred".
        """
        if accent_color is not None:
            pulumi.set(__self__, "accent_color", accent_color)
        if allow_own_account_edit is not None:
            pulumi.set(__self__, "allow_own_account_edit", allow_own_account_edit)
        if allow_user_signups is not None:
            pulumi.set(__self__, "allow_user_signups", allow_user_signups)
        if app_name is not None:
            pulumi.set(__self__, "app_name", app_name)
        if auto_create_oidc_client_secret is not None:
            pulumi.set(__self__, "auto_create_oidc_client_secret", auto_create_oidc_client_secret)
        if cimd_url_allowlist is not None:
            pulumi.set(__self__, "cimd_url_allowlist", cimd_url_allowlist)
        if disable_animations is not None:
            pulumi.set(__self__, "disable_animations", disable_animations)
        if email_api_key_expiration_enabled is not None:
            pulumi.set(__self__, "email_api_key_expiration_enabled", email_api_key_expiration_enabled)
        if email_login_notification_enabled is not None:
            pulumi.set(__self__, "email_login_notification_enabled", email_login_notification_enabled)
        if email_one_time_access_as_admin_enabled is not None:
            pulumi.set(__self__, "email_one_time_access_as_admin_enabled", email_one_time_access_as_admin_enabled)
        if email_one_time_access_as_unauthenticated_enabled is not None:
            pulumi.set(__self__, "email_one_time_access_as_unauthenticated_enabled", email_one_time_access_as_unauthenticated_enabled)
        if email_verification_enabled is not None:
            pulumi.set(__self__, "email_verification_enabled", email_verification_enabled)
        if emails_verified is not None:
            pulumi.set(__self__, "emails_verified", emails_verified)
        if home_page_url is not None:
            pulumi.set(__self__, "home_page_url", home_page_url)
        if ldap_admin_group_name is not None:
            pulumi.set(__self__, "ldap_admin_group_name", ldap_admin_group_name)
        if ldap_attribute_group_member is not None:
            pulumi.set(__self__, "ldap_attribute_group_member", ldap_attribute_group_member)
        if ldap_attribute_group_name is not None:
            pulumi.set(__self__, "ldap_attribute_group_name", ldap_attribute_group_name)
        if ldap_attribute_group_unique_identifier is not None:
            pulumi.set(__self__, "ldap_attribute_group_unique_identifier", ldap_attribute_group_unique_identifier)
        if ldap_attribute_user_display_name is not None:
            pulumi.set(__self__, "ldap_attribute_user_display_name", ldap_attribute_user_display_name)
        if ldap_attribute_user_email is not None:
            pulumi.set(__self__, "ldap_attribute_user_email", ldap_attribute_user_email)
        if ldap_attribute_user_first_name is not None:
            pulumi.set(__self__, "ldap_attribute_user_first_name", ldap_attribute_user_first_name)
        if ldap_attribute_user_last_name is not None:
            pulumi.set(__self__, "ldap_attribute_user_last_name", ldap_attribute_user_last_name)
        if ldap_attribute_user_profile_picture is not None:
            pulumi.set(__self__, "ldap_attribute_user_profile_picture", ldap_attribute_user_profile_picture)
        if ldap_attribute_user_unique_identifier is not None:
            pulumi.set(__self__, "ldap_attribute_user_unique_identifier", ldap_attribute_user_unique_identifier)
        if ldap_attribute_user_username is not None:
            pulumi.set(__self__, "ldap_attribute_user_username", ldap_attribute_user_username)
        if ldap_base is not None:
            pulumi.set(__self__, "ldap_base", ldap_base)
        if ldap_bind_dn is not None:
            pulumi.set(__self__, "ldap_bind_dn", ldap_bind_dn)
        if ldap_bind_password is not None:
            pulumi.set(__self__, "ldap_bind_password", ldap_bind_password)
        if ldap_enabled is not None:
            pulumi.set(__self__, "ldap_enabled", ldap_enabled)
        if ldap_skip_cert_verify is not None:
            pulumi.set(__self__, "ldap_skip_cert_verify", ldap_skip_cert_verify)
        if ldap_soft_delete_users is not None:
            pulumi.set(__self__, "ldap_soft_delete_users", ldap_soft_delete_users)
        if ldap_url is not None:
            pulumi.set(__self__, "ldap_url", ldap_url)
        if ldap_user_group_search_filter is not None:
            pulumi.set(__self__, "ldap_user_group_search_filter", ldap_user_group_search_filter)
        if ldap_user_search_filter is not None:
            pulumi.set(__self__, "ldap_user_search_filter", ldap_user_search_filter)
        if require_user_email is not None:
            pulumi.set(__self__, "require_user_email", require_user_email)
        if session_duration is not None:
            pulumi.set(__self__, "session_duration", session_duration)
        if signup_default_custom_claims is not None:
            pulumi.set(__self__, "signup_default_custom_claims", signup_default_custom_claims)
        if signup_default_user_group_ids is not None:
            pulumi.set(__self__, "signup_default_user_group_ids", signup_default_user_group_ids)
        if smtp_from is not None:
            pulumi.set(__self__, "smtp_from", smtp_from)
        if smtp_host is not None:
            pulumi.set(__self__, "smtp_host", smtp_host)
        if smtp_password is not None:
            pulumi.set(__self__, "smtp_password", smtp_password)
        if smtp_port is not None:
            pulumi.set(__self__, "smtp_port", smtp_port)
        if smtp_skip_cert_verify is not None:
            pulumi.set(__self__, "smtp_skip_cert_verify", smtp_skip_cert_verify)
        if smtp_tls is not None:
            pulumi.set(__self__, "smtp_tls", smtp_tls)
        if smtp_user is not None:
            pulumi.set(__self__, "smtp_user", smtp_user)
        if webauthn_allow_synced_passkeys is not None:
            pulumi.set(__self__, "webauthn_allow_synced_passkeys", webauthn_allow_synced_passkeys)
        if webauthn_authenticator_attachment is not None:
            pulumi.set(__self__, "webauthn_authenticator_attachment", webauthn_authenticator_attachment)
        if webauthn_user_verification is not None:
            pulumi.set(__self__, "webauthn_user_verification", webauthn_user_verification)

    @_builtins.property
    @pulumi.getter(name="accentColor")
    def accent_color(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The UI accent color, as "default" or a CSS color value.
        """
        return pulumi.get(self, "accent_color")

    @accent_color.setter
    def accent_color(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "accent_color", value)

    @_builtins.property
    @pulumi.getter(name="allowOwnAccountEdit")
    def allow_own_account_edit(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether users may edit their own account details.
        """
        return pulumi.get(self, "allow_own_account_edit")

    @allow_own_account_edit.setter
    def allow_own_account_edit(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "allow_own_account_edit", value)

    @_builtins.property
    @pulumi.getter(name="allowUserSignups")
    def allow_user_signups(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        Who may sign up by themselves: "disabled", "withToken" or "open".
        """
        return pulumi.get(self, "allow_user_signups")

    @allow_user_signups.setter
    def allow_user_signups(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "allow_user_signups", value)

    @_builtins.property
    @pulumi.getter(name="appName")
    def app_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The application name shown in the UI and in emails (1 to 30 characters).
        """
        return pulumi.get(self, "app_name")

    @app_name.setter
    def app_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "app_name", value)

    @_builtins.property
    @pulumi.getter(name="autoCreateOidcClientSecret")
    def auto_create_oidc_client_secret(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether a secret is generated automatically when an OIDC client is created.
        """
        return pulumi.get(self, "auto_create_oidc_client_secret")

    @auto_create_oidc_client_secret.setter
    def auto_create_oidc_client_secret(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "auto_create_oidc_client_secret", value)

    @_builtins.property
    @pulumi.getter(name="cimdUrlAllowlist")
    def cimd_url_allowlist(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The allowlist of URLs accepted as OIDC client metadata documents (CIMD), in the format Pocket-ID expects.
        """
        return pulumi.get(self, "cimd_url_allowlist")

    @cimd_url_allowlist.setter
    def cimd_url_allowlist(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "cimd_url_allowlist", value)

    @_builtins.property
    @pulumi.getter(name="disableAnimations")
    def disable_animations(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to disable the UI animations.
        """
        return pulumi.get(self, "disable_animations")

    @disable_animations.setter
    def disable_animations(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "disable_animations", value)

    @_builtins.property
    @pulumi.getter(name="emailApiKeyExpirationEnabled")
    def email_api_key_expiration_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether an email is sent when an API key is about to expire.
        """
        return pulumi.get(self, "email_api_key_expiration_enabled")

    @email_api_key_expiration_enabled.setter
    def email_api_key_expiration_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "email_api_key_expiration_enabled", value)

    @_builtins.property
    @pulumi.getter(name="emailLoginNotificationEnabled")
    def email_login_notification_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether an email is sent when a user signs in from a new device.
        """
        return pulumi.get(self, "email_login_notification_enabled")

    @email_login_notification_enabled.setter
    def email_login_notification_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "email_login_notification_enabled", value)

    @_builtins.property
    @pulumi.getter(name="emailOneTimeAccessAsAdminEnabled")
    def email_one_time_access_as_admin_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether administrators may send one-time access links by email.
        """
        return pulumi.get(self, "email_one_time_access_as_admin_enabled")

    @email_one_time_access_as_admin_enabled.setter
    def email_one_time_access_as_admin_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "email_one_time_access_as_admin_enabled", value)

    @_builtins.property
    @pulumi.getter(name="emailOneTimeAccessAsUnauthenticatedEnabled")
    def email_one_time_access_as_unauthenticated_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether unauthenticated users may request a one-time access link by email.
        """
        return pulumi.get(self, "email_one_time_access_as_unauthenticated_enabled")

    @email_one_time_access_as_unauthenticated_enabled.setter
    def email_one_time_access_as_unauthenticated_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "email_one_time_access_as_unauthenticated_enabled", value)

    @_builtins.property
    @pulumi.getter(name="emailVerificationEnabled")
    def email_verification_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether users must verify their email address.
        """
        return pulumi.get(self, "email_verification_enabled")

    @email_verification_enabled.setter
    def email_verification_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "email_verification_enabled", value)

    @_builtins.property
    @pulumi.getter(name="emailsVerified")
    def emails_verified(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether emails are considered verified by default.
        """
        return pulumi.get(self, "emails_verified")

    @emails_verified.setter
    def emails_verified(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "emails_verified", value)

    @_builtins.property
    @pulumi.getter(name="homePageUrl")
    def home_page_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The path of the page users land on after signing in, e.g. "/settings/account".
        """
        return pulumi.get(self, "home_page_url")

    @home_page_url.setter
    def home_page_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "home_page_url", value)

    @_builtins.property
    @pulumi.getter(name="ldapAdminGroupName")
    def ldap_admin_group_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name of the LDAP group whose members become Pocket-ID administrators.
        """
        return pulumi.get(self, "ldap_admin_group_name")

    @ldap_admin_group_name.setter
    def ldap_admin_group_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_admin_group_name", value)

    @_builtins.property
    @pulumi.getter(name="ldapAttributeGroupMember")
    def ldap_attribute_group_member(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP attribute listing the members of a group.
        """
        return pulumi.get(self, "ldap_attribute_group_member")

    @ldap_attribute_group_member.setter
    def ldap_attribute_group_member(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_attribute_group_member", value)

    @_builtins.property
    @pulumi.getter(name="ldapAttributeGroupName")
    def ldap_attribute_group_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the group name.
        """
        return pulumi.get(self, "ldap_attribute_group_name")

    @ldap_attribute_group_name.setter
    def ldap_attribute_group_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_attribute_group_name", value)

    @_builtins.property
    @pulumi.getter(name="ldapAttributeGroupUniqueIdentifier")
    def ldap_attribute_group_unique_identifier(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP attribute holding the unique identifier of a group.
        """
        return pulumi.get(self, "ldap_attribute_group_unique_identifier")

    @ldap_attribute_group_unique_identifier.setter
    def ldap_attribute_group_unique_identifier(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_attribute_group_unique_identifier", value)

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserDisplayName")
    def ldap_attribute_user_display_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the display name.
        """
        return pulumi.get(self, "ldap_attribute_user_display_name")

    @ldap_attribute_user_display_name.setter
    def ldap_attribute_user_display_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_attribute_user_display_name", value)

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserEmail")
    def ldap_attribute_user_email(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the email address.
        """
        return pulumi.get(self, "ldap_attribute_user_email")

    @ldap_attribute_user_email.setter
    def ldap_attribute_user_email(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_attribute_user_email", value)

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserFirstName")
    def ldap_attribute_user_first_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the first name.
        """
        return pulumi.get(self, "ldap_attribute_user_first_name")

    @ldap_attribute_user_first_name.setter
    def ldap_attribute_user_first_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_attribute_user_first_name", value)

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserLastName")
    def ldap_attribute_user_last_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the last name.
        """
        return pulumi.get(self, "ldap_attribute_user_last_name")

    @ldap_attribute_user_last_name.setter
    def ldap_attribute_user_last_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_attribute_user_last_name", value)

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserProfilePicture")
    def ldap_attribute_user_profile_picture(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the profile picture.
        """
        return pulumi.get(self, "ldap_attribute_user_profile_picture")

    @ldap_attribute_user_profile_picture.setter
    def ldap_attribute_user_profile_picture(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_attribute_user_profile_picture", value)

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserUniqueIdentifier")
    def ldap_attribute_user_unique_identifier(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP attribute holding the unique identifier of a user.
        """
        return pulumi.get(self, "ldap_attribute_user_unique_identifier")

    @ldap_attribute_user_unique_identifier.setter
    def ldap_attribute_user_unique_identifier(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_attribute_user_unique_identifier", value)

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserUsername")
    def ldap_attribute_user_username(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the user name.
        """
        return pulumi.get(self, "ldap_attribute_user_username")

    @ldap_attribute_user_username.setter
    def ldap_attribute_user_username(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_attribute_user_username", value)

    @_builtins.property
    @pulumi.getter(name="ldapBase")
    def ldap_base(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP base DN under which users and groups are searched.
        """
        return pulumi.get(self, "ldap_base")

    @ldap_base.setter
    def ldap_base(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_base", value)

    @_builtins.property
    @pulumi.getter(name="ldapBindDn")
    def ldap_bind_dn(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The distinguished name used to bind to the LDAP server.
        """
        return pulumi.get(self, "ldap_bind_dn")

    @ldap_bind_dn.setter
    def ldap_bind_dn(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_bind_dn", value)

    @_builtins.property
    @pulumi.getter(name="ldapBindPassword")
    def ldap_bind_password(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP bind password. It is a secret and is never read back from Pocket-ID: the value in state is the one from the program, and it is empty after an import.
        """
        return pulumi.get(self, "ldap_bind_password")

    @ldap_bind_password.setter
    def ldap_bind_password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_bind_password", value)

    @_builtins.property
    @pulumi.getter(name="ldapEnabled")
    def ldap_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether LDAP synchronization is enabled.
        """
        return pulumi.get(self, "ldap_enabled")

    @ldap_enabled.setter
    def ldap_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "ldap_enabled", value)

    @_builtins.property
    @pulumi.getter(name="ldapSkipCertVerify")
    def ldap_skip_cert_verify(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to skip the verification of the LDAP server certificate.
        """
        return pulumi.get(self, "ldap_skip_cert_verify")

    @ldap_skip_cert_verify.setter
    def ldap_skip_cert_verify(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "ldap_skip_cert_verify", value)

    @_builtins.property
    @pulumi.getter(name="ldapSoftDeleteUsers")
    def ldap_soft_delete_users(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether users removed from LDAP are disabled instead of deleted.
        """
        return pulumi.get(self, "ldap_soft_delete_users")

    @ldap_soft_delete_users.setter
    def ldap_soft_delete_users(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "ldap_soft_delete_users", value)

    @_builtins.property
    @pulumi.getter(name="ldapUrl")
    def ldap_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP server URL, e.g. "ldaps://ldap.example.com:636".
        """
        return pulumi.get(self, "ldap_url")

    @ldap_url.setter
    def ldap_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_url", value)

    @_builtins.property
    @pulumi.getter(name="ldapUserGroupSearchFilter")
    def ldap_user_group_search_filter(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP filter selecting groups, e.g. "(objectClass=groupOfNames)".
        """
        return pulumi.get(self, "ldap_user_group_search_filter")

    @ldap_user_group_search_filter.setter
    def ldap_user_group_search_filter(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_user_group_search_filter", value)

    @_builtins.property
    @pulumi.getter(name="ldapUserSearchFilter")
    def ldap_user_search_filter(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The LDAP filter selecting users, e.g. "(objectClass=person)".
        """
        return pulumi.get(self, "ldap_user_search_filter")

    @ldap_user_search_filter.setter
    def ldap_user_search_filter(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "ldap_user_search_filter", value)

    @_builtins.property
    @pulumi.getter(name="requireUserEmail")
    def require_user_email(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether an email address is required for every user.
        """
        return pulumi.get(self, "require_user_email")

    @require_user_email.setter
    def require_user_email(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "require_user_email", value)

    @_builtins.property
    @pulumi.getter(name="sessionDuration")
    def session_duration(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The session lifetime, in minutes.
        """
        return pulumi.get(self, "session_duration")

    @session_duration.setter
    def session_duration(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "session_duration", value)

    @_builtins.property
    @pulumi.getter(name="signupDefaultCustomClaims")
    def signup_default_custom_claims(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The custom claims given to new users, as the JSON array string Pocket-ID expects.
        """
        return pulumi.get(self, "signup_default_custom_claims")

    @signup_default_custom_claims.setter
    def signup_default_custom_claims(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "signup_default_custom_claims", value)

    @_builtins.property
    @pulumi.getter(name="signupDefaultUserGroupIDs")
    def signup_default_user_group_ids(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The IDs of the user groups new users join, as the JSON array string Pocket-ID expects.
        """
        return pulumi.get(self, "signup_default_user_group_ids")

    @signup_default_user_group_ids.setter
    def signup_default_user_group_ids(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "signup_default_user_group_ids", value)

    @_builtins.property
    @pulumi.getter(name="smtpFrom")
    def smtp_from(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The sender address of outgoing emails.
        """
        return pulumi.get(self, "smtp_from")

    @smtp_from.setter
    def smtp_from(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "smtp_from", value)

    @_builtins.property
    @pulumi.getter(name="smtpHost")
    def smtp_host(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The SMTP server host name.
        """
        return pulumi.get(self, "smtp_host")

    @smtp_host.setter
    def smtp_host(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "smtp_host", value)

    @_builtins.property
    @pulumi.getter(name="smtpPassword")
    def smtp_password(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The SMTP password. It is a secret and is never read back from Pocket-ID: the value in state is the one from the program, and it is empty after an import.
        """
        return pulumi.get(self, "smtp_password")

    @smtp_password.setter
    def smtp_password(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "smtp_password", value)

    @_builtins.property
    @pulumi.getter(name="smtpPort")
    def smtp_port(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The SMTP server port.
        """
        return pulumi.get(self, "smtp_port")

    @smtp_port.setter
    def smtp_port(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "smtp_port", value)

    @_builtins.property
    @pulumi.getter(name="smtpSkipCertVerify")
    def smtp_skip_cert_verify(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether to skip the verification of the SMTP server certificate.
        """
        return pulumi.get(self, "smtp_skip_cert_verify")

    @smtp_skip_cert_verify.setter
    def smtp_skip_cert_verify(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "smtp_skip_cert_verify", value)

    @_builtins.property
    @pulumi.getter(name="smtpTls")
    def smtp_tls(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The SMTP transport security: "none", "starttls" or "tls".
        """
        return pulumi.get(self, "smtp_tls")

    @smtp_tls.setter
    def smtp_tls(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "smtp_tls", value)

    @_builtins.property
    @pulumi.getter(name="smtpUser")
    def smtp_user(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The SMTP user name.
        """
        return pulumi.get(self, "smtp_user")

    @smtp_user.setter
    def smtp_user(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "smtp_user", value)

    @_builtins.property
    @pulumi.getter(name="webauthnAllowSyncedPasskeys")
    def webauthn_allow_synced_passkeys(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether passkeys synced between devices are accepted.
        """
        return pulumi.get(self, "webauthn_allow_synced_passkeys")

    @webauthn_allow_synced_passkeys.setter
    def webauthn_allow_synced_passkeys(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "webauthn_allow_synced_passkeys", value)

    @_builtins.property
    @pulumi.getter(name="webauthnAuthenticatorAttachment")
    def webauthn_authenticator_attachment(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The accepted authenticator attachment: "any", "platform" or "cross-platform".
        """
        return pulumi.get(self, "webauthn_authenticator_attachment")

    @webauthn_authenticator_attachment.setter
    def webauthn_authenticator_attachment(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "webauthn_authenticator_attachment", value)

    @_builtins.property
    @pulumi.getter(name="webauthnUserVerification")
    def webauthn_user_verification(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The user verification requirement: "required" or "preferred".
        """
        return pulumi.get(self, "webauthn_user_verification")

    @webauthn_user_verification.setter
    def webauthn_user_verification(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "webauthn_user_verification", value)


@pulumi.type_token("pocket-id:index:ApplicationConfiguration")
class ApplicationConfiguration(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 accent_color: pulumi.Input[Optional[_builtins.str]] = None,
                 allow_own_account_edit: pulumi.Input[Optional[_builtins.bool]] = None,
                 allow_user_signups: pulumi.Input[Optional[_builtins.str]] = None,
                 app_name: pulumi.Input[Optional[_builtins.str]] = None,
                 auto_create_oidc_client_secret: pulumi.Input[Optional[_builtins.bool]] = None,
                 cimd_url_allowlist: pulumi.Input[Optional[_builtins.str]] = None,
                 disable_animations: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_api_key_expiration_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_login_notification_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_one_time_access_as_admin_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_one_time_access_as_unauthenticated_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_verification_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 emails_verified: pulumi.Input[Optional[_builtins.bool]] = None,
                 home_page_url: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_admin_group_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_group_member: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_group_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_group_unique_identifier: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_email: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_first_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_last_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_profile_picture: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_unique_identifier: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_username: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_base: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_bind_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_bind_password: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 ldap_skip_cert_verify: pulumi.Input[Optional[_builtins.bool]] = None,
                 ldap_soft_delete_users: pulumi.Input[Optional[_builtins.bool]] = None,
                 ldap_url: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_user_group_search_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_user_search_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 require_user_email: pulumi.Input[Optional[_builtins.bool]] = None,
                 session_duration: pulumi.Input[Optional[_builtins.int]] = None,
                 signup_default_custom_claims: pulumi.Input[Optional[_builtins.str]] = None,
                 signup_default_user_group_ids: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_from: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_host: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_password: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_port: pulumi.Input[Optional[_builtins.int]] = None,
                 smtp_skip_cert_verify: pulumi.Input[Optional[_builtins.bool]] = None,
                 smtp_tls: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_user: pulumi.Input[Optional[_builtins.str]] = None,
                 webauthn_allow_synced_passkeys: pulumi.Input[Optional[_builtins.bool]] = None,
                 webauthn_authenticator_attachment: pulumi.Input[Optional[_builtins.str]] = None,
                 webauthn_user_verification: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        The instance-wide configuration of Pocket-ID. It is a singleton with the fixed ID "app-config": only the fields that are set are managed, the others keep their current value on the server, and destroying the resource leaves the configuration untouched. Use at most one per instance.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.str] accent_color: The UI accent color, as "default" or a CSS color value.
        :param pulumi.Input[_builtins.bool] allow_own_account_edit: Whether users may edit their own account details.
        :param pulumi.Input[_builtins.str] allow_user_signups: Who may sign up by themselves: "disabled", "withToken" or "open".
        :param pulumi.Input[_builtins.str] app_name: The application name shown in the UI and in emails (1 to 30 characters).
        :param pulumi.Input[_builtins.bool] auto_create_oidc_client_secret: Whether a secret is generated automatically when an OIDC client is created.
        :param pulumi.Input[_builtins.str] cimd_url_allowlist: The allowlist of URLs accepted as OIDC client metadata documents (CIMD), in the format Pocket-ID expects.
        :param pulumi.Input[_builtins.bool] disable_animations: Whether to disable the UI animations.
        :param pulumi.Input[_builtins.bool] email_api_key_expiration_enabled: Whether an email is sent when an API key is about to expire.
        :param pulumi.Input[_builtins.bool] email_login_notification_enabled: Whether an email is sent when a user signs in from a new device.
        :param pulumi.Input[_builtins.bool] email_one_time_access_as_admin_enabled: Whether administrators may send one-time access links by email.
        :param pulumi.Input[_builtins.bool] email_one_time_access_as_unauthenticated_enabled: Whether unauthenticated users may request a one-time access link by email.
        :param pulumi.Input[_builtins.bool] email_verification_enabled: Whether users must verify their email address.
        :param pulumi.Input[_builtins.bool] emails_verified: Whether emails are considered verified by default.
        :param pulumi.Input[_builtins.str] home_page_url: The path of the page users land on after signing in, e.g. "/settings/account".
        :param pulumi.Input[_builtins.str] ldap_admin_group_name: The name of the LDAP group whose members become Pocket-ID administrators.
        :param pulumi.Input[_builtins.str] ldap_attribute_group_member: The LDAP attribute listing the members of a group.
        :param pulumi.Input[_builtins.str] ldap_attribute_group_name: The LDAP attribute mapped to the group name.
        :param pulumi.Input[_builtins.str] ldap_attribute_group_unique_identifier: The LDAP attribute holding the unique identifier of a group.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_display_name: The LDAP attribute mapped to the display name.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_email: The LDAP attribute mapped to the email address.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_first_name: The LDAP attribute mapped to the first name.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_last_name: The LDAP attribute mapped to the last name.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_profile_picture: The LDAP attribute mapped to the profile picture.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_unique_identifier: The LDAP attribute holding the unique identifier of a user.
        :param pulumi.Input[_builtins.str] ldap_attribute_user_username: The LDAP attribute mapped to the user name.
        :param pulumi.Input[_builtins.str] ldap_base: The LDAP base DN under which users and groups are searched.
        :param pulumi.Input[_builtins.str] ldap_bind_dn: The distinguished name used to bind to the LDAP server.
        :param pulumi.Input[_builtins.str] ldap_bind_password: The LDAP bind password. It is a secret and is never read back from Pocket-ID: the value in state is the one from the program, and it is empty after an import.
        :param pulumi.Input[_builtins.bool] ldap_enabled: Whether LDAP synchronization is enabled.
        :param pulumi.Input[_builtins.bool] ldap_skip_cert_verify: Whether to skip the verification of the LDAP server certificate.
        :param pulumi.Input[_builtins.bool] ldap_soft_delete_users: Whether users removed from LDAP are disabled instead of deleted.
        :param pulumi.Input[_builtins.str] ldap_url: The LDAP server URL, e.g. "ldaps://ldap.example.com:636".
        :param pulumi.Input[_builtins.str] ldap_user_group_search_filter: The LDAP filter selecting groups, e.g. "(objectClass=groupOfNames)".
        :param pulumi.Input[_builtins.str] ldap_user_search_filter: The LDAP filter selecting users, e.g. "(objectClass=person)".
        :param pulumi.Input[_builtins.bool] require_user_email: Whether an email address is required for every user.
        :param pulumi.Input[_builtins.int] session_duration: The session lifetime, in minutes.
        :param pulumi.Input[_builtins.str] signup_default_custom_claims: The custom claims given to new users, as the JSON array string Pocket-ID expects.
        :param pulumi.Input[_builtins.str] signup_default_user_group_ids: The IDs of the user groups new users join, as the JSON array string Pocket-ID expects.
        :param pulumi.Input[_builtins.str] smtp_from: The sender address of outgoing emails.
        :param pulumi.Input[_builtins.str] smtp_host: The SMTP server host name.
        :param pulumi.Input[_builtins.str] smtp_password: The SMTP password. It is a secret and is never read back from Pocket-ID: the value in state is the one from the program, and it is empty after an import.
        :param pulumi.Input[_builtins.int] smtp_port: The SMTP server port.
        :param pulumi.Input[_builtins.bool] smtp_skip_cert_verify: Whether to skip the verification of the SMTP server certificate.
        :param pulumi.Input[_builtins.str] smtp_tls: The SMTP transport security: "none", "starttls" or "tls".
        :param pulumi.Input[_builtins.str] smtp_user: The SMTP user name.
        :param pulumi.Input[_builtins.bool] webauthn_allow_synced_passkeys: Whether passkeys synced between devices are accepted.
        :param pulumi.Input[_builtins.str] webauthn_authenticator_attachment: The accepted authenticator attachment: "any", "platform" or "cross-platform".
        :param pulumi.Input[_builtins.str] webauthn_user_verification: The user verification requirement: "required" or "preferred".
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: Optional[ApplicationConfigurationArgs] = None,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The instance-wide configuration of Pocket-ID. It is a singleton with the fixed ID "app-config": only the fields that are set are managed, the others keep their current value on the server, and destroying the resource leaves the configuration untouched. Use at most one per instance.

        :param str resource_name: The name of the resource.
        :param ApplicationConfigurationArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ApplicationConfigurationArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 accent_color: pulumi.Input[Optional[_builtins.str]] = None,
                 allow_own_account_edit: pulumi.Input[Optional[_builtins.bool]] = None,
                 allow_user_signups: pulumi.Input[Optional[_builtins.str]] = None,
                 app_name: pulumi.Input[Optional[_builtins.str]] = None,
                 auto_create_oidc_client_secret: pulumi.Input[Optional[_builtins.bool]] = None,
                 cimd_url_allowlist: pulumi.Input[Optional[_builtins.str]] = None,
                 disable_animations: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_api_key_expiration_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_login_notification_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_one_time_access_as_admin_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_one_time_access_as_unauthenticated_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 email_verification_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 emails_verified: pulumi.Input[Optional[_builtins.bool]] = None,
                 home_page_url: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_admin_group_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_group_member: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_group_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_group_unique_identifier: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_email: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_first_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_last_name: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_profile_picture: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_unique_identifier: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_attribute_user_username: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_base: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_bind_dn: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_bind_password: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 ldap_skip_cert_verify: pulumi.Input[Optional[_builtins.bool]] = None,
                 ldap_soft_delete_users: pulumi.Input[Optional[_builtins.bool]] = None,
                 ldap_url: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_user_group_search_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 ldap_user_search_filter: pulumi.Input[Optional[_builtins.str]] = None,
                 require_user_email: pulumi.Input[Optional[_builtins.bool]] = None,
                 session_duration: pulumi.Input[Optional[_builtins.int]] = None,
                 signup_default_custom_claims: pulumi.Input[Optional[_builtins.str]] = None,
                 signup_default_user_group_ids: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_from: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_host: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_password: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_port: pulumi.Input[Optional[_builtins.int]] = None,
                 smtp_skip_cert_verify: pulumi.Input[Optional[_builtins.bool]] = None,
                 smtp_tls: pulumi.Input[Optional[_builtins.str]] = None,
                 smtp_user: pulumi.Input[Optional[_builtins.str]] = None,
                 webauthn_allow_synced_passkeys: pulumi.Input[Optional[_builtins.bool]] = None,
                 webauthn_authenticator_attachment: pulumi.Input[Optional[_builtins.str]] = None,
                 webauthn_user_verification: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ApplicationConfigurationArgs.__new__(ApplicationConfigurationArgs)

            __props__.__dict__["accent_color"] = accent_color
            __props__.__dict__["allow_own_account_edit"] = allow_own_account_edit
            __props__.__dict__["allow_user_signups"] = allow_user_signups
            __props__.__dict__["app_name"] = app_name
            __props__.__dict__["auto_create_oidc_client_secret"] = auto_create_oidc_client_secret
            __props__.__dict__["cimd_url_allowlist"] = cimd_url_allowlist
            __props__.__dict__["disable_animations"] = disable_animations
            __props__.__dict__["email_api_key_expiration_enabled"] = email_api_key_expiration_enabled
            __props__.__dict__["email_login_notification_enabled"] = email_login_notification_enabled
            __props__.__dict__["email_one_time_access_as_admin_enabled"] = email_one_time_access_as_admin_enabled
            __props__.__dict__["email_one_time_access_as_unauthenticated_enabled"] = email_one_time_access_as_unauthenticated_enabled
            __props__.__dict__["email_verification_enabled"] = email_verification_enabled
            __props__.__dict__["emails_verified"] = emails_verified
            __props__.__dict__["home_page_url"] = home_page_url
            __props__.__dict__["ldap_admin_group_name"] = ldap_admin_group_name
            __props__.__dict__["ldap_attribute_group_member"] = ldap_attribute_group_member
            __props__.__dict__["ldap_attribute_group_name"] = ldap_attribute_group_name
            __props__.__dict__["ldap_attribute_group_unique_identifier"] = ldap_attribute_group_unique_identifier
            __props__.__dict__["ldap_attribute_user_display_name"] = ldap_attribute_user_display_name
            __props__.__dict__["ldap_attribute_user_email"] = ldap_attribute_user_email
            __props__.__dict__["ldap_attribute_user_first_name"] = ldap_attribute_user_first_name
            __props__.__dict__["ldap_attribute_user_last_name"] = ldap_attribute_user_last_name
            __props__.__dict__["ldap_attribute_user_profile_picture"] = ldap_attribute_user_profile_picture
            __props__.__dict__["ldap_attribute_user_unique_identifier"] = ldap_attribute_user_unique_identifier
            __props__.__dict__["ldap_attribute_user_username"] = ldap_attribute_user_username
            __props__.__dict__["ldap_base"] = ldap_base
            __props__.__dict__["ldap_bind_dn"] = ldap_bind_dn
            __props__.__dict__["ldap_bind_password"] = None if ldap_bind_password is None else pulumi.Output.secret(ldap_bind_password)
            __props__.__dict__["ldap_enabled"] = ldap_enabled
            __props__.__dict__["ldap_skip_cert_verify"] = ldap_skip_cert_verify
            __props__.__dict__["ldap_soft_delete_users"] = ldap_soft_delete_users
            __props__.__dict__["ldap_url"] = ldap_url
            __props__.__dict__["ldap_user_group_search_filter"] = ldap_user_group_search_filter
            __props__.__dict__["ldap_user_search_filter"] = ldap_user_search_filter
            __props__.__dict__["require_user_email"] = require_user_email
            __props__.__dict__["session_duration"] = session_duration
            __props__.__dict__["signup_default_custom_claims"] = signup_default_custom_claims
            __props__.__dict__["signup_default_user_group_ids"] = signup_default_user_group_ids
            __props__.__dict__["smtp_from"] = smtp_from
            __props__.__dict__["smtp_host"] = smtp_host
            __props__.__dict__["smtp_password"] = None if smtp_password is None else pulumi.Output.secret(smtp_password)
            __props__.__dict__["smtp_port"] = smtp_port
            __props__.__dict__["smtp_skip_cert_verify"] = smtp_skip_cert_verify
            __props__.__dict__["smtp_tls"] = smtp_tls
            __props__.__dict__["smtp_user"] = smtp_user
            __props__.__dict__["webauthn_allow_synced_passkeys"] = webauthn_allow_synced_passkeys
            __props__.__dict__["webauthn_authenticator_attachment"] = webauthn_authenticator_attachment
            __props__.__dict__["webauthn_user_verification"] = webauthn_user_verification
        secret_opts = pulumi.ResourceOptions(additional_secret_outputs=["ldapBindPassword", "smtpPassword"])
        opts = pulumi.ResourceOptions.merge(opts, secret_opts)
        super(ApplicationConfiguration, __self__).__init__(
            'pocket-id:index:ApplicationConfiguration',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'ApplicationConfiguration':
        """
        Get an existing ApplicationConfiguration resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ApplicationConfigurationArgs.__new__(ApplicationConfigurationArgs)

        __props__.__dict__["accent_color"] = None
        __props__.__dict__["allow_own_account_edit"] = None
        __props__.__dict__["allow_user_signups"] = None
        __props__.__dict__["app_name"] = None
        __props__.__dict__["auto_create_oidc_client_secret"] = None
        __props__.__dict__["cimd_url_allowlist"] = None
        __props__.__dict__["disable_animations"] = None
        __props__.__dict__["email_api_key_expiration_enabled"] = None
        __props__.__dict__["email_login_notification_enabled"] = None
        __props__.__dict__["email_one_time_access_as_admin_enabled"] = None
        __props__.__dict__["email_one_time_access_as_unauthenticated_enabled"] = None
        __props__.__dict__["email_verification_enabled"] = None
        __props__.__dict__["emails_verified"] = None
        __props__.__dict__["home_page_url"] = None
        __props__.__dict__["ldap_admin_group_name"] = None
        __props__.__dict__["ldap_attribute_group_member"] = None
        __props__.__dict__["ldap_attribute_group_name"] = None
        __props__.__dict__["ldap_attribute_group_unique_identifier"] = None
        __props__.__dict__["ldap_attribute_user_display_name"] = None
        __props__.__dict__["ldap_attribute_user_email"] = None
        __props__.__dict__["ldap_attribute_user_first_name"] = None
        __props__.__dict__["ldap_attribute_user_last_name"] = None
        __props__.__dict__["ldap_attribute_user_profile_picture"] = None
        __props__.__dict__["ldap_attribute_user_unique_identifier"] = None
        __props__.__dict__["ldap_attribute_user_username"] = None
        __props__.__dict__["ldap_base"] = None
        __props__.__dict__["ldap_bind_dn"] = None
        __props__.__dict__["ldap_bind_password"] = None
        __props__.__dict__["ldap_enabled"] = None
        __props__.__dict__["ldap_skip_cert_verify"] = None
        __props__.__dict__["ldap_soft_delete_users"] = None
        __props__.__dict__["ldap_url"] = None
        __props__.__dict__["ldap_user_group_search_filter"] = None
        __props__.__dict__["ldap_user_search_filter"] = None
        __props__.__dict__["require_user_email"] = None
        __props__.__dict__["session_duration"] = None
        __props__.__dict__["signup_default_custom_claims"] = None
        __props__.__dict__["signup_default_user_group_ids"] = None
        __props__.__dict__["smtp_from"] = None
        __props__.__dict__["smtp_host"] = None
        __props__.__dict__["smtp_password"] = None
        __props__.__dict__["smtp_port"] = None
        __props__.__dict__["smtp_skip_cert_verify"] = None
        __props__.__dict__["smtp_tls"] = None
        __props__.__dict__["smtp_user"] = None
        __props__.__dict__["webauthn_allow_synced_passkeys"] = None
        __props__.__dict__["webauthn_authenticator_attachment"] = None
        __props__.__dict__["webauthn_user_verification"] = None
        return ApplicationConfiguration(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accentColor")
    def accent_color(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The UI accent color, as "default" or a CSS color value.
        """
        return pulumi.get(self, "accent_color")

    @_builtins.property
    @pulumi.getter(name="allowOwnAccountEdit")
    def allow_own_account_edit(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether users may edit their own account details.
        """
        return pulumi.get(self, "allow_own_account_edit")

    @_builtins.property
    @pulumi.getter(name="allowUserSignups")
    def allow_user_signups(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        Who may sign up by themselves: "disabled", "withToken" or "open".
        """
        return pulumi.get(self, "allow_user_signups")

    @_builtins.property
    @pulumi.getter(name="appName")
    def app_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The application name shown in the UI and in emails (1 to 30 characters).
        """
        return pulumi.get(self, "app_name")

    @_builtins.property
    @pulumi.getter(name="autoCreateOidcClientSecret")
    def auto_create_oidc_client_secret(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether a secret is generated automatically when an OIDC client is created.
        """
        return pulumi.get(self, "auto_create_oidc_client_secret")

    @_builtins.property
    @pulumi.getter(name="cimdUrlAllowlist")
    def cimd_url_allowlist(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The allowlist of URLs accepted as OIDC client metadata documents (CIMD), in the format Pocket-ID expects.
        """
        return pulumi.get(self, "cimd_url_allowlist")

    @_builtins.property
    @pulumi.getter(name="disableAnimations")
    def disable_animations(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to disable the UI animations.
        """
        return pulumi.get(self, "disable_animations")

    @_builtins.property
    @pulumi.getter(name="emailApiKeyExpirationEnabled")
    def email_api_key_expiration_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether an email is sent when an API key is about to expire.
        """
        return pulumi.get(self, "email_api_key_expiration_enabled")

    @_builtins.property
    @pulumi.getter(name="emailLoginNotificationEnabled")
    def email_login_notification_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether an email is sent when a user signs in from a new device.
        """
        return pulumi.get(self, "email_login_notification_enabled")

    @_builtins.property
    @pulumi.getter(name="emailOneTimeAccessAsAdminEnabled")
    def email_one_time_access_as_admin_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether administrators may send one-time access links by email.
        """
        return pulumi.get(self, "email_one_time_access_as_admin_enabled")

    @_builtins.property
    @pulumi.getter(name="emailOneTimeAccessAsUnauthenticatedEnabled")
    def email_one_time_access_as_unauthenticated_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether unauthenticated users may request a one-time access link by email.
        """
        return pulumi.get(self, "email_one_time_access_as_unauthenticated_enabled")

    @_builtins.property
    @pulumi.getter(name="emailVerificationEnabled")
    def email_verification_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether users must verify their email address.
        """
        return pulumi.get(self, "email_verification_enabled")

    @_builtins.property
    @pulumi.getter(name="emailsVerified")
    def emails_verified(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether emails are considered verified by default.
        """
        return pulumi.get(self, "emails_verified")

    @_builtins.property
    @pulumi.getter(name="homePageUrl")
    def home_page_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The path of the page users land on after signing in, e.g. "/settings/account".
        """
        return pulumi.get(self, "home_page_url")

    @_builtins.property
    @pulumi.getter(name="ldapAdminGroupName")
    def ldap_admin_group_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The name of the LDAP group whose members become Pocket-ID administrators.
        """
        return pulumi.get(self, "ldap_admin_group_name")

    @_builtins.property
    @pulumi.getter(name="ldapAttributeGroupMember")
    def ldap_attribute_group_member(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP attribute listing the members of a group.
        """
        return pulumi.get(self, "ldap_attribute_group_member")

    @_builtins.property
    @pulumi.getter(name="ldapAttributeGroupName")
    def ldap_attribute_group_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the group name.
        """
        return pulumi.get(self, "ldap_attribute_group_name")

    @_builtins.property
    @pulumi.getter(name="ldapAttributeGroupUniqueIdentifier")
    def ldap_attribute_group_unique_identifier(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP attribute holding the unique identifier of a group.
        """
        return pulumi.get(self, "ldap_attribute_group_unique_identifier")

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserDisplayName")
    def ldap_attribute_user_display_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the display name.
        """
        return pulumi.get(self, "ldap_attribute_user_display_name")

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserEmail")
    def ldap_attribute_user_email(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the email address.
        """
        return pulumi.get(self, "ldap_attribute_user_email")

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserFirstName")
    def ldap_attribute_user_first_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the first name.
        """
        return pulumi.get(self, "ldap_attribute_user_first_name")

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserLastName")
    def ldap_attribute_user_last_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the last name.
        """
        return pulumi.get(self, "ldap_attribute_user_last_name")

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserProfilePicture")
    def ldap_attribute_user_profile_picture(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the profile picture.
        """
        return pulumi.get(self, "ldap_attribute_user_profile_picture")

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserUniqueIdentifier")
    def ldap_attribute_user_unique_identifier(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP attribute holding the unique identifier of a user.
        """
        return pulumi.get(self, "ldap_attribute_user_unique_identifier")

    @_builtins.property
    @pulumi.getter(name="ldapAttributeUserUsername")
    def ldap_attribute_user_username(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP attribute mapped to the user name.
        """
        return pulumi.get(self, "ldap_attribute_user_username")

    @_builtins.property
    @pulumi.getter(name="ldapBase")
    def ldap_base(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP base DN under which users and groups are searched.
        """
        return pulumi.get(self, "ldap_base")

    @_builtins.property
    @pulumi.getter(name="ldapBindDn")
    def ldap_bind_dn(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The distinguished name used to bind to the LDAP server.
        """
        return pulumi.get(self, "ldap_bind_dn")

    @_builtins.property
    @pulumi.getter(name="ldapBindPassword")
    def ldap_bind_password(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP bind password. It is a secret and is never read back from Pocket-ID: the value in state is the one from the program, and it is empty after an import.
        """
        return pulumi.get(self, "ldap_bind_password")

    @_builtins.property
    @pulumi.getter(name="ldapEnabled")
    def ldap_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether LDAP synchronization is enabled.
        """
        return pulumi.get(self, "ldap_enabled")

    @_builtins.property
    @pulumi.getter(name="ldapSkipCertVerify")
    def ldap_skip_cert_verify(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to skip the verification of the LDAP server certificate.
        """
        return pulumi.get(self, "ldap_skip_cert_verify")

    @_builtins.property
    @pulumi.getter(name="ldapSoftDeleteUsers")
    def ldap_soft_delete_users(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether users removed from LDAP are disabled instead of deleted.
        """
        return pulumi.get(self, "ldap_soft_delete_users")

    @_builtins.property
    @pulumi.getter(name="ldapUrl")
    def ldap_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP server URL, e.g. "ldaps://ldap.example.com:636".
        """
        return pulumi.get(self, "ldap_url")

    @_builtins.property
    @pulumi.getter(name="ldapUserGroupSearchFilter")
    def ldap_user_group_search_filter(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP filter selecting groups, e.g. "(objectClass=groupOfNames)".
        """
        return pulumi.get(self, "ldap_user_group_search_filter")

    @_builtins.property
    @pulumi.getter(name="ldapUserSearchFilter")
    def ldap_user_search_filter(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The LDAP filter selecting users, e.g. "(objectClass=person)".
        """
        return pulumi.get(self, "ldap_user_search_filter")

    @_builtins.property
    @pulumi.getter(name="requireUserEmail")
    def require_user_email(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether an email address is required for every user.
        """
        return pulumi.get(self, "require_user_email")

    @_builtins.property
    @pulumi.getter(name="sessionDuration")
    def session_duration(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The session lifetime, in minutes.
        """
        return pulumi.get(self, "session_duration")

    @_builtins.property
    @pulumi.getter(name="signupDefaultCustomClaims")
    def signup_default_custom_claims(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The custom claims given to new users, as the JSON array string Pocket-ID expects.
        """
        return pulumi.get(self, "signup_default_custom_claims")

    @_builtins.property
    @pulumi.getter(name="signupDefaultUserGroupIDs")
    def signup_default_user_group_ids(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The IDs of the user groups new users join, as the JSON array string Pocket-ID expects.
        """
        return pulumi.get(self, "signup_default_user_group_ids")

    @_builtins.property
    @pulumi.getter(name="smtpFrom")
    def smtp_from(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The sender address of outgoing emails.
        """
        return pulumi.get(self, "smtp_from")

    @_builtins.property
    @pulumi.getter(name="smtpHost")
    def smtp_host(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The SMTP server host name.
        """
        return pulumi.get(self, "smtp_host")

    @_builtins.property
    @pulumi.getter(name="smtpPassword")
    def smtp_password(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The SMTP password. It is a secret and is never read back from Pocket-ID: the value in state is the one from the program, and it is empty after an import.
        """
        return pulumi.get(self, "smtp_password")

    @_builtins.property
    @pulumi.getter(name="smtpPort")
    def smtp_port(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The SMTP server port.
        """
        return pulumi.get(self, "smtp_port")

    @_builtins.property
    @pulumi.getter(name="smtpSkipCertVerify")
    def smtp_skip_cert_verify(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether to skip the verification of the SMTP server certificate.
        """
        return pulumi.get(self, "smtp_skip_cert_verify")

    @_builtins.property
    @pulumi.getter(name="smtpTls")
    def smtp_tls(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The SMTP transport security: "none", "starttls" or "tls".
        """
        return pulumi.get(self, "smtp_tls")

    @_builtins.property
    @pulumi.getter(name="smtpUser")
    def smtp_user(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The SMTP user name.
        """
        return pulumi.get(self, "smtp_user")

    @_builtins.property
    @pulumi.getter(name="webauthnAllowSyncedPasskeys")
    def webauthn_allow_synced_passkeys(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether passkeys synced between devices are accepted.
        """
        return pulumi.get(self, "webauthn_allow_synced_passkeys")

    @_builtins.property
    @pulumi.getter(name="webauthnAuthenticatorAttachment")
    def webauthn_authenticator_attachment(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The accepted authenticator attachment: "any", "platform" or "cross-platform".
        """
        return pulumi.get(self, "webauthn_authenticator_attachment")

    @_builtins.property
    @pulumi.getter(name="webauthnUserVerification")
    def webauthn_user_verification(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The user verification requirement: "required" or "preferred".
        """
        return pulumi.get(self, "webauthn_user_verification")

