# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from ._enums import *

__all__ = ['ApplicationImageArgs', 'ApplicationImage']

@pulumi.input_type
class ApplicationImageArgs:
    def __init__(__self__, *,
                 image: pulumi.Input[Union[pulumi.Asset, pulumi.Archive]],
                 type: pulumi.Input['ApplicationImageType']):
        """
        The set of arguments for constructing a ApplicationImage resource.

        :param pulumi.Input[Union[pulumi.Asset, pulumi.Archive]] image: The image file as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file. It is not read back as an asset: after an import it is empty and must be set in the program.
        :param pulumi.Input['ApplicationImageType'] type: Which image to manage. Changing it replaces the resource.
        """
        pulumi.set(__self__, "image", image)
        pulumi.set(__self__, "type", type)

    @_builtins.property
    @pulumi.getter
    def image(self) -> pulumi.Input[Union[pulumi.Asset, pulumi.Archive]]:
        """
        The image file as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file. It is not read back as an asset: after an import it is empty and must be set in the program.
        """
        return pulumi.get(self, "image")

    @image.setter
    def image(self, value: pulumi.Input[Union[pulumi.Asset, pulumi.Archive]]):
        pulumi.set(self, "image", value)

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Input['ApplicationImageType']:
        """
        Which image to manage. Changing it replaces the resource.
        """
        return pulumi.get(self, "type")

    @type.setter
    def type(self, value: pulumi.Input['ApplicationImageType']):
        pulumi.set(self, "type", value)


@pulumi.type_token("pocket-id:index:ApplicationImage")
class ApplicationImage(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 image: pulumi.Input[Optional[Union[pulumi.Asset, pulumi.Archive]]] = None,
                 type: pulumi.Input[Optional['ApplicationImageType']] = None,
                 __props__=None):
        """
        A global Pocket-ID branding image (logo, dark logo, favicon, background, e-mail image or default profile picture) uploaded from a local file or asset. Destroying it deletes the custom image and restores the default, except for the favicon and the e-mail image, which the API cannot delete: destroying those only removes the resource from state. Import with the type, e.g. "favicon". Per-user profile pictures are not covered.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Union[pulumi.Asset, pulumi.Archive]] image: The image file as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file. It is not read back as an asset: after an import it is empty and must be set in the program.
        :param pulumi.Input['ApplicationImageType'] type: Which image to manage. Changing it replaces the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: ApplicationImageArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A global Pocket-ID branding image (logo, dark logo, favicon, background, e-mail image or default profile picture) uploaded from a local file or asset. Destroying it deletes the custom image and restores the default, except for the favicon and the e-mail image, which the API cannot delete: destroying those only removes the resource from state. Import with the type, e.g. "favicon". Per-user profile pictures are not covered.

        :param str resource_name: The name of the resource.
        :param ApplicationImageArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(ApplicationImageArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 image: pulumi.Input[Optional[Union[pulumi.Asset, pulumi.Archive]]] = None,
                 type: pulumi.Input[Optional['ApplicationImageType']] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = ApplicationImageArgs.__new__(ApplicationImageArgs)

            if image is None and not opts.urn:
                raise TypeError("Missing required property 'image'")
            __props__.__dict__["image"] = image
            if type is None and not opts.urn:
                raise TypeError("Missing required property 'type'")
            __props__.__dict__["type"] = type
            __props__.__dict__["sha256"] = None
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["type"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(ApplicationImage, __self__).__init__(
            'pocket-id:index:ApplicationImage',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'ApplicationImage':
        """
        Get an existing ApplicationImage resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = ApplicationImageArgs.__new__(ApplicationImageArgs)

        __props__.__dict__["image"] = None
        __props__.__dict__["sha256"] = None
        __props__.__dict__["type"] = None
        return ApplicationImage(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def image(self) -> pulumi.Output[Union[pulumi.Asset, pulumi.Archive]]:
        """
        The image file as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file. It is not read back as an asset: after an import it is empty and must be set in the program.
        """
        return pulumi.get(self, "image")

    @_builtins.property
    @pulumi.getter
    def sha256(self) -> pulumi.Output[_builtins.str]:
        """
        The hex SHA-256 digest of the image content. At refresh it is the digest of the bytes currently served by Pocket-ID, so out-of-band changes show up as a diff.
        """
        return pulumi.get(self, "sha256")

    @_builtins.property
    @pulumi.getter
    def type(self) -> pulumi.Output['ApplicationImageType']:
        """
        Which image to manage. Changing it replaces the resource.
        """
        return pulumi.get(self, "type")

