# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['CustomClaimsArgs', 'CustomClaims']

@pulumi.input_type
class CustomClaimsArgs:
    def __init__(__self__, *,
                 owner_id: pulumi.Input[_builtins.str],
                 owner_type: pulumi.Input[_builtins.str],
                 claims: Optional[pulumi.Input[Sequence[pulumi.Input['CustomClaimArgs']]]] = None):
        """
        The set of arguments for constructing a CustomClaims resource.
        """
        pulumi.set(__self__, "owner_id", owner_id)
        pulumi.set(__self__, "owner_type", owner_type)
        if claims is not None:
            pulumi.set(__self__, "claims", claims)

    @_builtins.property
    @pulumi.getter(name="ownerId")
    def owner_id(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "owner_id")

    @owner_id.setter
    def owner_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "owner_id", value)

    @_builtins.property
    @pulumi.getter(name="ownerType")
    def owner_type(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "owner_type")

    @owner_type.setter
    def owner_type(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "owner_type", value)

    @_builtins.property
    @pulumi.getter
    def claims(self) -> Optional[pulumi.Input[Sequence[pulumi.Input['CustomClaimArgs']]]]:
        return pulumi.get(self, "claims")

    @claims.setter
    def claims(self, value: Optional[pulumi.Input[Sequence[pulumi.Input['CustomClaimArgs']]]]):
        pulumi.set(self, "claims", value)


@pulumi.type_token("pocket-id:index:CustomClaims")
class CustomClaims(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 claims: Optional[pulumi.Input[Sequence[pulumi.Input[Union['CustomClaimArgs', 'CustomClaimArgsDict']]]]] = None,
                 owner_id: Optional[pulumi.Input[_builtins.str]] = None,
                 owner_type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        """
        Create a CustomClaims resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: CustomClaimsArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a CustomClaims resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param CustomClaimsArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(CustomClaimsArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 claims: Optional[pulumi.Input[Sequence[pulumi.Input[Union['CustomClaimArgs', 'CustomClaimArgsDict']]]]] = None,
                 owner_id: Optional[pulumi.Input[_builtins.str]] = None,
                 owner_type: Optional[pulumi.Input[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = CustomClaimsArgs.__new__(CustomClaimsArgs)

            __props__.__dict__["claims"] = claims
            if owner_id is None and not opts.urn:
                raise TypeError("Missing required property 'owner_id'")
            __props__.__dict__["owner_id"] = owner_id
            if owner_type is None and not opts.urn:
                raise TypeError("Missing required property 'owner_type'")
            __props__.__dict__["owner_type"] = owner_type
        super(CustomClaims, __self__).__init__(
            'pocket-id:index:CustomClaims',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'CustomClaims':
        """
        Get an existing CustomClaims resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = CustomClaimsArgs.__new__(CustomClaimsArgs)

        __props__.__dict__["claims"] = None
        __props__.__dict__["owner_id"] = None
        __props__.__dict__["owner_type"] = None
        return CustomClaims(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def claims(self) -> pulumi.Output[Optional[Sequence['outputs.CustomClaim']]]:
        return pulumi.get(self, "claims")

    @_builtins.property
    @pulumi.getter(name="ownerId")
    def owner_id(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "owner_id")

    @_builtins.property
    @pulumi.getter(name="ownerType")
    def owner_type(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "owner_type")

