# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetUserGroupResult',
    'AwaitableGetUserGroupResult',
    'get_user_group',
    'get_user_group_output',
]

@pulumi.output_type
class GetUserGroupResult:
    def __init__(__self__, custom_claims=None, friendly_name=None, name=None, user_group_id=None, user_ids=None):
        if custom_claims and not isinstance(custom_claims, dict):
            raise TypeError("Expected argument 'custom_claims' to be a dict")
        pulumi.set(__self__, "custom_claims", custom_claims)
        if friendly_name and not isinstance(friendly_name, str):
            raise TypeError("Expected argument 'friendly_name' to be a str")
        pulumi.set(__self__, "friendly_name", friendly_name)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if user_group_id and not isinstance(user_group_id, str):
            raise TypeError("Expected argument 'user_group_id' to be a str")
        pulumi.set(__self__, "user_group_id", user_group_id)
        if user_ids and not isinstance(user_ids, list):
            raise TypeError("Expected argument 'user_ids' to be a list")
        pulumi.set(__self__, "user_ids", user_ids)

    @_builtins.property
    @pulumi.getter(name="customClaims")
    def custom_claims(self) -> Mapping[str, _builtins.str]:
        """
        The custom claims of the group.
        """
        return pulumi.get(self, "custom_claims")

    @_builtins.property
    @pulumi.getter(name="friendlyName")
    def friendly_name(self) -> _builtins.str:
        """
        The human-readable name of the group.
        """
        return pulumi.get(self, "friendly_name")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The name of the group.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="userGroupId")
    def user_group_id(self) -> _builtins.str:
        """
        The ID of the group.
        """
        return pulumi.get(self, "user_group_id")

    @_builtins.property
    @pulumi.getter(name="userIds")
    def user_ids(self) -> Sequence[_builtins.str]:
        """
        The IDs of the members of the group.
        """
        return pulumi.get(self, "user_ids")


class AwaitableGetUserGroupResult(GetUserGroupResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetUserGroupResult(
            custom_claims=self.custom_claims,
            friendly_name=self.friendly_name,
            name=self.name,
            user_group_id=self.user_group_id,
            user_ids=self.user_ids)


def get_user_group(name: Optional[_builtins.str] = None,
                   user_group_id: Optional[_builtins.str] = None,
                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetUserGroupResult:
    """
    Looks up a Pocket-ID user group by ID or by exact name.

    :param _builtins.str name: The exact name of the group. Exactly one of userGroupId or name must be set.
    :param _builtins.str user_group_id: The ID of the group. Exactly one of userGroupId or name must be set.
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['userGroupId'] = user_group_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('pocket-id:index:getUserGroup', __args__, opts=opts, typ=GetUserGroupResult).value

    return AwaitableGetUserGroupResult(
        custom_claims=pulumi.get(__ret__, 'custom_claims'),
        friendly_name=pulumi.get(__ret__, 'friendly_name'),
        name=pulumi.get(__ret__, 'name'),
        user_group_id=pulumi.get(__ret__, 'user_group_id'),
        user_ids=pulumi.get(__ret__, 'user_ids'))
def get_user_group_output(name: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                          user_group_id: pulumi.Input[Optional[Optional[_builtins.str]]] = None,
                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetUserGroupResult]:
    """
    Looks up a Pocket-ID user group by ID or by exact name.

    :param _builtins.str name: The exact name of the group. Exactly one of userGroupId or name must be set.
    :param _builtins.str user_group_id: The ID of the group. Exactly one of userGroupId or name must be set.
    """
    __args__ = dict()
    __args__['name'] = name
    __args__['userGroupId'] = user_group_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('pocket-id:index:getUserGroup', __args__, opts=opts, typ=GetUserGroupResult)
    return __ret__.apply(lambda __response__: GetUserGroupResult(
        custom_claims=pulumi.get(__response__, 'custom_claims'),
        friendly_name=pulumi.get(__response__, 'friendly_name'),
        name=pulumi.get(__response__, 'name'),
        user_group_id=pulumi.get(__response__, 'user_group_id'),
        user_ids=pulumi.get(__response__, 'user_ids')))
