# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = [
    'GetOpenIdConfigurationResult',
    'AwaitableGetOpenIdConfigurationResult',
    'get_open_id_configuration',
    'get_open_id_configuration_output',
]

@pulumi.output_type
class GetOpenIdConfigurationResult:
    def __init__(__self__, authorization_endpoint=None, claims_supported=None, code_challenge_methods_supported=None, device_authorization_endpoint=None, end_session_endpoint=None, grant_types_supported=None, id_token_signing_alg_values_supported=None, introspection_endpoint=None, issuer=None, jwks_uri=None, response_types_supported=None, scopes_supported=None, subject_types_supported=None, token_endpoint=None, token_endpoint_auth_methods_supported=None, userinfo_endpoint=None):
        if authorization_endpoint and not isinstance(authorization_endpoint, str):
            raise TypeError("Expected argument 'authorization_endpoint' to be a str")
        pulumi.set(__self__, "authorization_endpoint", authorization_endpoint)
        if claims_supported and not isinstance(claims_supported, list):
            raise TypeError("Expected argument 'claims_supported' to be a list")
        pulumi.set(__self__, "claims_supported", claims_supported)
        if code_challenge_methods_supported and not isinstance(code_challenge_methods_supported, list):
            raise TypeError("Expected argument 'code_challenge_methods_supported' to be a list")
        pulumi.set(__self__, "code_challenge_methods_supported", code_challenge_methods_supported)
        if device_authorization_endpoint and not isinstance(device_authorization_endpoint, str):
            raise TypeError("Expected argument 'device_authorization_endpoint' to be a str")
        pulumi.set(__self__, "device_authorization_endpoint", device_authorization_endpoint)
        if end_session_endpoint and not isinstance(end_session_endpoint, str):
            raise TypeError("Expected argument 'end_session_endpoint' to be a str")
        pulumi.set(__self__, "end_session_endpoint", end_session_endpoint)
        if grant_types_supported and not isinstance(grant_types_supported, list):
            raise TypeError("Expected argument 'grant_types_supported' to be a list")
        pulumi.set(__self__, "grant_types_supported", grant_types_supported)
        if id_token_signing_alg_values_supported and not isinstance(id_token_signing_alg_values_supported, list):
            raise TypeError("Expected argument 'id_token_signing_alg_values_supported' to be a list")
        pulumi.set(__self__, "id_token_signing_alg_values_supported", id_token_signing_alg_values_supported)
        if introspection_endpoint and not isinstance(introspection_endpoint, str):
            raise TypeError("Expected argument 'introspection_endpoint' to be a str")
        pulumi.set(__self__, "introspection_endpoint", introspection_endpoint)
        if issuer and not isinstance(issuer, str):
            raise TypeError("Expected argument 'issuer' to be a str")
        pulumi.set(__self__, "issuer", issuer)
        if jwks_uri and not isinstance(jwks_uri, str):
            raise TypeError("Expected argument 'jwks_uri' to be a str")
        pulumi.set(__self__, "jwks_uri", jwks_uri)
        if response_types_supported and not isinstance(response_types_supported, list):
            raise TypeError("Expected argument 'response_types_supported' to be a list")
        pulumi.set(__self__, "response_types_supported", response_types_supported)
        if scopes_supported and not isinstance(scopes_supported, list):
            raise TypeError("Expected argument 'scopes_supported' to be a list")
        pulumi.set(__self__, "scopes_supported", scopes_supported)
        if subject_types_supported and not isinstance(subject_types_supported, list):
            raise TypeError("Expected argument 'subject_types_supported' to be a list")
        pulumi.set(__self__, "subject_types_supported", subject_types_supported)
        if token_endpoint and not isinstance(token_endpoint, str):
            raise TypeError("Expected argument 'token_endpoint' to be a str")
        pulumi.set(__self__, "token_endpoint", token_endpoint)
        if token_endpoint_auth_methods_supported and not isinstance(token_endpoint_auth_methods_supported, list):
            raise TypeError("Expected argument 'token_endpoint_auth_methods_supported' to be a list")
        pulumi.set(__self__, "token_endpoint_auth_methods_supported", token_endpoint_auth_methods_supported)
        if userinfo_endpoint and not isinstance(userinfo_endpoint, str):
            raise TypeError("Expected argument 'userinfo_endpoint' to be a str")
        pulumi.set(__self__, "userinfo_endpoint", userinfo_endpoint)

    @_builtins.property
    @pulumi.getter(name="authorizationEndpoint")
    def authorization_endpoint(self) -> _builtins.str:
        """
        The OAuth 2.0 authorization endpoint.
        """
        return pulumi.get(self, "authorization_endpoint")

    @_builtins.property
    @pulumi.getter(name="claimsSupported")
    def claims_supported(self) -> Sequence[_builtins.str]:
        """
        The supported claims.
        """
        return pulumi.get(self, "claims_supported")

    @_builtins.property
    @pulumi.getter(name="codeChallengeMethodsSupported")
    def code_challenge_methods_supported(self) -> Sequence[_builtins.str]:
        """
        The supported PKCE code challenge methods.
        """
        return pulumi.get(self, "code_challenge_methods_supported")

    @_builtins.property
    @pulumi.getter(name="deviceAuthorizationEndpoint")
    def device_authorization_endpoint(self) -> _builtins.str:
        """
        The device authorization endpoint, empty if the instance does not advertise one.
        """
        return pulumi.get(self, "device_authorization_endpoint")

    @_builtins.property
    @pulumi.getter(name="endSessionEndpoint")
    def end_session_endpoint(self) -> _builtins.str:
        """
        The RP-initiated logout endpoint, empty if the instance does not advertise one.
        """
        return pulumi.get(self, "end_session_endpoint")

    @_builtins.property
    @pulumi.getter(name="grantTypesSupported")
    def grant_types_supported(self) -> Sequence[_builtins.str]:
        """
        The supported OAuth 2.0 grant types.
        """
        return pulumi.get(self, "grant_types_supported")

    @_builtins.property
    @pulumi.getter(name="idTokenSigningAlgValuesSupported")
    def id_token_signing_alg_values_supported(self) -> Sequence[_builtins.str]:
        """
        The supported ID token signing algorithms.
        """
        return pulumi.get(self, "id_token_signing_alg_values_supported")

    @_builtins.property
    @pulumi.getter(name="introspectionEndpoint")
    def introspection_endpoint(self) -> _builtins.str:
        """
        The token introspection endpoint, empty if the instance does not advertise one.
        """
        return pulumi.get(self, "introspection_endpoint")

    @_builtins.property
    @pulumi.getter
    def issuer(self) -> _builtins.str:
        """
        The issuer URL, i.e. the base URL of the instance.
        """
        return pulumi.get(self, "issuer")

    @_builtins.property
    @pulumi.getter(name="jwksUri")
    def jwks_uri(self) -> _builtins.str:
        """
        The URL of the JSON Web Key Set used to verify issued tokens.
        """
        return pulumi.get(self, "jwks_uri")

    @_builtins.property
    @pulumi.getter(name="responseTypesSupported")
    def response_types_supported(self) -> Sequence[_builtins.str]:
        """
        The supported response types.
        """
        return pulumi.get(self, "response_types_supported")

    @_builtins.property
    @pulumi.getter(name="scopesSupported")
    def scopes_supported(self) -> Sequence[_builtins.str]:
        """
        The supported scopes.
        """
        return pulumi.get(self, "scopes_supported")

    @_builtins.property
    @pulumi.getter(name="subjectTypesSupported")
    def subject_types_supported(self) -> Sequence[_builtins.str]:
        """
        The supported subject identifier types.
        """
        return pulumi.get(self, "subject_types_supported")

    @_builtins.property
    @pulumi.getter(name="tokenEndpoint")
    def token_endpoint(self) -> _builtins.str:
        """
        The OAuth 2.0 token endpoint.
        """
        return pulumi.get(self, "token_endpoint")

    @_builtins.property
    @pulumi.getter(name="tokenEndpointAuthMethodsSupported")
    def token_endpoint_auth_methods_supported(self) -> Sequence[_builtins.str]:
        """
        The supported client authentication methods at the token endpoint.
        """
        return pulumi.get(self, "token_endpoint_auth_methods_supported")

    @_builtins.property
    @pulumi.getter(name="userinfoEndpoint")
    def userinfo_endpoint(self) -> _builtins.str:
        """
        The OIDC userinfo endpoint.
        """
        return pulumi.get(self, "userinfo_endpoint")


class AwaitableGetOpenIdConfigurationResult(GetOpenIdConfigurationResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetOpenIdConfigurationResult(
            authorization_endpoint=self.authorization_endpoint,
            claims_supported=self.claims_supported,
            code_challenge_methods_supported=self.code_challenge_methods_supported,
            device_authorization_endpoint=self.device_authorization_endpoint,
            end_session_endpoint=self.end_session_endpoint,
            grant_types_supported=self.grant_types_supported,
            id_token_signing_alg_values_supported=self.id_token_signing_alg_values_supported,
            introspection_endpoint=self.introspection_endpoint,
            issuer=self.issuer,
            jwks_uri=self.jwks_uri,
            response_types_supported=self.response_types_supported,
            scopes_supported=self.scopes_supported,
            subject_types_supported=self.subject_types_supported,
            token_endpoint=self.token_endpoint,
            token_endpoint_auth_methods_supported=self.token_endpoint_auth_methods_supported,
            userinfo_endpoint=self.userinfo_endpoint)


def get_open_id_configuration(opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetOpenIdConfigurationResult:
    """
    Reads the OpenID Connect discovery document of the Pocket-ID instance: issuer, endpoints, JWKS URI and supported capabilities. Use it to configure applications that consume the instance as an OIDC provider.
    """
    __args__ = dict()
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('pocket-id:index:getOpenIdConfiguration', __args__, opts=opts, typ=GetOpenIdConfigurationResult).value

    return AwaitableGetOpenIdConfigurationResult(
        authorization_endpoint=pulumi.get(__ret__, 'authorization_endpoint'),
        claims_supported=pulumi.get(__ret__, 'claims_supported'),
        code_challenge_methods_supported=pulumi.get(__ret__, 'code_challenge_methods_supported'),
        device_authorization_endpoint=pulumi.get(__ret__, 'device_authorization_endpoint'),
        end_session_endpoint=pulumi.get(__ret__, 'end_session_endpoint'),
        grant_types_supported=pulumi.get(__ret__, 'grant_types_supported'),
        id_token_signing_alg_values_supported=pulumi.get(__ret__, 'id_token_signing_alg_values_supported'),
        introspection_endpoint=pulumi.get(__ret__, 'introspection_endpoint'),
        issuer=pulumi.get(__ret__, 'issuer'),
        jwks_uri=pulumi.get(__ret__, 'jwks_uri'),
        response_types_supported=pulumi.get(__ret__, 'response_types_supported'),
        scopes_supported=pulumi.get(__ret__, 'scopes_supported'),
        subject_types_supported=pulumi.get(__ret__, 'subject_types_supported'),
        token_endpoint=pulumi.get(__ret__, 'token_endpoint'),
        token_endpoint_auth_methods_supported=pulumi.get(__ret__, 'token_endpoint_auth_methods_supported'),
        userinfo_endpoint=pulumi.get(__ret__, 'userinfo_endpoint'))
def get_open_id_configuration_output(opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetOpenIdConfigurationResult]:
    """
    Reads the OpenID Connect discovery document of the Pocket-ID instance: issuer, endpoints, JWKS URI and supported capabilities. Use it to configure applications that consume the instance as an OIDC provider.
    """
    __args__ = dict()
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('pocket-id:index:getOpenIdConfiguration', __args__, opts=opts, typ=GetOpenIdConfigurationResult)
    return __ret__.apply(lambda __response__: GetOpenIdConfigurationResult(
        authorization_endpoint=pulumi.get(__response__, 'authorization_endpoint'),
        claims_supported=pulumi.get(__response__, 'claims_supported'),
        code_challenge_methods_supported=pulumi.get(__response__, 'code_challenge_methods_supported'),
        device_authorization_endpoint=pulumi.get(__response__, 'device_authorization_endpoint'),
        end_session_endpoint=pulumi.get(__response__, 'end_session_endpoint'),
        grant_types_supported=pulumi.get(__response__, 'grant_types_supported'),
        id_token_signing_alg_values_supported=pulumi.get(__response__, 'id_token_signing_alg_values_supported'),
        introspection_endpoint=pulumi.get(__response__, 'introspection_endpoint'),
        issuer=pulumi.get(__response__, 'issuer'),
        jwks_uri=pulumi.get(__response__, 'jwks_uri'),
        response_types_supported=pulumi.get(__response__, 'response_types_supported'),
        scopes_supported=pulumi.get(__response__, 'scopes_supported'),
        subject_types_supported=pulumi.get(__response__, 'subject_types_supported'),
        token_endpoint=pulumi.get(__response__, 'token_endpoint'),
        token_endpoint_auth_methods_supported=pulumi.get(__response__, 'token_endpoint_auth_methods_supported'),
        userinfo_endpoint=pulumi.get(__response__, 'userinfo_endpoint')))
