# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['OidcClientArgs', 'OidcClient']

@pulumi.input_type
class OidcClientArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 access_token_duration_minutes: pulumi.Input[Optional[_builtins.int]] = None,
                 allowed_user_group_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 backchannel_logout_url: pulumi.Input[Optional[_builtins.str]] = None,
                 callback_urls: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 client_id: pulumi.Input[Optional[_builtins.str]] = None,
                 credentials: pulumi.Input[Optional['OidcClientCredentialsArgs']] = None,
                 dark_logo: pulumi.Input[Optional[Union[pulumi.Asset, pulumi.Archive]]] = None,
                 dark_logo_url: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 is_public: pulumi.Input[Optional[_builtins.bool]] = None,
                 launch_url: pulumi.Input[Optional[_builtins.str]] = None,
                 logo: pulumi.Input[Optional[Union[pulumi.Asset, pulumi.Archive]]] = None,
                 logo_url: pulumi.Input[Optional[_builtins.str]] = None,
                 logout_callback_urls: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 pkce_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 refresh_token_duration_minutes: pulumi.Input[Optional[_builtins.int]] = None,
                 requires_pushed_authorization_requests: pulumi.Input[Optional[_builtins.bool]] = None,
                 requires_reauthentication: pulumi.Input[Optional[_builtins.bool]] = None,
                 skip_consent: pulumi.Input[Optional[_builtins.bool]] = None):
        """
        The set of arguments for constructing a OidcClient resource.

        :param pulumi.Input[_builtins.str] name: The display name of the client (50 characters max).
        :param pulumi.Input[_builtins.int] access_token_duration_minutes: The access token lifetime in minutes. Pocket-ID's default applies when unset.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_user_group_ids: The IDs of the user groups allowed to use the client. Authoritative: the set is replaced on every update, and the client is restricted to these groups when the list is non-empty (unrestricted when empty).
        :param pulumi.Input[_builtins.str] backchannel_logout_url: The URL called for OIDC back-channel logout.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] callback_urls: The allowed redirect URLs.
        :param pulumi.Input[_builtins.str] client_id: The ID of the client. Generated by Pocket-ID when unset. Changing it replaces the client.
        :param pulumi.Input['OidcClientCredentialsArgs'] credentials: The credentials of the client managed here (federated identities).
        :param pulumi.Input[Union[pulumi.Asset, pulumi.Archive]] dark_logo: The dark mode client logo (PNG, JPG or SVG) uploaded from a file, as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file and removing it deletes the logo. Mutually exclusive with darkLogoUrl. An asset cannot be read back: after an import it is empty and must be set in the program, which uploads the logo again if it differs from the served one.
        :param pulumi.Input[_builtins.str] dark_logo_url: A URL from which Pocket-ID fetches the dark mode logo. When unset, the dark logo is removed. It is not read back from the API. Mutually exclusive with darkLogo (uploaded file).
        :param pulumi.Input[_builtins.str] description: A description of the client (150 characters max).
        :param pulumi.Input[_builtins.bool] is_public: Whether the client is public (no client secret, PKCE recommended).
        :param pulumi.Input[_builtins.str] launch_url: The URL used to launch the application from the Pocket-ID dashboard.
        :param pulumi.Input[Union[pulumi.Asset, pulumi.Archive]] logo: The client logo (PNG, JPG or SVG) uploaded from a file, as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file and removing it deletes the logo. Mutually exclusive with logoUrl. An asset cannot be read back: after an import it is empty and must be set in the program, which uploads the logo again if it differs from the served one.
        :param pulumi.Input[_builtins.str] logo_url: A URL from which Pocket-ID fetches the client logo. When unset, the logo is removed. It is not read back from the API. Mutually exclusive with logo (uploaded file).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] logout_callback_urls: The allowed post-logout redirect URLs.
        :param pulumi.Input[_builtins.bool] pkce_enabled: Whether PKCE is required for the client.
        :param pulumi.Input[_builtins.int] refresh_token_duration_minutes: The refresh token lifetime in minutes. Pocket-ID's default applies when unset.
        :param pulumi.Input[_builtins.bool] requires_pushed_authorization_requests: Whether the client must use pushed authorization requests (PAR).
        :param pulumi.Input[_builtins.bool] requires_reauthentication: Whether users must re-authenticate on every authorization.
        :param pulumi.Input[_builtins.bool] skip_consent: Whether the consent screen is skipped for this client.
        """
        pulumi.set(__self__, "name", name)
        if access_token_duration_minutes is not None:
            pulumi.set(__self__, "access_token_duration_minutes", access_token_duration_minutes)
        if allowed_user_group_ids is not None:
            pulumi.set(__self__, "allowed_user_group_ids", allowed_user_group_ids)
        if backchannel_logout_url is not None:
            pulumi.set(__self__, "backchannel_logout_url", backchannel_logout_url)
        if callback_urls is not None:
            pulumi.set(__self__, "callback_urls", callback_urls)
        if client_id is not None:
            pulumi.set(__self__, "client_id", client_id)
        if credentials is not None:
            pulumi.set(__self__, "credentials", credentials)
        if dark_logo is not None:
            pulumi.set(__self__, "dark_logo", dark_logo)
        if dark_logo_url is not None:
            pulumi.set(__self__, "dark_logo_url", dark_logo_url)
        if description is not None:
            pulumi.set(__self__, "description", description)
        if is_public is not None:
            pulumi.set(__self__, "is_public", is_public)
        if launch_url is not None:
            pulumi.set(__self__, "launch_url", launch_url)
        if logo is not None:
            pulumi.set(__self__, "logo", logo)
        if logo_url is not None:
            pulumi.set(__self__, "logo_url", logo_url)
        if logout_callback_urls is not None:
            pulumi.set(__self__, "logout_callback_urls", logout_callback_urls)
        if pkce_enabled is not None:
            pulumi.set(__self__, "pkce_enabled", pkce_enabled)
        if refresh_token_duration_minutes is not None:
            pulumi.set(__self__, "refresh_token_duration_minutes", refresh_token_duration_minutes)
        if requires_pushed_authorization_requests is not None:
            pulumi.set(__self__, "requires_pushed_authorization_requests", requires_pushed_authorization_requests)
        if requires_reauthentication is not None:
            pulumi.set(__self__, "requires_reauthentication", requires_reauthentication)
        if skip_consent is not None:
            pulumi.set(__self__, "skip_consent", skip_consent)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        """
        The display name of the client (50 characters max).
        """
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="accessTokenDurationMinutes")
    def access_token_duration_minutes(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The access token lifetime in minutes. Pocket-ID's default applies when unset.
        """
        return pulumi.get(self, "access_token_duration_minutes")

    @access_token_duration_minutes.setter
    def access_token_duration_minutes(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "access_token_duration_minutes", value)

    @_builtins.property
    @pulumi.getter(name="allowedUserGroupIds")
    def allowed_user_group_ids(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The IDs of the user groups allowed to use the client. Authoritative: the set is replaced on every update, and the client is restricted to these groups when the list is non-empty (unrestricted when empty).
        """
        return pulumi.get(self, "allowed_user_group_ids")

    @allowed_user_group_ids.setter
    def allowed_user_group_ids(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "allowed_user_group_ids", value)

    @_builtins.property
    @pulumi.getter(name="backchannelLogoutUrl")
    def backchannel_logout_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The URL called for OIDC back-channel logout.
        """
        return pulumi.get(self, "backchannel_logout_url")

    @backchannel_logout_url.setter
    def backchannel_logout_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "backchannel_logout_url", value)

    @_builtins.property
    @pulumi.getter(name="callbackUrls")
    def callback_urls(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The allowed redirect URLs.
        """
        return pulumi.get(self, "callback_urls")

    @callback_urls.setter
    def callback_urls(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "callback_urls", value)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The ID of the client. Generated by Pocket-ID when unset. Changing it replaces the client.
        """
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "client_id", value)

    @_builtins.property
    @pulumi.getter
    def credentials(self) -> pulumi.Input[Optional['OidcClientCredentialsArgs']]:
        """
        The credentials of the client managed here (federated identities).
        """
        return pulumi.get(self, "credentials")

    @credentials.setter
    def credentials(self, value: pulumi.Input[Optional['OidcClientCredentialsArgs']]):
        pulumi.set(self, "credentials", value)

    @_builtins.property
    @pulumi.getter(name="darkLogo")
    def dark_logo(self) -> pulumi.Input[Optional[Union[pulumi.Asset, pulumi.Archive]]]:
        """
        The dark mode client logo (PNG, JPG or SVG) uploaded from a file, as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file and removing it deletes the logo. Mutually exclusive with darkLogoUrl. An asset cannot be read back: after an import it is empty and must be set in the program, which uploads the logo again if it differs from the served one.
        """
        return pulumi.get(self, "dark_logo")

    @dark_logo.setter
    def dark_logo(self, value: pulumi.Input[Optional[Union[pulumi.Asset, pulumi.Archive]]]):
        pulumi.set(self, "dark_logo", value)

    @_builtins.property
    @pulumi.getter(name="darkLogoUrl")
    def dark_logo_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A URL from which Pocket-ID fetches the dark mode logo. When unset, the dark logo is removed. It is not read back from the API. Mutually exclusive with darkLogo (uploaded file).
        """
        return pulumi.get(self, "dark_logo_url")

    @dark_logo_url.setter
    def dark_logo_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "dark_logo_url", value)

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A description of the client (150 characters max).
        """
        return pulumi.get(self, "description")

    @description.setter
    def description(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "description", value)

    @_builtins.property
    @pulumi.getter(name="isPublic")
    def is_public(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the client is public (no client secret, PKCE recommended).
        """
        return pulumi.get(self, "is_public")

    @is_public.setter
    def is_public(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "is_public", value)

    @_builtins.property
    @pulumi.getter(name="launchUrl")
    def launch_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The URL used to launch the application from the Pocket-ID dashboard.
        """
        return pulumi.get(self, "launch_url")

    @launch_url.setter
    def launch_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "launch_url", value)

    @_builtins.property
    @pulumi.getter
    def logo(self) -> pulumi.Input[Optional[Union[pulumi.Asset, pulumi.Archive]]]:
        """
        The client logo (PNG, JPG or SVG) uploaded from a file, as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file and removing it deletes the logo. Mutually exclusive with logoUrl. An asset cannot be read back: after an import it is empty and must be set in the program, which uploads the logo again if it differs from the served one.
        """
        return pulumi.get(self, "logo")

    @logo.setter
    def logo(self, value: pulumi.Input[Optional[Union[pulumi.Asset, pulumi.Archive]]]):
        pulumi.set(self, "logo", value)

    @_builtins.property
    @pulumi.getter(name="logoUrl")
    def logo_url(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        A URL from which Pocket-ID fetches the client logo. When unset, the logo is removed. It is not read back from the API. Mutually exclusive with logo (uploaded file).
        """
        return pulumi.get(self, "logo_url")

    @logo_url.setter
    def logo_url(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "logo_url", value)

    @_builtins.property
    @pulumi.getter(name="logoutCallbackUrls")
    def logout_callback_urls(self) -> pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]:
        """
        The allowed post-logout redirect URLs.
        """
        return pulumi.get(self, "logout_callback_urls")

    @logout_callback_urls.setter
    def logout_callback_urls(self, value: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "logout_callback_urls", value)

    @_builtins.property
    @pulumi.getter(name="pkceEnabled")
    def pkce_enabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether PKCE is required for the client.
        """
        return pulumi.get(self, "pkce_enabled")

    @pkce_enabled.setter
    def pkce_enabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "pkce_enabled", value)

    @_builtins.property
    @pulumi.getter(name="refreshTokenDurationMinutes")
    def refresh_token_duration_minutes(self) -> pulumi.Input[Optional[_builtins.int]]:
        """
        The refresh token lifetime in minutes. Pocket-ID's default applies when unset.
        """
        return pulumi.get(self, "refresh_token_duration_minutes")

    @refresh_token_duration_minutes.setter
    def refresh_token_duration_minutes(self, value: pulumi.Input[Optional[_builtins.int]]):
        pulumi.set(self, "refresh_token_duration_minutes", value)

    @_builtins.property
    @pulumi.getter(name="requiresPushedAuthorizationRequests")
    def requires_pushed_authorization_requests(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the client must use pushed authorization requests (PAR).
        """
        return pulumi.get(self, "requires_pushed_authorization_requests")

    @requires_pushed_authorization_requests.setter
    def requires_pushed_authorization_requests(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "requires_pushed_authorization_requests", value)

    @_builtins.property
    @pulumi.getter(name="requiresReauthentication")
    def requires_reauthentication(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether users must re-authenticate on every authorization.
        """
        return pulumi.get(self, "requires_reauthentication")

    @requires_reauthentication.setter
    def requires_reauthentication(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "requires_reauthentication", value)

    @_builtins.property
    @pulumi.getter(name="skipConsent")
    def skip_consent(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the consent screen is skipped for this client.
        """
        return pulumi.get(self, "skip_consent")

    @skip_consent.setter
    def skip_consent(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "skip_consent", value)


@pulumi.type_token("pocket-id:index:OidcClient")
class OidcClient(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_token_duration_minutes: pulumi.Input[Optional[_builtins.int]] = None,
                 allowed_user_group_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 backchannel_logout_url: pulumi.Input[Optional[_builtins.str]] = None,
                 callback_urls: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 client_id: pulumi.Input[Optional[_builtins.str]] = None,
                 credentials: pulumi.Input[Optional[Union['OidcClientCredentialsArgs', 'OidcClientCredentialsArgsDict', 'outputs.OidcClientCredentials']]] = None,
                 dark_logo: pulumi.Input[Optional[Union[pulumi.Asset, pulumi.Archive]]] = None,
                 dark_logo_url: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 is_public: pulumi.Input[Optional[_builtins.bool]] = None,
                 launch_url: pulumi.Input[Optional[_builtins.str]] = None,
                 logo: pulumi.Input[Optional[Union[pulumi.Asset, pulumi.Archive]]] = None,
                 logo_url: pulumi.Input[Optional[_builtins.str]] = None,
                 logout_callback_urls: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 pkce_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 refresh_token_duration_minutes: pulumi.Input[Optional[_builtins.int]] = None,
                 requires_pushed_authorization_requests: pulumi.Input[Optional[_builtins.bool]] = None,
                 requires_reauthentication: pulumi.Input[Optional[_builtins.bool]] = None,
                 skip_consent: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        """
        An OIDC client of Pocket-ID. The client never creates a secret by itself; use OidcClientSecret to generate one. The allowed user groups are owned by this resource. The logos are set either from a URL (logoUrl, darkLogoUrl) or from an uploaded file (logo, darkLogo), never both for the same variant.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.int] access_token_duration_minutes: The access token lifetime in minutes. Pocket-ID's default applies when unset.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] allowed_user_group_ids: The IDs of the user groups allowed to use the client. Authoritative: the set is replaced on every update, and the client is restricted to these groups when the list is non-empty (unrestricted when empty).
        :param pulumi.Input[_builtins.str] backchannel_logout_url: The URL called for OIDC back-channel logout.
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] callback_urls: The allowed redirect URLs.
        :param pulumi.Input[_builtins.str] client_id: The ID of the client. Generated by Pocket-ID when unset. Changing it replaces the client.
        :param pulumi.Input[Union['OidcClientCredentialsArgs', 'OidcClientCredentialsArgsDict', 'outputs.OidcClientCredentials']] credentials: The credentials of the client managed here (federated identities).
        :param pulumi.Input[Union[pulumi.Asset, pulumi.Archive]] dark_logo: The dark mode client logo (PNG, JPG or SVG) uploaded from a file, as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file and removing it deletes the logo. Mutually exclusive with darkLogoUrl. An asset cannot be read back: after an import it is empty and must be set in the program, which uploads the logo again if it differs from the served one.
        :param pulumi.Input[_builtins.str] dark_logo_url: A URL from which Pocket-ID fetches the dark mode logo. When unset, the dark logo is removed. It is not read back from the API. Mutually exclusive with darkLogo (uploaded file).
        :param pulumi.Input[_builtins.str] description: A description of the client (150 characters max).
        :param pulumi.Input[_builtins.bool] is_public: Whether the client is public (no client secret, PKCE recommended).
        :param pulumi.Input[_builtins.str] launch_url: The URL used to launch the application from the Pocket-ID dashboard.
        :param pulumi.Input[Union[pulumi.Asset, pulumi.Archive]] logo: The client logo (PNG, JPG or SVG) uploaded from a file, as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file and removing it deletes the logo. Mutually exclusive with logoUrl. An asset cannot be read back: after an import it is empty and must be set in the program, which uploads the logo again if it differs from the served one.
        :param pulumi.Input[_builtins.str] logo_url: A URL from which Pocket-ID fetches the client logo. When unset, the logo is removed. It is not read back from the API. Mutually exclusive with logo (uploaded file).
        :param pulumi.Input[Sequence[pulumi.Input[_builtins.str]]] logout_callback_urls: The allowed post-logout redirect URLs.
        :param pulumi.Input[_builtins.str] name: The display name of the client (50 characters max).
        :param pulumi.Input[_builtins.bool] pkce_enabled: Whether PKCE is required for the client.
        :param pulumi.Input[_builtins.int] refresh_token_duration_minutes: The refresh token lifetime in minutes. Pocket-ID's default applies when unset.
        :param pulumi.Input[_builtins.bool] requires_pushed_authorization_requests: Whether the client must use pushed authorization requests (PAR).
        :param pulumi.Input[_builtins.bool] requires_reauthentication: Whether users must re-authenticate on every authorization.
        :param pulumi.Input[_builtins.bool] skip_consent: Whether the consent screen is skipped for this client.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: OidcClientArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        An OIDC client of Pocket-ID. The client never creates a secret by itself; use OidcClientSecret to generate one. The allowed user groups are owned by this resource. The logos are set either from a URL (logoUrl, darkLogoUrl) or from an uploaded file (logo, darkLogo), never both for the same variant.

        :param str resource_name: The name of the resource.
        :param OidcClientArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(OidcClientArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 access_token_duration_minutes: pulumi.Input[Optional[_builtins.int]] = None,
                 allowed_user_group_ids: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 backchannel_logout_url: pulumi.Input[Optional[_builtins.str]] = None,
                 callback_urls: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 client_id: pulumi.Input[Optional[_builtins.str]] = None,
                 credentials: pulumi.Input[Optional[Union['OidcClientCredentialsArgs', 'OidcClientCredentialsArgsDict', 'outputs.OidcClientCredentials']]] = None,
                 dark_logo: pulumi.Input[Optional[Union[pulumi.Asset, pulumi.Archive]]] = None,
                 dark_logo_url: pulumi.Input[Optional[_builtins.str]] = None,
                 description: pulumi.Input[Optional[_builtins.str]] = None,
                 is_public: pulumi.Input[Optional[_builtins.bool]] = None,
                 launch_url: pulumi.Input[Optional[_builtins.str]] = None,
                 logo: pulumi.Input[Optional[Union[pulumi.Asset, pulumi.Archive]]] = None,
                 logo_url: pulumi.Input[Optional[_builtins.str]] = None,
                 logout_callback_urls: pulumi.Input[Optional[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: pulumi.Input[Optional[_builtins.str]] = None,
                 pkce_enabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 refresh_token_duration_minutes: pulumi.Input[Optional[_builtins.int]] = None,
                 requires_pushed_authorization_requests: pulumi.Input[Optional[_builtins.bool]] = None,
                 requires_reauthentication: pulumi.Input[Optional[_builtins.bool]] = None,
                 skip_consent: pulumi.Input[Optional[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = OidcClientArgs.__new__(OidcClientArgs)

            __props__.__dict__["access_token_duration_minutes"] = access_token_duration_minutes
            __props__.__dict__["allowed_user_group_ids"] = allowed_user_group_ids
            __props__.__dict__["backchannel_logout_url"] = backchannel_logout_url
            __props__.__dict__["callback_urls"] = callback_urls
            __props__.__dict__["client_id"] = client_id
            __props__.__dict__["credentials"] = credentials
            __props__.__dict__["dark_logo"] = dark_logo
            __props__.__dict__["dark_logo_url"] = dark_logo_url
            __props__.__dict__["description"] = description
            __props__.__dict__["is_public"] = is_public
            __props__.__dict__["launch_url"] = launch_url
            __props__.__dict__["logo"] = logo
            __props__.__dict__["logo_url"] = logo_url
            __props__.__dict__["logout_callback_urls"] = logout_callback_urls
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["pkce_enabled"] = pkce_enabled
            __props__.__dict__["refresh_token_duration_minutes"] = refresh_token_duration_minutes
            __props__.__dict__["requires_pushed_authorization_requests"] = requires_pushed_authorization_requests
            __props__.__dict__["requires_reauthentication"] = requires_reauthentication
            __props__.__dict__["skip_consent"] = skip_consent
            __props__.__dict__["client_type"] = None
            __props__.__dict__["dark_logo_sha256"] = None
            __props__.__dict__["has_dark_logo"] = None
            __props__.__dict__["has_logo"] = None
            __props__.__dict__["is_group_restricted"] = None
            __props__.__dict__["logo_sha256"] = None
            __props__.__dict__["pkce_supported"] = None
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["clientId"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(OidcClient, __self__).__init__(
            'pocket-id:index:OidcClient',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'OidcClient':
        """
        Get an existing OidcClient resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = OidcClientArgs.__new__(OidcClientArgs)

        __props__.__dict__["access_token_duration_minutes"] = None
        __props__.__dict__["allowed_user_group_ids"] = None
        __props__.__dict__["backchannel_logout_url"] = None
        __props__.__dict__["callback_urls"] = None
        __props__.__dict__["client_id"] = None
        __props__.__dict__["client_type"] = None
        __props__.__dict__["credentials"] = None
        __props__.__dict__["dark_logo"] = None
        __props__.__dict__["dark_logo_sha256"] = None
        __props__.__dict__["dark_logo_url"] = None
        __props__.__dict__["description"] = None
        __props__.__dict__["has_dark_logo"] = None
        __props__.__dict__["has_logo"] = None
        __props__.__dict__["is_group_restricted"] = None
        __props__.__dict__["is_public"] = None
        __props__.__dict__["launch_url"] = None
        __props__.__dict__["logo"] = None
        __props__.__dict__["logo_sha256"] = None
        __props__.__dict__["logo_url"] = None
        __props__.__dict__["logout_callback_urls"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["pkce_enabled"] = None
        __props__.__dict__["pkce_supported"] = None
        __props__.__dict__["refresh_token_duration_minutes"] = None
        __props__.__dict__["requires_pushed_authorization_requests"] = None
        __props__.__dict__["requires_reauthentication"] = None
        __props__.__dict__["skip_consent"] = None
        return OidcClient(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="accessTokenDurationMinutes")
    def access_token_duration_minutes(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The access token lifetime in minutes. Pocket-ID's default applies when unset.
        """
        return pulumi.get(self, "access_token_duration_minutes")

    @_builtins.property
    @pulumi.getter(name="allowedUserGroupIds")
    def allowed_user_group_ids(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        The IDs of the user groups allowed to use the client. Authoritative: the set is replaced on every update, and the client is restricted to these groups when the list is non-empty (unrestricted when empty).
        """
        return pulumi.get(self, "allowed_user_group_ids")

    @_builtins.property
    @pulumi.getter(name="backchannelLogoutUrl")
    def backchannel_logout_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The URL called for OIDC back-channel logout.
        """
        return pulumi.get(self, "backchannel_logout_url")

    @_builtins.property
    @pulumi.getter(name="callbackUrls")
    def callback_urls(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        The allowed redirect URLs.
        """
        return pulumi.get(self, "callback_urls")

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The ID of the client. Generated by Pocket-ID when unset. Changing it replaces the client.
        """
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter(name="clientType")
    def client_type(self) -> pulumi.Output[_builtins.str]:
        """
        The client type reported by Pocket-ID (confidential or public).
        """
        return pulumi.get(self, "client_type")

    @_builtins.property
    @pulumi.getter
    def credentials(self) -> pulumi.Output[Optional['outputs.OidcClientCredentials']]:
        """
        The credentials of the client managed here (federated identities).
        """
        return pulumi.get(self, "credentials")

    @_builtins.property
    @pulumi.getter(name="darkLogo")
    def dark_logo(self) -> pulumi.Output[Optional[Union[pulumi.Asset, pulumi.Archive]]]:
        """
        The dark mode client logo (PNG, JPG or SVG) uploaded from a file, as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file and removing it deletes the logo. Mutually exclusive with darkLogoUrl. An asset cannot be read back: after an import it is empty and must be set in the program, which uploads the logo again if it differs from the served one.
        """
        return pulumi.get(self, "dark_logo")

    @_builtins.property
    @pulumi.getter(name="darkLogoSha256")
    def dark_logo_sha256(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The hex SHA-256 digest of the uploaded dark mode logo (see darkLogo). At refresh it is the digest of the bytes currently served by Pocket-ID, so out-of-band changes show up as a diff.
        """
        return pulumi.get(self, "dark_logo_sha256")

    @_builtins.property
    @pulumi.getter(name="darkLogoUrl")
    def dark_logo_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A URL from which Pocket-ID fetches the dark mode logo. When unset, the dark logo is removed. It is not read back from the API. Mutually exclusive with darkLogo (uploaded file).
        """
        return pulumi.get(self, "dark_logo_url")

    @_builtins.property
    @pulumi.getter
    def description(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A description of the client (150 characters max).
        """
        return pulumi.get(self, "description")

    @_builtins.property
    @pulumi.getter(name="hasDarkLogo")
    def has_dark_logo(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the client has a dark mode logo.
        """
        return pulumi.get(self, "has_dark_logo")

    @_builtins.property
    @pulumi.getter(name="hasLogo")
    def has_logo(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether the client has a logo.
        """
        return pulumi.get(self, "has_logo")

    @_builtins.property
    @pulumi.getter(name="isGroupRestricted")
    def is_group_restricted(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether access is restricted to the allowed user groups.
        """
        return pulumi.get(self, "is_group_restricted")

    @_builtins.property
    @pulumi.getter(name="isPublic")
    def is_public(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the client is public (no client secret, PKCE recommended).
        """
        return pulumi.get(self, "is_public")

    @_builtins.property
    @pulumi.getter(name="launchUrl")
    def launch_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The URL used to launch the application from the Pocket-ID dashboard.
        """
        return pulumi.get(self, "launch_url")

    @_builtins.property
    @pulumi.getter
    def logo(self) -> pulumi.Output[Optional[Union[pulumi.Asset, pulumi.Archive]]]:
        """
        The client logo (PNG, JPG or SVG) uploaded from a file, as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file and removing it deletes the logo. Mutually exclusive with logoUrl. An asset cannot be read back: after an import it is empty and must be set in the program, which uploads the logo again if it differs from the served one.
        """
        return pulumi.get(self, "logo")

    @_builtins.property
    @pulumi.getter(name="logoSha256")
    def logo_sha256(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The hex SHA-256 digest of the uploaded logo (see logo). At refresh it is the digest of the bytes currently served by Pocket-ID, so out-of-band changes show up as a diff.
        """
        return pulumi.get(self, "logo_sha256")

    @_builtins.property
    @pulumi.getter(name="logoUrl")
    def logo_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        A URL from which Pocket-ID fetches the client logo. When unset, the logo is removed. It is not read back from the API. Mutually exclusive with logo (uploaded file).
        """
        return pulumi.get(self, "logo_url")

    @_builtins.property
    @pulumi.getter(name="logoutCallbackUrls")
    def logout_callback_urls(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        """
        The allowed post-logout redirect URLs.
        """
        return pulumi.get(self, "logout_callback_urls")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        """
        The display name of the client (50 characters max).
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="pkceEnabled")
    def pkce_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether PKCE is required for the client.
        """
        return pulumi.get(self, "pkce_enabled")

    @_builtins.property
    @pulumi.getter(name="pkceSupported")
    def pkce_supported(self) -> pulumi.Output[_builtins.bool]:
        """
        Whether PKCE is supported for this client.
        """
        return pulumi.get(self, "pkce_supported")

    @_builtins.property
    @pulumi.getter(name="refreshTokenDurationMinutes")
    def refresh_token_duration_minutes(self) -> pulumi.Output[Optional[_builtins.int]]:
        """
        The refresh token lifetime in minutes. Pocket-ID's default applies when unset.
        """
        return pulumi.get(self, "refresh_token_duration_minutes")

    @_builtins.property
    @pulumi.getter(name="requiresPushedAuthorizationRequests")
    def requires_pushed_authorization_requests(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the client must use pushed authorization requests (PAR).
        """
        return pulumi.get(self, "requires_pushed_authorization_requests")

    @_builtins.property
    @pulumi.getter(name="requiresReauthentication")
    def requires_reauthentication(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether users must re-authenticate on every authorization.
        """
        return pulumi.get(self, "requires_reauthentication")

    @_builtins.property
    @pulumi.getter(name="skipConsent")
    def skip_consent(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the consent screen is skipped for this client.
        """
        return pulumi.get(self, "skip_consent")

