# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._inputs import *

__all__ = ['OidcClientArgs', 'OidcClient']

@pulumi.input_type
class OidcClientArgs:
    def __init__(__self__, *,
                 name: pulumi.Input[_builtins.str],
                 callback_urls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 credentials: Optional[pulumi.Input['OidcClientCredentialsArgs']] = None,
                 is_group_restricted: Optional[pulumi.Input[_builtins.bool]] = None,
                 is_public: Optional[pulumi.Input[_builtins.bool]] = None,
                 launch_url: Optional[pulumi.Input[_builtins.str]] = None,
                 logout_callback_urls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 pkce_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 requires_pushed_authorization_requests: Optional[pulumi.Input[_builtins.bool]] = None,
                 requires_reauthentication: Optional[pulumi.Input[_builtins.bool]] = None,
                 skip_consent: Optional[pulumi.Input[_builtins.bool]] = None):
        """
        The set of arguments for constructing a OidcClient resource.
        """
        pulumi.set(__self__, "name", name)
        if callback_urls is not None:
            pulumi.set(__self__, "callback_urls", callback_urls)
        if client_id is not None:
            pulumi.set(__self__, "client_id", client_id)
        if credentials is not None:
            pulumi.set(__self__, "credentials", credentials)
        if is_group_restricted is not None:
            pulumi.set(__self__, "is_group_restricted", is_group_restricted)
        if is_public is not None:
            pulumi.set(__self__, "is_public", is_public)
        if launch_url is not None:
            pulumi.set(__self__, "launch_url", launch_url)
        if logout_callback_urls is not None:
            pulumi.set(__self__, "logout_callback_urls", logout_callback_urls)
        if pkce_enabled is not None:
            pulumi.set(__self__, "pkce_enabled", pkce_enabled)
        if requires_pushed_authorization_requests is not None:
            pulumi.set(__self__, "requires_pushed_authorization_requests", requires_pushed_authorization_requests)
        if requires_reauthentication is not None:
            pulumi.set(__self__, "requires_reauthentication", requires_reauthentication)
        if skip_consent is not None:
            pulumi.set(__self__, "skip_consent", skip_consent)

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Input[_builtins.str]:
        return pulumi.get(self, "name")

    @name.setter
    def name(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "name", value)

    @_builtins.property
    @pulumi.getter(name="callbackUrls")
    def callback_urls(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "callback_urls")

    @callback_urls.setter
    def callback_urls(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "callback_urls", value)

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "client_id")

    @client_id.setter
    def client_id(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "client_id", value)

    @_builtins.property
    @pulumi.getter
    def credentials(self) -> Optional[pulumi.Input['OidcClientCredentialsArgs']]:
        return pulumi.get(self, "credentials")

    @credentials.setter
    def credentials(self, value: Optional[pulumi.Input['OidcClientCredentialsArgs']]):
        pulumi.set(self, "credentials", value)

    @_builtins.property
    @pulumi.getter(name="isGroupRestricted")
    def is_group_restricted(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "is_group_restricted")

    @is_group_restricted.setter
    def is_group_restricted(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_group_restricted", value)

    @_builtins.property
    @pulumi.getter(name="isPublic")
    def is_public(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "is_public")

    @is_public.setter
    def is_public(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "is_public", value)

    @_builtins.property
    @pulumi.getter(name="launchUrl")
    def launch_url(self) -> Optional[pulumi.Input[_builtins.str]]:
        return pulumi.get(self, "launch_url")

    @launch_url.setter
    def launch_url(self, value: Optional[pulumi.Input[_builtins.str]]):
        pulumi.set(self, "launch_url", value)

    @_builtins.property
    @pulumi.getter(name="logoutCallbackUrls")
    def logout_callback_urls(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]:
        return pulumi.get(self, "logout_callback_urls")

    @logout_callback_urls.setter
    def logout_callback_urls(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]]):
        pulumi.set(self, "logout_callback_urls", value)

    @_builtins.property
    @pulumi.getter(name="pkceEnabled")
    def pkce_enabled(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "pkce_enabled")

    @pkce_enabled.setter
    def pkce_enabled(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "pkce_enabled", value)

    @_builtins.property
    @pulumi.getter(name="requiresPushedAuthorizationRequests")
    def requires_pushed_authorization_requests(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "requires_pushed_authorization_requests")

    @requires_pushed_authorization_requests.setter
    def requires_pushed_authorization_requests(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "requires_pushed_authorization_requests", value)

    @_builtins.property
    @pulumi.getter(name="requiresReauthentication")
    def requires_reauthentication(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "requires_reauthentication")

    @requires_reauthentication.setter
    def requires_reauthentication(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "requires_reauthentication", value)

    @_builtins.property
    @pulumi.getter(name="skipConsent")
    def skip_consent(self) -> Optional[pulumi.Input[_builtins.bool]]:
        return pulumi.get(self, "skip_consent")

    @skip_consent.setter
    def skip_consent(self, value: Optional[pulumi.Input[_builtins.bool]]):
        pulumi.set(self, "skip_consent", value)


@pulumi.type_token("pocket-id:index:OidcClient")
class OidcClient(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 callback_urls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 credentials: Optional[pulumi.Input[Union['OidcClientCredentialsArgs', 'OidcClientCredentialsArgsDict']]] = None,
                 is_group_restricted: Optional[pulumi.Input[_builtins.bool]] = None,
                 is_public: Optional[pulumi.Input[_builtins.bool]] = None,
                 launch_url: Optional[pulumi.Input[_builtins.str]] = None,
                 logout_callback_urls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 pkce_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 requires_pushed_authorization_requests: Optional[pulumi.Input[_builtins.bool]] = None,
                 requires_reauthentication: Optional[pulumi.Input[_builtins.bool]] = None,
                 skip_consent: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        """
        Create a OidcClient resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: OidcClientArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        Create a OidcClient resource with the given unique name, props, and options.
        :param str resource_name: The name of the resource.
        :param OidcClientArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(OidcClientArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 callback_urls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 client_id: Optional[pulumi.Input[_builtins.str]] = None,
                 credentials: Optional[pulumi.Input[Union['OidcClientCredentialsArgs', 'OidcClientCredentialsArgsDict']]] = None,
                 is_group_restricted: Optional[pulumi.Input[_builtins.bool]] = None,
                 is_public: Optional[pulumi.Input[_builtins.bool]] = None,
                 launch_url: Optional[pulumi.Input[_builtins.str]] = None,
                 logout_callback_urls: Optional[pulumi.Input[Sequence[pulumi.Input[_builtins.str]]]] = None,
                 name: Optional[pulumi.Input[_builtins.str]] = None,
                 pkce_enabled: Optional[pulumi.Input[_builtins.bool]] = None,
                 requires_pushed_authorization_requests: Optional[pulumi.Input[_builtins.bool]] = None,
                 requires_reauthentication: Optional[pulumi.Input[_builtins.bool]] = None,
                 skip_consent: Optional[pulumi.Input[_builtins.bool]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = OidcClientArgs.__new__(OidcClientArgs)

            __props__.__dict__["callback_urls"] = callback_urls
            __props__.__dict__["client_id"] = client_id
            __props__.__dict__["credentials"] = credentials
            __props__.__dict__["is_group_restricted"] = is_group_restricted
            __props__.__dict__["is_public"] = is_public
            __props__.__dict__["launch_url"] = launch_url
            __props__.__dict__["logout_callback_urls"] = logout_callback_urls
            if name is None and not opts.urn:
                raise TypeError("Missing required property 'name'")
            __props__.__dict__["name"] = name
            __props__.__dict__["pkce_enabled"] = pkce_enabled
            __props__.__dict__["requires_pushed_authorization_requests"] = requires_pushed_authorization_requests
            __props__.__dict__["requires_reauthentication"] = requires_reauthentication
            __props__.__dict__["skip_consent"] = skip_consent
            __props__.__dict__["has_dark_logo"] = None
            __props__.__dict__["has_logo"] = None
            __props__.__dict__["pkce_supported"] = None
        super(OidcClient, __self__).__init__(
            'pocket-id:index:OidcClient',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'OidcClient':
        """
        Get an existing OidcClient resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = OidcClientArgs.__new__(OidcClientArgs)

        __props__.__dict__["callback_urls"] = None
        __props__.__dict__["client_id"] = None
        __props__.__dict__["credentials"] = None
        __props__.__dict__["has_dark_logo"] = None
        __props__.__dict__["has_logo"] = None
        __props__.__dict__["is_group_restricted"] = None
        __props__.__dict__["is_public"] = None
        __props__.__dict__["launch_url"] = None
        __props__.__dict__["logout_callback_urls"] = None
        __props__.__dict__["name"] = None
        __props__.__dict__["pkce_enabled"] = None
        __props__.__dict__["pkce_supported"] = None
        __props__.__dict__["requires_pushed_authorization_requests"] = None
        __props__.__dict__["requires_reauthentication"] = None
        __props__.__dict__["skip_consent"] = None
        return OidcClient(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter(name="callbackUrls")
    def callback_urls(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "callback_urls")

    @_builtins.property
    @pulumi.getter(name="clientId")
    def client_id(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "client_id")

    @_builtins.property
    @pulumi.getter
    def credentials(self) -> pulumi.Output[Optional['outputs.OidcClientCredentials']]:
        return pulumi.get(self, "credentials")

    @_builtins.property
    @pulumi.getter(name="hasDarkLogo")
    def has_dark_logo(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "has_dark_logo")

    @_builtins.property
    @pulumi.getter(name="hasLogo")
    def has_logo(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "has_logo")

    @_builtins.property
    @pulumi.getter(name="isGroupRestricted")
    def is_group_restricted(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "is_group_restricted")

    @_builtins.property
    @pulumi.getter(name="isPublic")
    def is_public(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "is_public")

    @_builtins.property
    @pulumi.getter(name="launchUrl")
    def launch_url(self) -> pulumi.Output[Optional[_builtins.str]]:
        return pulumi.get(self, "launch_url")

    @_builtins.property
    @pulumi.getter(name="logoutCallbackUrls")
    def logout_callback_urls(self) -> pulumi.Output[Optional[Sequence[_builtins.str]]]:
        return pulumi.get(self, "logout_callback_urls")

    @_builtins.property
    @pulumi.getter
    def name(self) -> pulumi.Output[_builtins.str]:
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter(name="pkceEnabled")
    def pkce_enabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "pkce_enabled")

    @_builtins.property
    @pulumi.getter(name="pkceSupported")
    def pkce_supported(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "pkce_supported")

    @_builtins.property
    @pulumi.getter(name="requiresPushedAuthorizationRequests")
    def requires_pushed_authorization_requests(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "requires_pushed_authorization_requests")

    @_builtins.property
    @pulumi.getter(name="requiresReauthentication")
    def requires_reauthentication(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "requires_reauthentication")

    @_builtins.property
    @pulumi.getter(name="skipConsent")
    def skip_consent(self) -> pulumi.Output[Optional[_builtins.bool]]:
        return pulumi.get(self, "skip_consent")

