# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs
from ._enums import *

__all__ = [
    'ApiCimdAccess',
    'ApiPermissionState',
    'OidcClientCredentials',
    'OidcFederatedIdentity',
]

@pulumi.output_type
class ApiCimdAccess(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "permissionKeys":
            suggest = "permission_keys"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in ApiCimdAccess. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        ApiCimdAccess.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        ApiCimdAccess.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 enabled: _builtins.bool,
                 permission_keys: Optional[Sequence[_builtins.str]] = None):
        """
        :param _builtins.bool enabled: Whether clients registered through a Client ID Metadata Document (CIMD) may use the API.
        :param Sequence[_builtins.str] permission_keys: The keys of the API permissions that such clients may request. Each key must be declared in `permissions`.
        """
        pulumi.set(__self__, "enabled", enabled)
        if permission_keys is not None:
            pulumi.set(__self__, "permission_keys", permission_keys)

    @_builtins.property
    @pulumi.getter
    def enabled(self) -> _builtins.bool:
        """
        Whether clients registered through a Client ID Metadata Document (CIMD) may use the API.
        """
        return pulumi.get(self, "enabled")

    @_builtins.property
    @pulumi.getter(name="permissionKeys")
    def permission_keys(self) -> Optional[Sequence[_builtins.str]]:
        """
        The keys of the API permissions that such clients may request. Each key must be declared in `permissions`.
        """
        return pulumi.get(self, "permission_keys")


@pulumi.output_type
class ApiPermissionState(dict):
    def __init__(__self__, *,
                 id: _builtins.str,
                 key: _builtins.str,
                 name: _builtins.str,
                 description: Optional[_builtins.str] = None):
        """
        :param _builtins.str id: The Pocket-ID identifier of the permission.
        :param _builtins.str key: The stable identifier of the permission, e.g. "read:orders". Unique within the API.
        :param _builtins.str name: The display name of the permission.
        :param _builtins.str description: A description of the permission.
        """
        pulumi.set(__self__, "id", id)
        pulumi.set(__self__, "key", key)
        pulumi.set(__self__, "name", name)
        if description is not None:
            pulumi.set(__self__, "description", description)

    @_builtins.property
    @pulumi.getter
    def id(self) -> _builtins.str:
        """
        The Pocket-ID identifier of the permission.
        """
        return pulumi.get(self, "id")

    @_builtins.property
    @pulumi.getter
    def key(self) -> _builtins.str:
        """
        The stable identifier of the permission, e.g. "read:orders". Unique within the API.
        """
        return pulumi.get(self, "key")

    @_builtins.property
    @pulumi.getter
    def name(self) -> _builtins.str:
        """
        The display name of the permission.
        """
        return pulumi.get(self, "name")

    @_builtins.property
    @pulumi.getter
    def description(self) -> Optional[_builtins.str]:
        """
        A description of the permission.
        """
        return pulumi.get(self, "description")


@pulumi.output_type
class OidcClientCredentials(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "federatedIdentities":
            suggest = "federated_identities"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in OidcClientCredentials. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        OidcClientCredentials.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        OidcClientCredentials.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 federated_identities: Optional[Sequence['outputs.OidcFederatedIdentity']] = None):
        """
        :param Sequence['OidcFederatedIdentity'] federated_identities: The federated identities allowed to authenticate as the client.
        """
        if federated_identities is not None:
            pulumi.set(__self__, "federated_identities", federated_identities)

    @_builtins.property
    @pulumi.getter(name="federatedIdentities")
    def federated_identities(self) -> Optional[Sequence['outputs.OidcFederatedIdentity']]:
        """
        The federated identities allowed to authenticate as the client.
        """
        return pulumi.get(self, "federated_identities")


@pulumi.output_type
class OidcFederatedIdentity(dict):
    @staticmethod
    def __key_warning(key: str):
        suggest = None
        if key == "replayProtection":
            suggest = "replay_protection"

        if suggest:
            pulumi.log.warn(f"Key '{key}' not found in OidcFederatedIdentity. Access the value via the '{suggest}' property getter instead.")

    def __getitem__(self, key: str) -> Any:
        OidcFederatedIdentity.__key_warning(key)
        return super().__getitem__(key)

    def get(self, key: str, default = None) -> Any:
        OidcFederatedIdentity.__key_warning(key)
        return super().get(key, default)

    def __init__(__self__, *,
                 issuer: _builtins.str,
                 audience: Optional[_builtins.str] = None,
                 jwks: Optional[_builtins.str] = None,
                 replay_protection: Optional[_builtins.bool] = None,
                 subject: Optional[_builtins.str] = None):
        """
        :param _builtins.str issuer: The issuer URL of the federated identity.
        :param _builtins.str audience: The expected audience of the federated identity.
        :param _builtins.str jwks: The URL or content of the JWKS used to verify the federated identity.
        :param _builtins.bool replay_protection: Whether tokens issued by the federated identity can only be used once.
        :param _builtins.str subject: The expected subject of the federated identity.
        """
        pulumi.set(__self__, "issuer", issuer)
        if audience is not None:
            pulumi.set(__self__, "audience", audience)
        if jwks is not None:
            pulumi.set(__self__, "jwks", jwks)
        if replay_protection is not None:
            pulumi.set(__self__, "replay_protection", replay_protection)
        if subject is not None:
            pulumi.set(__self__, "subject", subject)

    @_builtins.property
    @pulumi.getter
    def issuer(self) -> _builtins.str:
        """
        The issuer URL of the federated identity.
        """
        return pulumi.get(self, "issuer")

    @_builtins.property
    @pulumi.getter
    def audience(self) -> Optional[_builtins.str]:
        """
        The expected audience of the federated identity.
        """
        return pulumi.get(self, "audience")

    @_builtins.property
    @pulumi.getter
    def jwks(self) -> Optional[_builtins.str]:
        """
        The URL or content of the JWKS used to verify the federated identity.
        """
        return pulumi.get(self, "jwks")

    @_builtins.property
    @pulumi.getter(name="replayProtection")
    def replay_protection(self) -> Optional[_builtins.bool]:
        """
        Whether tokens issued by the federated identity can only be used once.
        """
        return pulumi.get(self, "replay_protection")

    @_builtins.property
    @pulumi.getter
    def subject(self) -> Optional[_builtins.str]:
        """
        The expected subject of the federated identity.
        """
        return pulumi.get(self, "subject")


