# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['UserArgs', 'User']

@pulumi.input_type
class UserArgs:
    def __init__(__self__, *,
                 username: pulumi.Input[_builtins.str],
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 email_verified: pulumi.Input[Optional[_builtins.bool]] = None,
                 first_name: pulumi.Input[Optional[_builtins.str]] = None,
                 is_admin: pulumi.Input[Optional[_builtins.bool]] = None,
                 last_name: pulumi.Input[Optional[_builtins.str]] = None,
                 locale: pulumi.Input[Optional[_builtins.str]] = None):
        """
        The set of arguments for constructing a User resource.

        :param pulumi.Input[_builtins.str] username: The unique login name of the user.
        :param pulumi.Input[_builtins.bool] disabled: Whether the user is disabled and cannot sign in.
        :param pulumi.Input[_builtins.str] display_name: The name displayed for the user. Pocket-ID may derive it from the first and last names when unset.
        :param pulumi.Input[_builtins.str] email: The email address of the user.
        :param pulumi.Input[_builtins.bool] email_verified: Whether the email address is considered verified.
        :param pulumi.Input[_builtins.str] first_name: The first name of the user.
        :param pulumi.Input[_builtins.bool] is_admin: Whether the user is an administrator.
        :param pulumi.Input[_builtins.str] last_name: The last name of the user.
        :param pulumi.Input[_builtins.str] locale: The locale of the user, for example en or fr.
        """
        pulumi.set(__self__, "username", username)
        if disabled is not None:
            pulumi.set(__self__, "disabled", disabled)
        if display_name is not None:
            pulumi.set(__self__, "display_name", display_name)
        if email is not None:
            pulumi.set(__self__, "email", email)
        if email_verified is not None:
            pulumi.set(__self__, "email_verified", email_verified)
        if first_name is not None:
            pulumi.set(__self__, "first_name", first_name)
        if is_admin is not None:
            pulumi.set(__self__, "is_admin", is_admin)
        if last_name is not None:
            pulumi.set(__self__, "last_name", last_name)
        if locale is not None:
            pulumi.set(__self__, "locale", locale)

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Input[_builtins.str]:
        """
        The unique login name of the user.
        """
        return pulumi.get(self, "username")

    @username.setter
    def username(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "username", value)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the user is disabled and cannot sign in.
        """
        return pulumi.get(self, "disabled")

    @disabled.setter
    def disabled(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "disabled", value)

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The name displayed for the user. Pocket-ID may derive it from the first and last names when unset.
        """
        return pulumi.get(self, "display_name")

    @display_name.setter
    def display_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "display_name", value)

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The email address of the user.
        """
        return pulumi.get(self, "email")

    @email.setter
    def email(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "email", value)

    @_builtins.property
    @pulumi.getter(name="emailVerified")
    def email_verified(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the email address is considered verified.
        """
        return pulumi.get(self, "email_verified")

    @email_verified.setter
    def email_verified(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "email_verified", value)

    @_builtins.property
    @pulumi.getter(name="firstName")
    def first_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The first name of the user.
        """
        return pulumi.get(self, "first_name")

    @first_name.setter
    def first_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "first_name", value)

    @_builtins.property
    @pulumi.getter(name="isAdmin")
    def is_admin(self) -> pulumi.Input[Optional[_builtins.bool]]:
        """
        Whether the user is an administrator.
        """
        return pulumi.get(self, "is_admin")

    @is_admin.setter
    def is_admin(self, value: pulumi.Input[Optional[_builtins.bool]]):
        pulumi.set(self, "is_admin", value)

    @_builtins.property
    @pulumi.getter(name="lastName")
    def last_name(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The last name of the user.
        """
        return pulumi.get(self, "last_name")

    @last_name.setter
    def last_name(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "last_name", value)

    @_builtins.property
    @pulumi.getter
    def locale(self) -> pulumi.Input[Optional[_builtins.str]]:
        """
        The locale of the user, for example en or fr.
        """
        return pulumi.get(self, "locale")

    @locale.setter
    def locale(self, value: pulumi.Input[Optional[_builtins.str]]):
        pulumi.set(self, "locale", value)


@pulumi.type_token("pocket-id:index:User")
class User(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 email_verified: pulumi.Input[Optional[_builtins.bool]] = None,
                 first_name: pulumi.Input[Optional[_builtins.str]] = None,
                 is_admin: pulumi.Input[Optional[_builtins.bool]] = None,
                 last_name: pulumi.Input[Optional[_builtins.str]] = None,
                 locale: pulumi.Input[Optional[_builtins.str]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        A Pocket-ID user. Group membership is managed with the UserGroupMembers resource.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[_builtins.bool] disabled: Whether the user is disabled and cannot sign in.
        :param pulumi.Input[_builtins.str] display_name: The name displayed for the user. Pocket-ID may derive it from the first and last names when unset.
        :param pulumi.Input[_builtins.str] email: The email address of the user.
        :param pulumi.Input[_builtins.bool] email_verified: Whether the email address is considered verified.
        :param pulumi.Input[_builtins.str] first_name: The first name of the user.
        :param pulumi.Input[_builtins.bool] is_admin: Whether the user is an administrator.
        :param pulumi.Input[_builtins.str] last_name: The last name of the user.
        :param pulumi.Input[_builtins.str] locale: The locale of the user, for example en or fr.
        :param pulumi.Input[_builtins.str] username: The unique login name of the user.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: UserArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        A Pocket-ID user. Group membership is managed with the UserGroupMembers resource.

        :param str resource_name: The name of the resource.
        :param UserArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(UserArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 disabled: pulumi.Input[Optional[_builtins.bool]] = None,
                 display_name: pulumi.Input[Optional[_builtins.str]] = None,
                 email: pulumi.Input[Optional[_builtins.str]] = None,
                 email_verified: pulumi.Input[Optional[_builtins.bool]] = None,
                 first_name: pulumi.Input[Optional[_builtins.str]] = None,
                 is_admin: pulumi.Input[Optional[_builtins.bool]] = None,
                 last_name: pulumi.Input[Optional[_builtins.str]] = None,
                 locale: pulumi.Input[Optional[_builtins.str]] = None,
                 username: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = UserArgs.__new__(UserArgs)

            __props__.__dict__["disabled"] = disabled
            __props__.__dict__["display_name"] = display_name
            __props__.__dict__["email"] = email
            __props__.__dict__["email_verified"] = email_verified
            __props__.__dict__["first_name"] = first_name
            __props__.__dict__["is_admin"] = is_admin
            __props__.__dict__["last_name"] = last_name
            __props__.__dict__["locale"] = locale
            if username is None and not opts.urn:
                raise TypeError("Missing required property 'username'")
            __props__.__dict__["username"] = username
        super(User, __self__).__init__(
            'pocket-id:index:User',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'User':
        """
        Get an existing User resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = UserArgs.__new__(UserArgs)

        __props__.__dict__["disabled"] = None
        __props__.__dict__["display_name"] = None
        __props__.__dict__["email"] = None
        __props__.__dict__["email_verified"] = None
        __props__.__dict__["first_name"] = None
        __props__.__dict__["is_admin"] = None
        __props__.__dict__["last_name"] = None
        __props__.__dict__["locale"] = None
        __props__.__dict__["username"] = None
        return User(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def disabled(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the user is disabled and cannot sign in.
        """
        return pulumi.get(self, "disabled")

    @_builtins.property
    @pulumi.getter(name="displayName")
    def display_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The name displayed for the user. Pocket-ID may derive it from the first and last names when unset.
        """
        return pulumi.get(self, "display_name")

    @_builtins.property
    @pulumi.getter
    def email(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The email address of the user.
        """
        return pulumi.get(self, "email")

    @_builtins.property
    @pulumi.getter(name="emailVerified")
    def email_verified(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the email address is considered verified.
        """
        return pulumi.get(self, "email_verified")

    @_builtins.property
    @pulumi.getter(name="firstName")
    def first_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The first name of the user.
        """
        return pulumi.get(self, "first_name")

    @_builtins.property
    @pulumi.getter(name="isAdmin")
    def is_admin(self) -> pulumi.Output[Optional[_builtins.bool]]:
        """
        Whether the user is an administrator.
        """
        return pulumi.get(self, "is_admin")

    @_builtins.property
    @pulumi.getter(name="lastName")
    def last_name(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The last name of the user.
        """
        return pulumi.get(self, "last_name")

    @_builtins.property
    @pulumi.getter
    def locale(self) -> pulumi.Output[Optional[_builtins.str]]:
        """
        The locale of the user, for example en or fr.
        """
        return pulumi.get(self, "locale")

    @_builtins.property
    @pulumi.getter
    def username(self) -> pulumi.Output[_builtins.str]:
        """
        The unique login name of the user.
        """
        return pulumi.get(self, "username")

