# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities

__all__ = ['UserGroupCustomClaimsArgs', 'UserGroupCustomClaims']

@pulumi.input_type
class UserGroupCustomClaimsArgs:
    def __init__(__self__, *,
                 claims: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]],
                 user_group_id: pulumi.Input[_builtins.str]):
        """
        The set of arguments for constructing a UserGroupCustomClaims resource.

        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] claims: The custom claims of the group, as key/value pairs. The set is authoritative: claims not listed are removed from the group.
        :param pulumi.Input[_builtins.str] user_group_id: The ID of the user group. Changing it replaces the resource.
        """
        pulumi.set(__self__, "claims", claims)
        pulumi.set(__self__, "user_group_id", user_group_id)

    @_builtins.property
    @pulumi.getter
    def claims(self) -> pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]:
        """
        The custom claims of the group, as key/value pairs. The set is authoritative: claims not listed are removed from the group.
        """
        return pulumi.get(self, "claims")

    @claims.setter
    def claims(self, value: pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]]):
        pulumi.set(self, "claims", value)

    @_builtins.property
    @pulumi.getter(name="userGroupId")
    def user_group_id(self) -> pulumi.Input[_builtins.str]:
        """
        The ID of the user group. Changing it replaces the resource.
        """
        return pulumi.get(self, "user_group_id")

    @user_group_id.setter
    def user_group_id(self, value: pulumi.Input[_builtins.str]):
        pulumi.set(self, "user_group_id", value)


@pulumi.type_token("pocket-id:index:UserGroupCustomClaims")
class UserGroupCustomClaims(pulumi.CustomResource):
    @overload
    def __init__(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 claims: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 user_group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        """
        The authoritative set of custom claims of a user group. Destroying the resource removes every custom claim from the group.

        :param str resource_name: The name of the resource.
        :param pulumi.ResourceOptions opts: Options for the resource.
        :param pulumi.Input[Mapping[str, pulumi.Input[_builtins.str]]] claims: The custom claims of the group, as key/value pairs. The set is authoritative: claims not listed are removed from the group.
        :param pulumi.Input[_builtins.str] user_group_id: The ID of the user group. Changing it replaces the resource.
        """
        ...
    @overload
    def __init__(__self__,
                 resource_name: str,
                 args: UserGroupCustomClaimsArgs,
                 opts: Optional[pulumi.ResourceOptions] = None):
        """
        The authoritative set of custom claims of a user group. Destroying the resource removes every custom claim from the group.

        :param str resource_name: The name of the resource.
        :param UserGroupCustomClaimsArgs args: The arguments to use to populate this resource's properties.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        ...
    def __init__(__self__, resource_name: str, *args, **kwargs):
        resource_args, opts = _utilities.get_resource_args_opts(UserGroupCustomClaimsArgs, pulumi.ResourceOptions, *args, **kwargs)
        if resource_args is not None:
            __self__._internal_init(resource_name, opts, **resource_args.__dict__)
        else:
            __self__._internal_init(resource_name, *args, **kwargs)

    def _internal_init(__self__,
                 resource_name: str,
                 opts: Optional[pulumi.ResourceOptions] = None,
                 claims: pulumi.Input[Optional[Mapping[str, pulumi.Input[_builtins.str]]]] = None,
                 user_group_id: pulumi.Input[Optional[_builtins.str]] = None,
                 __props__=None):
        opts = pulumi.ResourceOptions.merge(_utilities.get_resource_opts_defaults(), opts)
        if not isinstance(opts, pulumi.ResourceOptions):
            raise TypeError('Expected resource options to be a ResourceOptions instance')
        if opts.id is None:
            if __props__ is not None:
                raise TypeError('__props__ is only valid when passed in combination with a valid opts.id to get an existing resource')
            __props__ = UserGroupCustomClaimsArgs.__new__(UserGroupCustomClaimsArgs)

            if claims is None and not opts.urn:
                raise TypeError("Missing required property 'claims'")
            __props__.__dict__["claims"] = claims
            if user_group_id is None and not opts.urn:
                raise TypeError("Missing required property 'user_group_id'")
            __props__.__dict__["user_group_id"] = user_group_id
        replace_on_changes = pulumi.ResourceOptions(replace_on_changes=["userGroupId"])
        opts = pulumi.ResourceOptions.merge(opts, replace_on_changes)
        super(UserGroupCustomClaims, __self__).__init__(
            'pocket-id:index:UserGroupCustomClaims',
            resource_name,
            __props__,
            opts)

    @staticmethod
    def get(resource_name: str,
            id: pulumi.Input[str],
            opts: Optional[pulumi.ResourceOptions] = None) -> 'UserGroupCustomClaims':
        """
        Get an existing UserGroupCustomClaims resource's state with the given name, id, and optional extra
        properties used to qualify the lookup.

        :param str resource_name: The unique name of the resulting resource.
        :param pulumi.Input[str] id: The unique provider ID of the resource to lookup.
        :param pulumi.ResourceOptions opts: Options for the resource.
        """
        opts = pulumi.ResourceOptions.merge(opts, pulumi.ResourceOptions(id=id))

        __props__ = UserGroupCustomClaimsArgs.__new__(UserGroupCustomClaimsArgs)

        __props__.__dict__["claims"] = None
        __props__.__dict__["user_group_id"] = None
        return UserGroupCustomClaims(resource_name, opts=opts, __props__=__props__)

    @_builtins.property
    @pulumi.getter
    def claims(self) -> pulumi.Output[Mapping[str, _builtins.str]]:
        """
        The custom claims of the group, as key/value pairs. The set is authoritative: claims not listed are removed from the group.
        """
        return pulumi.get(self, "claims")

    @_builtins.property
    @pulumi.getter(name="userGroupId")
    def user_group_id(self) -> pulumi.Output[_builtins.str]:
        """
        The ID of the user group. Changing it replaces the resource.
        """
        return pulumi.get(self, "user_group_id")

