// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId.Outputs
{

    [OutputType]
    public sealed class FederatedIdentity
    {
        public readonly string? Audience;
        public readonly string Issuer;
        public readonly string? Jwks;
        public readonly bool? ReplayProtection;
        public readonly string? Subject;

        [OutputConstructor]
        private FederatedIdentity(
            string? audience,

            string issuer,

            string? jwks,

            bool? replayProtection,

            string? subject)
        {
            Audience = audience;
            Issuer = issuer;
            Jwks = jwks;
            ReplayProtection = replayProtection;
            Subject = subject;
        }
    }
}
