// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId.Outputs
{

    [OutputType]
    public sealed class OidcClientCredentials
    {
        public readonly ImmutableArray<Outputs.FederatedIdentity> FederatedIdentities;

        [OutputConstructor]
        private OidcClientCredentials(ImmutableArray<Outputs.FederatedIdentity> federatedIdentities)
        {
            FederatedIdentities = federatedIdentities;
        }
    }
}
