// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace Axnic.Pulumi.PocketId.Outputs
{

    [OutputType]
    public sealed class OidcFederatedIdentity
    {
        /// <summary>
        /// The expected audience of the federated identity.
        /// </summary>
        public readonly string? Audience;
        /// <summary>
        /// The issuer URL of the federated identity.
        /// </summary>
        public readonly string Issuer;
        /// <summary>
        /// The URL or content of the JWKS used to verify the federated identity.
        /// </summary>
        public readonly string? Jwks;
        /// <summary>
        /// Whether tokens issued by the federated identity can only be used once.
        /// </summary>
        public readonly bool? ReplayProtection;
        /// <summary>
        /// The expected subject of the federated identity.
        /// </summary>
        public readonly string? Subject;

        [OutputConstructor]
        private OidcFederatedIdentity(
            string? audience,

            string issuer,

            string? jwks,

            bool? replayProtection,

            string? subject)
        {
            Audience = audience;
            Issuer = issuer;
            Jwks = jwks;
            ReplayProtection = replayProtection;
            Subject = subject;
        }
    }
}
