// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface CustomClaimArgs {
    key: pulumi.Input<string>;
    value: pulumi.Input<string>;
}

export interface FederatedIdentityArgs {
    audience?: pulumi.Input<string>;
    issuer: pulumi.Input<string>;
    jwks?: pulumi.Input<string>;
    replayProtection?: pulumi.Input<boolean>;
    subject?: pulumi.Input<string>;
}

export interface OidcClientCredentialsArgs {
    federatedIdentities?: pulumi.Input<pulumi.Input<inputs.FederatedIdentityArgs>[]>;
}
