// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";
import * as enums from "../types/enums";

export interface ApiCimdAccess {
    /**
     * Whether clients registered through a Client ID Metadata Document (CIMD) may use the API.
     */
    enabled: boolean;
    /**
     * The keys of the API permissions that such clients may request. Each key must be declared in `permissions`.
     */
    permissionKeys?: string[];
}

export interface ApiPermissionState {
    /**
     * A description of the permission.
     */
    description?: string;
    /**
     * The Pocket-ID identifier of the permission.
     */
    id: string;
    /**
     * The stable identifier of the permission, e.g. "read:orders". Unique within the API.
     */
    key: string;
    /**
     * The display name of the permission.
     */
    name: string;
}

export interface OidcClientCredentials {
    /**
     * The federated identities allowed to authenticate as the client.
     */
    federatedIdentities?: outputs.OidcFederatedIdentity[];
}

export interface OidcFederatedIdentity {
    /**
     * The expected audience of the federated identity.
     */
    audience?: string;
    /**
     * The issuer URL of the federated identity.
     */
    issuer: string;
    /**
     * The URL or content of the JWKS used to verify the federated identity.
     */
    jwks?: string;
    /**
     * Whether tokens issued by the federated identity can only be used once.
     */
    replayProtection?: boolean;
    /**
     * The expected subject of the federated identity.
     */
    subject?: string;
}

