// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A Pocket-ID API (OAuth resource server) and its permissions.
 */
export class Api extends pulumi.CustomResource {
    /**
     * Get an existing Api resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): Api {
        return new Api(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pocket-id:index:Api';

    /**
     * Returns true if the given object is an instance of Api.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Api {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Api.__pulumiType;
    }

    /**
     * The access granted to clients registered through a Client ID Metadata Document, if managed.
     */
    declare public readonly cimdAccess: pulumi.Output<outputs.ApiCimdAccess | undefined>;
    /**
     * The RFC 3339 timestamp at which the API was created.
     */
    declare public /*out*/ readonly createdAt: pulumi.Output<string>;
    /**
     * The display name of the API.
     */
    declare public readonly name: pulumi.Output<string>;
    /**
     * The permissions of the API, including their Pocket-ID identifiers.
     */
    declare public readonly permissions: pulumi.Output<outputs.ApiPermissionState[]>;
    /**
     * The resource identifier (audience) of the API.
     */
    declare public readonly resource: pulumi.Output<string>;

    /**
     * Create a Api resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApiArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            if (args?.resource === undefined && !opts.urn) {
                throw new Error("Missing required property 'resource'");
            }
            resourceInputs["cimdAccess"] = args?.cimdAccess;
            resourceInputs["name"] = args?.name;
            resourceInputs["permissions"] = args?.permissions;
            resourceInputs["resource"] = args?.resource;
            resourceInputs["createdAt"] = undefined /*out*/;
        } else {
            resourceInputs["cimdAccess"] = undefined /*out*/;
            resourceInputs["createdAt"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["permissions"] = undefined /*out*/;
            resourceInputs["resource"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["resource"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(Api.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a Api resource.
 */
export interface ApiArgs {
    /**
     * The access granted to clients registered through a Client ID Metadata Document. When set it is authoritative; when omitted the server value is left untouched.
     */
    cimdAccess?: pulumi.Input<inputs.ApiCimdAccessArgs | undefined>;
    /**
     * The display name of the API.
     */
    name: pulumi.Input<string>;
    /**
     * The permissions of the API. The list is authoritative: permissions not listed here are removed.
     */
    permissions?: pulumi.Input<pulumi.Input<inputs.ApiPermissionArgsArgs>[] | undefined>;
    /**
     * The resource identifier (audience) of the API, usually a URL. Changing it replaces the API.
     */
    resource: pulumi.Input<string>;
}
