// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

/**
 * A global Pocket-ID branding image (logo, dark logo, favicon, background, e-mail image or default profile picture) uploaded from a local file or asset. Destroying it deletes the custom image and restores the default, except for the favicon and the e-mail image, which the API cannot delete: destroying those only removes the resource from state. Import with the type, e.g. "favicon". Per-user profile pictures are not covered.
 */
export class ApplicationImage extends pulumi.CustomResource {
    /**
     * Get an existing ApplicationImage resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): ApplicationImage {
        return new ApplicationImage(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pocket-id:index:ApplicationImage';

    /**
     * Returns true if the given object is an instance of ApplicationImage.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is ApplicationImage {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === ApplicationImage.__pulumiType;
    }

    /**
     * The image file as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file. It is not read back as an asset: after an import it is empty and must be set in the program.
     */
    declare public readonly image: pulumi.Output<pulumi.asset.Asset | pulumi.asset.Archive>;
    /**
     * The hex SHA-256 digest of the image content. At refresh it is the digest of the bytes currently served by Pocket-ID, so out-of-band changes show up as a diff.
     */
    declare public /*out*/ readonly sha256: pulumi.Output<string>;
    /**
     * Which image to manage. Changing it replaces the resource.
     */
    declare public readonly type: pulumi.Output<enums.ApplicationImageType>;

    /**
     * Create a ApplicationImage resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: ApplicationImageArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.image === undefined && !opts.urn) {
                throw new Error("Missing required property 'image'");
            }
            if (args?.type === undefined && !opts.urn) {
                throw new Error("Missing required property 'type'");
            }
            resourceInputs["image"] = args?.image;
            resourceInputs["type"] = args?.type;
            resourceInputs["sha256"] = undefined /*out*/;
        } else {
            resourceInputs["image"] = undefined /*out*/;
            resourceInputs["sha256"] = undefined /*out*/;
            resourceInputs["type"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["type"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(ApplicationImage.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a ApplicationImage resource.
 */
export interface ApplicationImageArgs {
    /**
     * The image file as an asset, e.g. a FileAsset. Archives are not supported. A change of content re-uploads the file. It is not read back as an asset: after an import it is empty and must be set in the program.
     */
    image: pulumi.Input<pulumi.asset.Asset | pulumi.asset.Archive>;
    /**
     * Which image to manage. Changing it replaces the resource.
     */
    type: pulumi.Input<enums.ApplicationImageType>;
}
