// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class CustomClaims extends pulumi.CustomResource {
    /**
     * Get an existing CustomClaims resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): CustomClaims {
        return new CustomClaims(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pocket-id:index:CustomClaims';

    /**
     * Returns true if the given object is an instance of CustomClaims.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is CustomClaims {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === CustomClaims.__pulumiType;
    }

    declare public readonly claims: pulumi.Output<outputs.CustomClaim[] | undefined>;
    declare public readonly ownerId: pulumi.Output<string>;
    declare public readonly ownerType: pulumi.Output<string>;

    /**
     * Create a CustomClaims resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: CustomClaimsArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.ownerId === undefined && !opts.urn) {
                throw new Error("Missing required property 'ownerId'");
            }
            if (args?.ownerType === undefined && !opts.urn) {
                throw new Error("Missing required property 'ownerType'");
            }
            resourceInputs["claims"] = args?.claims;
            resourceInputs["ownerId"] = args?.ownerId;
            resourceInputs["ownerType"] = args?.ownerType;
        } else {
            resourceInputs["claims"] = undefined /*out*/;
            resourceInputs["ownerId"] = undefined /*out*/;
            resourceInputs["ownerType"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(CustomClaims.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a CustomClaims resource.
 */
export interface CustomClaimsArgs {
    claims?: pulumi.Input<pulumi.Input<inputs.CustomClaimArgs>[]>;
    ownerId: pulumi.Input<string>;
    ownerType: pulumi.Input<string>;
}
