// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as enums from "./types/enums";
import * as utilities from "./utilities";

export function getOidcClient(args: GetOidcClientArgs, opts?: pulumi.InvokeOptions): Promise<GetOidcClientResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("pocket-id:index:getOidcClient", {
        "clientId": args.clientId,
    }, opts);
}

export interface GetOidcClientArgs {
    /**
     * The ID of the OIDC client to look up.
     */
    clientId: string;
}

export interface GetOidcClientResult {
    /**
     * The access token lifetime in minutes.
     */
    readonly accessTokenDurationMinutes: number;
    /**
     * The IDs of the user groups allowed to use the client.
     */
    readonly allowedUserGroupIds: string[];
    /**
     * The back-channel logout URL.
     */
    readonly backchannelLogoutUrl: string;
    /**
     * The allowed redirect URLs.
     */
    readonly callbackUrls: string[];
    /**
     * The ID of the client.
     */
    readonly clientId: string;
    /**
     * The client type reported by Pocket-ID.
     */
    readonly clientType: string;
    /**
     * The description of the client.
     */
    readonly description: string;
    /**
     * The federated identities allowed to authenticate as the client.
     */
    readonly federatedIdentities: outputs.OidcFederatedIdentity[];
    /**
     * Whether the client has a dark mode logo.
     */
    readonly hasDarkLogo: boolean;
    /**
     * Whether the client has a logo.
     */
    readonly hasLogo: boolean;
    /**
     * Whether access is restricted to the allowed user groups.
     */
    readonly isGroupRestricted: boolean;
    /**
     * Whether the client is public.
     */
    readonly isPublic: boolean;
    /**
     * The launch URL of the application.
     */
    readonly launchUrl: string;
    /**
     * The allowed post-logout redirect URLs.
     */
    readonly logoutCallbackUrls: string[];
    /**
     * The display name of the client.
     */
    readonly name: string;
    /**
     * Whether PKCE is required.
     */
    readonly pkceEnabled: boolean;
    /**
     * Whether PKCE is supported.
     */
    readonly pkceSupported: boolean;
    /**
     * The refresh token lifetime in minutes.
     */
    readonly refreshTokenDurationMinutes: number;
    /**
     * Whether pushed authorization requests (PAR) are required.
     */
    readonly requiresPushedAuthorizationRequests: boolean;
    /**
     * Whether users must re-authenticate on every authorization.
     */
    readonly requiresReauthentication: boolean;
    /**
     * Whether the consent screen is skipped.
     */
    readonly skipConsent: boolean;
}
export function getOidcClientOutput(args: GetOidcClientOutputArgs, opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetOidcClientResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("pocket-id:index:getOidcClient", {
        "clientId": args.clientId,
    }, opts);
}

export interface GetOidcClientOutputArgs {
    /**
     * The ID of the OIDC client to look up.
     */
    clientId: pulumi.Input<string>;
}
