// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

// Export members:
export { CustomClaimsArgs } from "./customClaims";
export type CustomClaims = import("./customClaims").CustomClaims;
export const CustomClaims: typeof import("./customClaims").CustomClaims = null as any;
utilities.lazyLoad(exports, ["CustomClaims"], () => require("./customClaims"));

export { OidcClientArgs } from "./oidcClient";
export type OidcClient = import("./oidcClient").OidcClient;
export const OidcClient: typeof import("./oidcClient").OidcClient = null as any;
utilities.lazyLoad(exports, ["OidcClient"], () => require("./oidcClient"));

export { ProviderArgs } from "./provider";
export type Provider = import("./provider").Provider;
export const Provider: typeof import("./provider").Provider = null as any;
utilities.lazyLoad(exports, ["Provider"], () => require("./provider"));

export { UserArgs } from "./user";
export type User = import("./user").User;
export const User: typeof import("./user").User = null as any;
utilities.lazyLoad(exports, ["User"], () => require("./user"));

export { UserGroupArgs } from "./userGroup";
export type UserGroup = import("./userGroup").UserGroup;
export const UserGroup: typeof import("./userGroup").UserGroup = null as any;
utilities.lazyLoad(exports, ["UserGroup"], () => require("./userGroup"));


// Export sub-modules:
import * as config from "./config";
import * as types from "./types";

export {
    config,
    types,
};

const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "pocket-id:index:CustomClaims":
                return new CustomClaims(name, <any>undefined, { urn })
            case "pocket-id:index:OidcClient":
                return new OidcClient(name, <any>undefined, { urn })
            case "pocket-id:index:User":
                return new User(name, <any>undefined, { urn })
            case "pocket-id:index:UserGroup":
                return new UserGroup(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("pocket-id", "index", _module)
pulumi.runtime.registerResourcePackage("pocket-id", {
    version: utilities.getVersion(),
    constructProvider: (name: string, type: string, urn: string): pulumi.ProviderResource => {
        if (type !== "pulumi:providers:pocket-id") {
            throw new Error(`unknown provider type ${type}`);
        }
        return new Provider(name, <any>undefined, { urn });
    },
});
