// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class OidcClient extends pulumi.CustomResource {
    /**
     * Get an existing OidcClient resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): OidcClient {
        return new OidcClient(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pocket-id:index:OidcClient';

    /**
     * Returns true if the given object is an instance of OidcClient.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is OidcClient {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === OidcClient.__pulumiType;
    }

    declare public readonly callbackUrls: pulumi.Output<string[] | undefined>;
    declare public readonly clientId: pulumi.Output<string | undefined>;
    declare public readonly credentials: pulumi.Output<outputs.OidcClientCredentials | undefined>;
    declare public /*out*/ readonly hasDarkLogo: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly hasLogo: pulumi.Output<boolean | undefined>;
    declare public readonly isGroupRestricted: pulumi.Output<boolean | undefined>;
    declare public readonly isPublic: pulumi.Output<boolean | undefined>;
    declare public readonly launchUrl: pulumi.Output<string | undefined>;
    declare public readonly logoutCallbackUrls: pulumi.Output<string[] | undefined>;
    declare public readonly name: pulumi.Output<string>;
    declare public readonly pkceEnabled: pulumi.Output<boolean | undefined>;
    declare public /*out*/ readonly pkceSupported: pulumi.Output<boolean | undefined>;
    declare public readonly requiresPushedAuthorizationRequests: pulumi.Output<boolean | undefined>;
    declare public readonly requiresReauthentication: pulumi.Output<boolean | undefined>;
    declare public readonly skipConsent: pulumi.Output<boolean | undefined>;

    /**
     * Create a OidcClient resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: OidcClientArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.name === undefined && !opts.urn) {
                throw new Error("Missing required property 'name'");
            }
            resourceInputs["callbackUrls"] = args?.callbackUrls;
            resourceInputs["clientId"] = args?.clientId;
            resourceInputs["credentials"] = args?.credentials;
            resourceInputs["isGroupRestricted"] = args?.isGroupRestricted;
            resourceInputs["isPublic"] = args?.isPublic;
            resourceInputs["launchUrl"] = args?.launchUrl;
            resourceInputs["logoutCallbackUrls"] = args?.logoutCallbackUrls;
            resourceInputs["name"] = args?.name;
            resourceInputs["pkceEnabled"] = args?.pkceEnabled;
            resourceInputs["requiresPushedAuthorizationRequests"] = args?.requiresPushedAuthorizationRequests;
            resourceInputs["requiresReauthentication"] = args?.requiresReauthentication;
            resourceInputs["skipConsent"] = args?.skipConsent;
            resourceInputs["hasDarkLogo"] = undefined /*out*/;
            resourceInputs["hasLogo"] = undefined /*out*/;
            resourceInputs["pkceSupported"] = undefined /*out*/;
        } else {
            resourceInputs["callbackUrls"] = undefined /*out*/;
            resourceInputs["clientId"] = undefined /*out*/;
            resourceInputs["credentials"] = undefined /*out*/;
            resourceInputs["hasDarkLogo"] = undefined /*out*/;
            resourceInputs["hasLogo"] = undefined /*out*/;
            resourceInputs["isGroupRestricted"] = undefined /*out*/;
            resourceInputs["isPublic"] = undefined /*out*/;
            resourceInputs["launchUrl"] = undefined /*out*/;
            resourceInputs["logoutCallbackUrls"] = undefined /*out*/;
            resourceInputs["name"] = undefined /*out*/;
            resourceInputs["pkceEnabled"] = undefined /*out*/;
            resourceInputs["pkceSupported"] = undefined /*out*/;
            resourceInputs["requiresPushedAuthorizationRequests"] = undefined /*out*/;
            resourceInputs["requiresReauthentication"] = undefined /*out*/;
            resourceInputs["skipConsent"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(OidcClient.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a OidcClient resource.
 */
export interface OidcClientArgs {
    callbackUrls?: pulumi.Input<pulumi.Input<string>[]>;
    clientId?: pulumi.Input<string>;
    credentials?: pulumi.Input<inputs.OidcClientCredentialsArgs>;
    isGroupRestricted?: pulumi.Input<boolean>;
    isPublic?: pulumi.Input<boolean>;
    launchUrl?: pulumi.Input<string>;
    logoutCallbackUrls?: pulumi.Input<pulumi.Input<string>[]>;
    name: pulumi.Input<string>;
    pkceEnabled?: pulumi.Input<boolean>;
    requiresPushedAuthorizationRequests?: pulumi.Input<boolean>;
    requiresReauthentication?: pulumi.Input<boolean>;
    skipConsent?: pulumi.Input<boolean>;
}
