// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * A Pocket-ID user. Group membership is managed with the UserGroupMembers resource.
 */
export class User extends pulumi.CustomResource {
    /**
     * Get an existing User resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): User {
        return new User(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pocket-id:index:User';

    /**
     * Returns true if the given object is an instance of User.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is User {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === User.__pulumiType;
    }

    /**
     * Whether the user is disabled and cannot sign in.
     */
    declare public readonly disabled: pulumi.Output<boolean | undefined>;
    /**
     * The name displayed for the user. Pocket-ID may derive it from the first and last names when unset.
     */
    declare public readonly displayName: pulumi.Output<string | undefined>;
    /**
     * The email address of the user.
     */
    declare public readonly email: pulumi.Output<string | undefined>;
    /**
     * Whether the email address is considered verified.
     */
    declare public readonly emailVerified: pulumi.Output<boolean | undefined>;
    /**
     * The first name of the user.
     */
    declare public readonly firstName: pulumi.Output<string | undefined>;
    /**
     * Whether the user is an administrator.
     */
    declare public readonly isAdmin: pulumi.Output<boolean | undefined>;
    /**
     * The last name of the user.
     */
    declare public readonly lastName: pulumi.Output<string | undefined>;
    /**
     * The locale of the user, for example en or fr.
     */
    declare public readonly locale: pulumi.Output<string | undefined>;
    /**
     * The unique login name of the user.
     */
    declare public readonly username: pulumi.Output<string>;

    /**
     * Create a User resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.username === undefined && !opts.urn) {
                throw new Error("Missing required property 'username'");
            }
            resourceInputs["disabled"] = args?.disabled;
            resourceInputs["displayName"] = args?.displayName;
            resourceInputs["email"] = args?.email;
            resourceInputs["emailVerified"] = args?.emailVerified;
            resourceInputs["firstName"] = args?.firstName;
            resourceInputs["isAdmin"] = args?.isAdmin;
            resourceInputs["lastName"] = args?.lastName;
            resourceInputs["locale"] = args?.locale;
            resourceInputs["username"] = args?.username;
        } else {
            resourceInputs["disabled"] = undefined /*out*/;
            resourceInputs["displayName"] = undefined /*out*/;
            resourceInputs["email"] = undefined /*out*/;
            resourceInputs["emailVerified"] = undefined /*out*/;
            resourceInputs["firstName"] = undefined /*out*/;
            resourceInputs["isAdmin"] = undefined /*out*/;
            resourceInputs["lastName"] = undefined /*out*/;
            resourceInputs["locale"] = undefined /*out*/;
            resourceInputs["username"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(User.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a User resource.
 */
export interface UserArgs {
    /**
     * Whether the user is disabled and cannot sign in.
     */
    disabled?: pulumi.Input<boolean | undefined>;
    /**
     * The name displayed for the user. Pocket-ID may derive it from the first and last names when unset.
     */
    displayName?: pulumi.Input<string | undefined>;
    /**
     * The email address of the user.
     */
    email?: pulumi.Input<string | undefined>;
    /**
     * Whether the email address is considered verified.
     */
    emailVerified?: pulumi.Input<boolean | undefined>;
    /**
     * The first name of the user.
     */
    firstName?: pulumi.Input<string | undefined>;
    /**
     * Whether the user is an administrator.
     */
    isAdmin?: pulumi.Input<boolean | undefined>;
    /**
     * The last name of the user.
     */
    lastName?: pulumi.Input<string | undefined>;
    /**
     * The locale of the user, for example en or fr.
     */
    locale?: pulumi.Input<string | undefined>;
    /**
     * The unique login name of the user.
     */
    username: pulumi.Input<string>;
}
