// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

/**
 * The authoritative set of members of a user group. Destroying the resource removes every member from the group.
 */
export class UserGroupMembers extends pulumi.CustomResource {
    /**
     * Get an existing UserGroupMembers resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, opts?: pulumi.CustomResourceOptions): UserGroupMembers {
        return new UserGroupMembers(name, undefined as any, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'pocket-id:index:UserGroupMembers';

    /**
     * Returns true if the given object is an instance of UserGroupMembers.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is UserGroupMembers {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === UserGroupMembers.__pulumiType;
    }

    /**
     * The ID of the group. Changing it replaces the resource.
     */
    declare public readonly groupId: pulumi.Output<string>;
    /**
     * The IDs of all users that belong to the group. The set is authoritative: users not listed are removed from the group.
     */
    declare public readonly userIds: pulumi.Output<string[]>;

    /**
     * Create a UserGroupMembers resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: UserGroupMembersArgs, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (!opts.id) {
            if (args?.groupId === undefined && !opts.urn) {
                throw new Error("Missing required property 'groupId'");
            }
            if (args?.userIds === undefined && !opts.urn) {
                throw new Error("Missing required property 'userIds'");
            }
            resourceInputs["groupId"] = args?.groupId;
            resourceInputs["userIds"] = args?.userIds;
        } else {
            resourceInputs["groupId"] = undefined /*out*/;
            resourceInputs["userIds"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        const replaceOnChanges = { replaceOnChanges: ["groupId"] };
        opts = pulumi.mergeOptions(opts, replaceOnChanges);
        super(UserGroupMembers.__pulumiType, name, resourceInputs, opts);
    }
}

/**
 * The set of arguments for constructing a UserGroupMembers resource.
 */
export interface UserGroupMembersArgs {
    /**
     * The ID of the group. Changing it replaces the resource.
     */
    groupId: pulumi.Input<string>;
    /**
     * The IDs of all users that belong to the group. The set is authoritative: users not listed are removed from the group.
     */
    userIds: pulumi.Input<pulumi.Input<string>[]>;
}
